In [3]:
import pandas as pd

In [4]:
%pip install pandas

Requirement already satisfied: pandas in c:\Users\Krishna Prajapati\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\Krishna Prajapati\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Krishna Prajapati\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Krishna Prajapati\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Krishna Prajapati\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd

In [6]:
import numpy as np

In [7]:
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
%pip install matplotlib seaborn

Requirement already satisfied: matplotlib in c:\Users\Krishna Prajapati\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.11.1)
Requirement already satisfied: seaborn in c:\Users\Krishna Prajapati\AppData\Local\Programs\Python\Python313\Lib\site-packages (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\Krishna Prajapati\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\Krishna Prajapati\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\Krishna Prajapati\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\Krishna Prajapati\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.25 in c:\Users\Krishna Prajapati\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (2.5.2)
Requirement already satisfied: packaging>=20.0 in C:\Users\Krishna Prajapati\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in c:\Users\Krishna Prajapati\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\Krishna Prajapati\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\Krishna Prajapati\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in c:\Users\Krishna Prajapati\AppData\Local\Programs\Python\Python313\Lib\site-packages (from seaborn) (3.0.5)
Requirement already satisfied: tzdata in c:\Users\Krishna Prajapati\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Krishna Prajapati\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
import matplotlib.pyplot as plt

In [10]:
import seaborn as sns

In [11]:
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Matplotlib:", plt.matplotlib.__version__)
print("Seaborn:", sns.__version__)

Pandas: 3.0.5
NumPy: 2.5.2
Matplotlib: 3.11.1
Seaborn: 0.13.2

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Matplotlib:", plt.matplotlib.__version__)
print("Seaborn:", sns.__version__)

Pandas: 3.0.5
NumPy: 2.5.2
Matplotlib: 3.11.1
Seaborn: 0.13.2

In [14]:
from pathlib import Path

BASE_DIR = Path.cwd().parent

DATA_PATH = BASE_DIR / "data" / "Nassau Candy Distributor.csv"

print("Dataset path:")
print(DATA_PATH)

print("\nFile exists:")
print(DATA_PATH.exists())

Dataset path:
c:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization\data\Nassau Candy Distributor.csv

File exists:
True

In [15]:
from pathlib import Path

BASE_DIR = Path.cwd().parent

DATA_PATH = BASE_DIR / "data" / "Nassau Candy Distributor.csv"

print("Dataset path:")
print(DATA_PATH)

print("\nFile exists:")
print(DATA_PATH.exists())

Dataset path:
c:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization\data\Nassau Candy Distributor.csv

File exists:
True

In [16]:
from pathlib import Path

BASE_DIR = Path.cwd().parent

DATA_PATH = BASE_DIR / "data" / "Nassau Candy Distributor.csv"

print("Dataset path:")
print(DATA_PATH)

print("\nFile exists:")
print(DATA_PATH.exists())

Dataset path:
c:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization\data\Nassau Candy Distributor.csv

File exists:
True

In [17]:
df = pd.read_csv(DATA_PATH)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [18]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [19]:
df.shape

(10194, 18)

In [20]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Country/Region',
 'City',
 'State/Province',
 'Postal Code',
 'Division',
 'Region',
 'Product ID',
 'Product Name',
 'Sales',
 'Units',
 'Gross Profit',
 'Cost']

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  str
 2   Order Date      10194 non-null  str
 3   Ship Date       10194 non-null  str
 4   Ship Mode       10194 non-null  str
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  str
 7   City            10194 non-null  str
 8   State/Province  10194 non-null  str
 9   Postal Code     10194 non-null  str
 10  Division        10194 non-null  str
 11  Region          10194 non-null  str
 12  Product ID      10194 non-null  str
 13  Product Name    10194 non-null  str
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), str(12)
memory usage: 1.4 MB

In [22]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.describe()

,Row ID,Customer ID,Sales,Units,Gross Profit,Cost
count,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,134468.961154,13.908537,3.791838,9.166451,4.742087
std,2942.898656,20231.483007,11.341020,2.228317,6.643740,5.061647
min,1.000000,100006.000000,1.250000,1.000000,0.250000,0.600000
25%,2549.250000,117212.000000,7.200000,2.000000,4.900000,2.400000
50%,5097.500000,133550.000000,10.800000,3.000000,7.470000,3.600000
75%,7645.750000,152051.000000,18.000000,5.000000,12.250000,5.700000
max,10194.000000,192314.000000,260.000000,14.000000,130.000000,130.000000

In [25]:
df.describe(include="object")

C:\Users\Krishna Prajapati\AppData\Local\Temp\ipykernel_3592\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,Order ID,Order Date,Ship Date,Ship Mode,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name
count,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194
unique,8549,717,1338,4,2,542,59,654,3,4,15,15
top,US-2021-155502-CHO-MIL-31000,02-09-2025,07-06-2028,Standard Class,United States,New York City,California,10035,Chocolate,Pacific,CHO-MIL-31000,Wonka Bar - Milk Chocolate
freq,5,62,38,6120,9994,915,2001,263,9844,3253,2137,2137

In [26]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

In [27]:
df.duplicated().sum()

np.int64(0)

In [28]:
df.describe()

,Row ID,Customer ID,Sales,Units,Gross Profit,Cost
count,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,134468.961154,13.908537,3.791838,9.166451,4.742087
std,2942.898656,20231.483007,11.341020,2.228317,6.643740,5.061647
min,1.000000,100006.000000,1.250000,1.000000,0.250000,0.600000
25%,2549.250000,117212.000000,7.200000,2.000000,4.900000,2.400000
50%,5097.500000,133550.000000,10.800000,3.000000,7.470000,3.600000
75%,7645.750000,152051.000000,18.000000,5.000000,12.250000,5.700000
max,10194.000000,192314.000000,260.000000,14.000000,130.000000,130.000000

In [29]:
df.describe(include="object")

C:\Users\Krishna Prajapati\AppData\Local\Temp\ipykernel_3592\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,Order ID,Order Date,Ship Date,Ship Mode,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name
count,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194
unique,8549,717,1338,4,2,542,59,654,3,4,15,15
top,US-2021-155502-CHO-MIL-31000,02-09-2025,07-06-2028,Standard Class,United States,New York City,California,10035,Chocolate,Pacific,CHO-MIL-31000,Wonka Bar - Milk Chocolate
freq,5,62,38,6120,9994,915,2001,263,9844,3253,2137,2137

In [30]:
# Check missing values in each column

missing_values = df.isnull().sum()

print("Missing Values:")
print(missing_values)

Missing Values:
Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

In [31]:
# Check duplicate rows

duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [32]:
# Check number of unique values in important categorical columns

print("Ship Modes:")
print(df["Ship Mode"].unique())

print("\nRegions:")
print(df["Region"].unique())

print("\nDivisions:")
print(df["Division"].unique())

print("\nCountries:")
print(df["Country/Region"].unique())

Ship Modes:
<StringArray>
['Standard Class', 'First Class', 'Second Class', 'Same Day']
Length: 4, dtype: str

Regions:
<StringArray>
['Interior', 'Atlantic', 'Gulf', 'Pacific']
Length: 4, dtype: str

Divisions:
<StringArray>
['Chocolate', 'Other', 'Sugar']
Length: 3, dtype: str

Countries:
<StringArray>
['United States', 'Canada']
Length: 2, dtype: str

In [33]:
# Check missing values in every column

missing_values = df.isnull().sum()

print("Missing Values:")
print(missing_values)

Missing Values:
Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

In [34]:
# Check duplicate rows

duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [35]:
# Step 3: Convert date columns safely to datetime

df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="mixed",
    errors="coerce"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    format="mixed",
    errors="coerce"
)

# Check the result
print("Date columns converted successfully!")

print("\nData Types:")
print(df[["Order Date", "Ship Date"]].dtypes)

print("\nMissing dates after conversion:")
print(df[["Order Date", "Ship Date"]].isna().sum())

Date columns converted successfully!

Data Types:
Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

Missing dates after conversion:
Order Date    0
Ship Date     0
dtype: int64

In [36]:
# Verify converted dates

print("First 10 Order Dates:")
print(df["Order Date"].head(10))

print("\nFirst 10 Ship Dates:")
print(df["Ship Date"].head(10))

First 10 Order Dates:
0   2024-03-01
1   2024-04-01
2   2024-04-01
3   2024-04-01
4   2024-05-01
5   2024-06-01
6   2024-06-01
7   2024-06-01
8   2024-06-01
9   2024-06-01
Name: Order Date, dtype: datetime64[us]

First 10 Ship Dates:
0   2026-06-30
1   2026-01-07
2   2026-01-07
3   2026-01-07
4   2026-05-07
5   2026-03-07
6   2026-03-07
7   2026-06-30
8   2026-03-07
9   2026-03-07
Name: Ship Date, dtype: datetime64[us]

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  str
 2   Order Date      10194 non-null  datetime64[us]
 3   Ship Date       10194 non-null  datetime64[us]
 4   Ship Mode       10194 non-null  str
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  str
 7   City            10194 non-null  str
 8   State/Province  10194 non-null  str
 9   Postal Code     10194 non-null  str
 10  Division        10194 non-null  str
 11  Region          10194 non-null  str
 12  Product ID      10194 non-null  str
 13  Product Name    10194 non-null  str
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: datetime64[us](2), float64(3), int64(3), str(10)
memory usage: 1.4 MB

In [38]:
# Step 4: Check missing values

missing_values = df.isnull().sum()

print("Missing Values in Each Column:")
print(missing_values)

print("\nTotal Missing Values:")
print(missing_values.sum())

Missing Values in Each Column:
Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

Total Missing Values:
0

In [39]:
# Step 5: Check duplicate rows

duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [40]:
# Step 6: Numerical columns summary

numeric_columns = ["Sales", "Units", "Gross Profit", "Cost"]

print("Numerical Columns Summary:")
display(df[numeric_columns].describe())

Numerical Columns Summary:

              Sales         Units  Gross Profit          Cost
count  10194.000000  10194.000000  10194.000000  10194.000000
mean      13.908537      3.791838      9.166451      4.742087
std       11.341020      2.228317      6.643740      5.061647
min        1.250000      1.000000      0.250000      0.600000
25%        7.200000      2.000000      4.900000      2.400000
50%       10.800000      3.000000      7.470000      3.600000
75%       18.000000      5.000000     12.250000      5.700000
max      260.000000     14.000000    130.000000    130.000000

In [41]:
# Step 7: Key Business KPIs

total_sales = df["Sales"].sum()
total_units = df["Units"].sum()
total_profit = df["Gross Profit"].sum()
total_cost = df["Cost"].sum()

print("========== BUSINESS KPIs ==========")
print(f"Total Sales      : ${total_sales:,.2f}")
print(f"Total Units Sold : {total_units:,}")
print(f"Total Gross Profit: ${total_profit:,.2f}")
print(f"Total Cost       : ${total_cost:,.2f}")

========== BUSINESS KPIs ==========
Total Sales      : $141,783.63
Total Units Sold : 38,654
Total Gross Profit: $93,442.80
Total Cost       : $48,340.83

In [42]:
# Step 8: Overall Profit Margin
# This cell independently loads the dataset if df is not available.

from pathlib import Path
import pandas as pd

# Find the project root
BASE_DIR = Path.cwd().parent

# Find Nassau Candy CSV file
csv_files = list((BASE_DIR / "data").glob("*.csv"))

nassau_files = [
    file for file in csv_files
    if "Nassau Candy Distributor" in file.name
]

if len(nassau_files) == 0:
    raise FileNotFoundError(
        "Nassau Candy Distributor CSV file was not found in the data folder."
    )

# Load dataset
DATA_PATH = nassau_files[0]
df = pd.read_csv(DATA_PATH)

# Calculate totals directly from the dataset
total_sales = df["Sales"].sum()
total_profit = df["Gross Profit"].sum()

# Calculate profit margin safely
if total_sales > 0:
    profit_margin = (total_profit / total_sales) * 100
else:
    profit_margin = 0

print("========== PROFIT ANALYSIS ==========")
print(f"Dataset loaded : {DATA_PATH.name}")
print(f"Rows           : {len(df):,}")
print(f"Total Sales    : ${total_sales:,.2f}")
print(f"Total Profit   : ${total_profit:,.2f}")
print(f"Profit Margin  : {profit_margin:.2f}%")

========== PROFIT ANALYSIS ==========
Dataset loaded : Nassau Candy Distributor.csv
Rows           : 10,194
Total Sales    : $141,783.63
Total Profit   : $93,442.80
Profit Margin  : 65.91%

In [43]:
# Step 9: Top 10 Products by Sales

# Create product-level analysis
product_analysis = (
    df.groupby(["Product ID", "Product Name"], as_index=False)
      .agg(
          Total_Sales=("Sales", "sum"),
          Total_Units=("Units", "sum"),
          Total_Gross_Profit=("Gross Profit", "sum"),
          Total_Cost=("Cost", "sum")
      )
      .sort_values("Total_Sales", ascending=False)
)

# Display Top 10 Products
print("========== TOP 10 PRODUCTS BY SALES ==========")

top_10_products = product_analysis.head(10).copy()

print(top_10_products.to_string(index=False))

print("\nTop product by sales:")
print(top_10_products.iloc[0]["Product Name"])

print(f"\nHighest product sales: ${top_10_products.iloc[0]['Total_Sales']:,.2f}")

========== TOP 10 PRODUCTS BY SALES ==========
   Product ID                      Product Name  Total_Sales  Total_Units  Total_Gross_Profit  Total_Cost
CHO-TRI-54000 Wonka Bar - Triple Dazzle Caramel     28485.00         7596            18610.20     9874.80
CHO-SCR-58000    Wonka Bar -Scrumdiddlyumptious     27874.80         7743            19357.50     8517.30
CHO-MIL-31000        Wonka Bar - Milk Chocolate     26867.75         8267            17443.37     9424.38
CHO-FUD-51000         Wonka Bar - Fudge Mallows     24890.40         6914            16593.60     8296.80
CHO-NUT-13000 Wonka Bar - Nutty Crunch Surprise     23574.95         6755            16819.95     6755.00
OTH-LIC-15000                Lickable Wallpaper      7860.00          393             3930.00     3930.00
OTH-KAZ-38000                         Kazookles      1205.75          371               92.75     1113.00
OTH-GUM-21000                         Wonka Gum       597.50          478              310.70      286.80
SUG-EVE-47000            Everlasting Gobstopper       130.00           13              104.00       26.00
OTH-FIZ-56000              Fizzy Lifting Drinks        78.75           21               47.25       31.50

Top product by sales:
Wonka Bar - Triple Dazzle Caramel

Highest product sales: $28,485.00

In [44]:
# Step 10: Product Profitability Analysis

# Calculate profit margin for each product
product_analysis["Profit_Margin_%"] = (
    product_analysis["Total_Gross_Profit"] /
    product_analysis["Total_Sales"]
) * 100

# Handle any invalid values
product_analysis["Profit_Margin_%"] = (
    product_analysis["Profit_Margin_%"]
    .replace([float("inf"), -float("inf")], 0)
    .fillna(0)
)

# Sort products by profit margin
profitability_analysis = product_analysis.sort_values(
    "Profit_Margin_%",
    ascending=False
).copy()

print("========== TOP 10 PRODUCTS BY PROFIT MARGIN ==========")

top_10_profitable = profitability_analysis.head(10)

print(
    top_10_profitable[
        [
            "Product ID",
            "Product Name",
            "Total_Sales",
            "Total_Units",
            "Total_Gross_Profit",
            "Total_Cost",
            "Profit_Margin_%"
        ]
    ].to_string(index=False)
)

print("\n========== MOST PROFITABLE PRODUCT ==========")

best_product = top_10_profitable.iloc[0]

print(f"Product Name      : {best_product['Product Name']}")
print(f"Total Sales       : ${best_product['Total_Sales']:,.2f}")
print(f"Gross Profit      : ${best_product['Total_Gross_Profit']:,.2f}")
print(f"Profit Margin     : {best_product['Profit_Margin_%']:.2f}%")

========== TOP 10 PRODUCTS BY PROFIT MARGIN ==========
   Product ID                      Product Name  Total_Sales  Total_Units  Total_Gross_Profit  Total_Cost  Profit_Margin_%
SUG-EVE-47000            Everlasting Gobstopper       130.00           13              104.00       26.00        80.000000
SUG-HAI-55000                       Hair Toffee        76.50           17               59.50       17.00        77.777778
CHO-NUT-13000 Wonka Bar - Nutty Crunch Surprise     23574.95         6755            16819.95     6755.00        71.346705
CHO-SCR-58000    Wonka Bar -Scrumdiddlyumptious     27874.80         7743            19357.50     8517.30        69.444444
CHO-FUD-51000         Wonka Bar - Fudge Mallows     24890.40         6914            16593.60     8296.80        66.666667
CHO-TRI-54000 Wonka Bar - Triple Dazzle Caramel     28485.00         7596            18610.20     9874.80        65.333333
CHO-MIL-31000        Wonka Bar - Milk Chocolate     26867.75         8267            17443.37     9424.38        64.923077
SUG-LAF-25000                       Laffy Taffy        53.73           27               33.48       20.25        62.311558
OTH-FIZ-56000              Fizzy Lifting Drinks        78.75           21               47.25       31.50        60.000000
OTH-GUM-21000                         Wonka Gum       597.50          478              310.70      286.80        52.000000

========== MOST PROFITABLE PRODUCT ==========
Product Name      : Everlasting Gobstopper
Total Sales       : $130.00
Gross Profit      : $104.00
Profit Margin     : 80.00%

In [45]:
# ============================================================
# STEP 11: SHIPPING PERFORMANCE ANALYSIS
# ============================================================

import pandas as pd

# ------------------------------------------------------------
# 1. Make sure both date columns are datetime
# ------------------------------------------------------------

df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    errors="coerce"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    errors="coerce"
)

# ------------------------------------------------------------
# 2. Check whether any invalid dates were created
# ------------------------------------------------------------

invalid_order_dates = df["Order Date"].isna().sum()
invalid_ship_dates = df["Ship Date"].isna().sum()

print("Invalid Order Dates :", invalid_order_dates)
print("Invalid Ship Dates  :", invalid_ship_dates)

# ------------------------------------------------------------
# 3. Calculate delivery time in days
# ------------------------------------------------------------

df["Delivery_Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

# ------------------------------------------------------------
# 4. Check invalid delivery values
# ------------------------------------------------------------

invalid_delivery = (df["Delivery_Days"] < 0).sum()

print("Invalid Delivery Days:", invalid_delivery)

# ------------------------------------------------------------
# 5. Shipping Performance Summary
# ------------------------------------------------------------

print("\n========== SHIPPING PERFORMANCE ==========")

print(
    f"Average Delivery Days : "
    f"{df['Delivery_Days'].mean():.2f}"
)

print(
    f"Minimum Delivery Days : "
    f"{df['Delivery_Days'].min():.0f}"
)

print(
    f"Maximum Delivery Days : "
    f"{df['Delivery_Days'].max():.0f}"
)

print(
    f"Median Delivery Days  : "
    f"{df['Delivery_Days'].median():.2f}"
)

# ------------------------------------------------------------
# 6. Shipping mode performance
# ------------------------------------------------------------

shipping_analysis = (
    df.groupby("Ship Mode")
      .agg(
          Orders=("Order ID", "count"),
          Average_Delivery_Days=("Delivery_Days", "mean"),
          Minimum_Delivery_Days=("Delivery_Days", "min"),
          Maximum_Delivery_Days=("Delivery_Days", "max")
      )
      .sort_values("Average_Delivery_Days")
)

print("\n========== SHIPPING MODE ANALYSIS ==========")

print(shipping_analysis.round(2).to_string())

Invalid Order Dates : 6064
Invalid Ship Dates  : 0
Invalid Delivery Days: 0

========== SHIPPING PERFORMANCE ==========
Average Delivery Days : 1366.01
Minimum Delivery Days : 613
Maximum Delivery Days : 1965

C:\Users\Krishna Prajapati\AppData\Local\Temp\ipykernel_3592\1193134755.py:16: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Ship Date"] = pd.to_datetime(

Median Delivery Days  : 1361.00

========== SHIPPING MODE ANALYSIS ==========
                Orders  Average_Delivery_Days  Minimum_Delivery_Days  Maximum_Delivery_Days
Ship Mode
Standard Class    6120                1354.83                  617.0                 1965.0
Second Class      1979                1372.39                  644.0                 1960.0
First Class       1548                1385.60                  613.0                 1961.0
Same Day           547                1405.35                  785.0                 1929.0

In [46]:
# ============================================================
# STEP 12: SHIPPING MODE PERFORMANCE ANALYSIS
# ============================================================

# Analyze shipping performance by Ship Mode

shipping_mode_analysis = (
    df.groupby("Ship Mode")
      .agg(
          Total_Orders=("Order ID", "count"),
          Total_Sales=("Sales", "sum"),
          Total_Units=("Units", "sum"),
          Total_Gross_Profit=("Gross Profit", "sum"),
          Average_Delivery_Days=("Delivery_Days", "mean")
      )
      .reset_index()
)

# Calculate profit margin for each shipping mode
shipping_mode_analysis["Profit_Margin_%"] = (
    shipping_mode_analysis["Total_Gross_Profit"]
    / shipping_mode_analysis["Total_Sales"]
) * 100

# Sort by average delivery time
shipping_mode_analysis = shipping_mode_analysis.sort_values(
    "Average_Delivery_Days"
)

# Display results
print("========== SHIPPING MODE PERFORMANCE ==========\n")

print(
    shipping_mode_analysis.to_string(
        index=False,
        formatters={
            "Total_Sales": "${:,.2f}".format,
            "Total_Gross_Profit": "${:,.2f}".format,
            "Average_Delivery_Days": "{:.2f}".format,
            "Profit_Margin_%": "{:.2f}%".format
        }
    )
)

# ------------------------------------------------------------
# Best and slowest shipping modes
# ------------------------------------------------------------

fastest_mode = shipping_mode_analysis.iloc[0]["Ship Mode"]
fastest_delivery = shipping_mode_analysis.iloc[0]["Average_Delivery_Days"]

slowest_mode = shipping_mode_analysis.iloc[-1]["Ship Mode"]
slowest_delivery = shipping_mode_analysis.iloc[-1]["Average_Delivery_Days"]

print("\n========== SHIPPING INSIGHTS ==========")

print(
    f"Fastest Shipping Mode : {fastest_mode}"
)

print(
    f"Average Delivery Time : {fastest_delivery:.2f} days"
)

print(
    f"\nSlowest Shipping Mode : {slowest_mode}"
)

print(
    f"Average Delivery Time : {slowest_delivery:.2f} days"
)

========== SHIPPING MODE PERFORMANCE ==========

     Ship Mode  Total_Orders Total_Sales  Total_Units Total_Gross_Profit Average_Delivery_Days Profit_Margin_%
Standard Class          6120  $85,490.35        23409         $56,424.46               1354.83          66.00%
  Second Class          1979  $27,860.22         7546         $18,306.52               1372.39          65.71%
   First Class          1548  $21,319.39         5724         $14,011.09               1385.60          65.72%
      Same Day           547   $7,113.67         1975          $4,700.73               1405.35          66.08%

========== SHIPPING INSIGHTS ==========
Fastest Shipping Mode : Standard Class
Average Delivery Time : 1354.83 days

Slowest Shipping Mode : Same Day
Average Delivery Time : 1405.35 days

In [47]:
# ============================================================
# STEP 12A: VALIDATE ORDER DATE AND SHIP DATE
# ============================================================

print("========== DATE VALIDATION ==========\n")

print("Order Date Range:")
print("Minimum:", df["Order Date"].min())
print("Maximum:", df["Order Date"].max())

print("\nShip Date Range:")
print("Minimum:", df["Ship Date"].min())
print("Maximum:", df["Ship Date"].max())

print("\nFirst 10 Date Records:")
print(
    df[["Order Date", "Ship Date", "Ship Mode", "Delivery_Days"]]
    .head(10)
    .to_string(index=False)
)

print("\nDate Data Types:")
print(df[["Order Date", "Ship Date"]].dtypes)

print("\nDelivery Days Statistics:")
print(
    df["Delivery_Days"]
    .describe()
    .to_string()
)

========== DATE VALIDATION ==========

Order Date Range:
Minimum: 2024-01-02 00:00:00
Maximum: 2025-12-12 00:00:00

Ship Date Range:
Minimum: 2026-06-30 00:00:00
Maximum: 2030-06-28 00:00:00

First 10 Date Records:
Order Date  Ship Date      Ship Mode  Delivery_Days
2024-03-01 2026-06-30 Standard Class          851.0
2024-04-01 2026-07-01 Standard Class          821.0
2024-04-01 2026-07-01 Standard Class          821.0
2024-04-01 2026-07-01 Standard Class          821.0
2024-05-01 2026-07-05 Standard Class          795.0
2024-06-01 2026-07-03 Standard Class          762.0
2024-06-01 2026-07-03 Standard Class          762.0
2024-06-01 2026-06-30    First Class          759.0
2024-06-01 2026-07-03 Standard Class          762.0
2024-06-01 2026-07-03 Standard Class          762.0

Date Data Types:
Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

Delivery Days Statistics:
count    4130.000000
mean     1366.009685
std       302.829972
min       613.000000
25%      1155.000000
50%      1361.000000
75%      1598.000000
max      1965.000000

In [48]:
# ============================================================
# STEP 12B: LEAD TIME DATA QUALITY ANALYSIS
# ============================================================

print("========== LEAD TIME DATA QUALITY ANALYSIS ==========\n")

# Basic statistics
lead_time_stats = df["Delivery_Days"].describe()

print("Lead Time Statistics:")
print(lead_time_stats)

# Percentiles
q1 = df["Delivery_Days"].quantile(0.25)
median = df["Delivery_Days"].quantile(0.50)
q3 = df["Delivery_Days"].quantile(0.75)

print("\n========== LEAD TIME PERCENTILES ==========")

print(f"25th Percentile : {q1:.2f} days")
print(f"Median          : {median:.2f} days")
print(f"75th Percentile : {q3:.2f} days")

# IQR
iqr = q3 - q1

lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)

print("\n========== IQR ANALYSIS ==========")

print(f"IQR             : {iqr:.2f} days")
print(f"Lower Bound     : {lower_bound:.2f} days")
print(f"Upper Bound     : {upper_bound:.2f} days")

# Count potential outliers
outlier_count = (
    (df["Delivery_Days"] < lower_bound) |
    (df["Delivery_Days"] > upper_bound)
).sum()

print(f"Potential Outliers : {outlier_count:,}")

# Negative lead times
negative_count = (df["Delivery_Days"] < 0).sum()

print(f"Negative Lead Times : {negative_count:,}")

# Zero-day shipments
zero_day_count = (df["Delivery_Days"] == 0).sum()

print(f"Zero-Day Shipments : {zero_day_count:,}")

print("\n========== DATA QUALITY RESULT ==========")

if negative_count == 0:
    print("✓ No negative lead times found.")
else:
    print("⚠ Negative lead times detected.")

if outlier_count == 0:
    print("✓ No statistical lead-time outliers found.")
else:
    print(f"⚠ {outlier_count:,} potential lead-time outliers detected.")

========== LEAD TIME DATA QUALITY ANALYSIS ==========

Lead Time Statistics:
count    4130.000000
mean     1366.009685
std       302.829972
min       613.000000
25%      1155.000000
50%      1361.000000
75%      1598.000000
max      1965.000000
Name: Delivery_Days, dtype: float64

========== LEAD TIME PERCENTILES ==========
25th Percentile : 1155.00 days
Median          : 1361.00 days
75th Percentile : 1598.00 days

========== IQR ANALYSIS ==========
IQR             : 443.00 days
Lower Bound     : 490.50 days
Upper Bound     : 2262.50 days
Potential Outliers : 0
Negative Lead Times : 0
Zero-Day Shipments : 0

========== DATA QUALITY RESULT ==========
✓ No negative lead times found.
✓ No statistical lead-time outliers found.

In [49]:
# ============================================================
# STEP 12C: DATE COMPLETENESS & PARSING VALIDATION
# ============================================================

print("========== DATE COMPLETENESS CHECK ==========\n")

# Total dataset rows
total_rows = len(df)

print(f"Total Dataset Rows        : {total_rows:,}")

# Check missing values in original date columns
print("\n========== ORIGINAL DATE COLUMNS ==========")

print(f"Missing Order Date        : {df['Order Date'].isna().sum():,}")
print(f"Missing Ship Date         : {df['Ship Date'].isna().sum():,}")

# Check missing values in Delivery_Days
print("\n========== DELIVERY DAYS ==========")

delivery_missing = df["Delivery_Days"].isna().sum()
delivery_valid = df["Delivery_Days"].notna().sum()

print(f"Valid Delivery_Days       : {delivery_valid:,}")
print(f"Missing Delivery_Days     : {delivery_missing:,}")

# Percentage
valid_percentage = (delivery_valid / total_rows) * 100
missing_percentage = (delivery_missing / total_rows) * 100

print(f"\nValid Percentage           : {valid_percentage:.2f}%")
print(f"Missing Percentage         : {missing_percentage:.2f}%")

# Check datetime dtypes
print("\n========== DATE DATA TYPES ==========")

print(f"Order Date dtype           : {df['Order Date'].dtype}")
print(f"Ship Date dtype            : {df['Ship Date'].dtype}")
print(f"Delivery_Days dtype        : {df['Delivery_Days'].dtype}")

# Check rows where dates are missing
print("\n========== SAMPLE ROWS WITH MISSING DELIVERY DAYS ==========")

missing_delivery = df[df["Delivery_Days"].isna()][
    ["Order ID", "Order Date", "Ship Date", "Ship Mode"]
]

print(missing_delivery.head(10).to_string(index=False))

# Final diagnostic
print("\n========== DIAGNOSTIC RESULT ==========")

if delivery_missing == 0:
    print("✓ All rows have valid Delivery_Days.")
else:
    print(f"⚠ {delivery_missing:,} rows have missing Delivery_Days.")
    print("⚠ Date parsing/calculation must be investigated before continuing.")

========== DATE COMPLETENESS CHECK ==========

Total Dataset Rows        : 10,194

========== ORIGINAL DATE COLUMNS ==========
Missing Order Date        : 6,064
Missing Ship Date         : 0

========== DELIVERY DAYS ==========
Valid Delivery_Days       : 4,130
Missing Delivery_Days     : 6,064

Valid Percentage           : 40.51%
Missing Percentage         : 59.49%

========== DATE DATA TYPES ==========
Order Date dtype           : datetime64[us]
Ship Date dtype            : datetime64[us]
Delivery_Days dtype        : float64

========== SAMPLE ROWS WITH MISSING DELIVERY DAYS ==========
                    Order ID Order Date  Ship Date      Ship Mode
US-2021-157147-CHO-MIL-31000        NaT 2026-07-11 Standard Class
US-2021-109232-CHO-NUT-13000        NaT 2026-07-09   Second Class
US-2021-157147-CHO-MIL-31000        NaT 2026-07-11 Standard Class
US-2021-118192-CHO-SCR-58000        NaT 2026-07-11 Standard Class
US-2021-162775-CHO-TRI-54000        NaT 2026-07-08   Second Class
US-2021-162775-OTH-KAZ-38000        NaT 2026-07-08   Second Class
US-2021-162775-CHO-MIL-31000        NaT 2026-07-08   Second Class
US-2021-118192-CHO-SCR-58000        NaT 2026-07-11 Standard Class
US-2021-162775-CHO-MIL-31000        NaT 2026-07-08   Second Class
US-2021-157147-CHO-NUT-13000        NaT 2026-07-11 Standard Class

========== DIAGNOSTIC RESULT ==========
⚠ 6,064 rows have missing Delivery_Days.
⚠ Date parsing/calculation must be investigated before continuing.

In [50]:
# ============================================================
# STEP 12D: CORRECT DATE PARSING & DELIVERY DAYS CALCULATION
# ============================================================

print("========== CORRECTING DATE PARSING ==========\n")

# Correct format in the original CSV is DD-MM-YYYY
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

# Calculate delivery / lead time
df["Delivery_Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

# ------------------------------------------------------------
# VALIDATION
# ------------------------------------------------------------

print("Total Rows              :", len(df))
print("Missing Order Date      :", df["Order Date"].isna().sum())
print("Missing Ship Date       :", df["Ship Date"].isna().sum())
print("Missing Delivery Days   :", df["Delivery_Days"].isna().sum())

print("\nDate Range:")
print("Order Date Minimum      :", df["Order Date"].min())
print("Order Date Maximum      :", df["Order Date"].max())
print("Ship Date Minimum       :", df["Ship Date"].min())
print("Ship Date Maximum       :", df["Ship Date"].max())

print("\nDelivery Days Statistics:")
print(df["Delivery_Days"].describe())

print("\n========== DATA QUALITY CHECK ==========")

negative_count = (df["Delivery_Days"] < 0).sum()
zero_count = (df["Delivery_Days"] == 0).sum()

print("Negative Delivery Days  :", negative_count)
print("Zero-Day Shipments      :", zero_count)

if (
    df["Order Date"].isna().sum() == 0
    and df["Ship Date"].isna().sum() == 0
    and df["Delivery_Days"].isna().sum() == 0
    and negative_count == 0
):
    print("\n✓ DATE PARSING SUCCESSFUL")
    print("✓ All 10,194 records have valid delivery days.")
    print("✓ No negative delivery times found.")
else:
    print("\n⚠ DATA QUALITY ISSUE STILL EXISTS")

========== CORRECTING DATE PARSING ==========

Total Rows              : 10194
Missing Order Date      : 6064
Missing Ship Date       : 0
Missing Delivery Days   : 6064

Date Range:
Order Date Minimum      : 2024-01-02 00:00:00
Order Date Maximum      : 2025-12-12 00:00:00
Ship Date Minimum       : 2026-06-30 00:00:00
Ship Date Maximum       : 2030-06-28 00:00:00

Delivery Days Statistics:
count    4130.000000
mean     1366.009685
std       302.829972
min       613.000000
25%      1155.000000
50%      1361.000000
75%      1598.000000
max      1965.000000
Name: Delivery_Days, dtype: float64

========== DATA QUALITY CHECK ==========
Negative Delivery Days  : 0
Zero-Day Shipments      : 0

⚠ DATA QUALITY ISSUE STILL EXISTS

In [51]:
# ============================================================
# STEP 12D-FINAL: RELOAD RAW DATES & CALCULATE LEAD TIME
# ============================================================

print("========== FINAL DATE CORRECTION ==========\n")

# IMPORTANT:
# Reload ONLY the original date columns from the raw CSV.
# This recovers the original date strings that were converted
# to NaT in the previous cells.

raw_dates = pd.read_csv(
    "../data/Nassau Candy Distributor.csv",
    usecols=["Order Date", "Ship Date"]
)

# Correct date format: DD-MM-YYYY
raw_dates["Order Date"] = pd.to_datetime(
    raw_dates["Order Date"],
    format="%d-%m-%Y",
    errors="raise"
)

raw_dates["Ship Date"] = pd.to_datetime(
    raw_dates["Ship Date"],
    format="%d-%m-%Y",
    errors="raise"
)

# Replace the damaged date columns in df
df["Order Date"] = raw_dates["Order Date"]
df["Ship Date"] = raw_dates["Ship Date"]

# Calculate Lead / Delivery Time
df["Delivery_Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

# ============================================================
# VALIDATION
# ============================================================

print("Total Rows              :", len(df))
print("Missing Order Date      :", df["Order Date"].isna().sum())
print("Missing Ship Date       :", df["Ship Date"].isna().sum())
print("Missing Delivery Days   :", df["Delivery_Days"].isna().sum())

print("\n========== DATE RANGE ==========")

print("Order Date Minimum      :", df["Order Date"].min())
print("Order Date Maximum      :", df["Order Date"].max())

print("Ship Date Minimum       :", df["Ship Date"].min())
print("Ship Date Maximum       :", df["Ship Date"].max())

print("\n========== DELIVERY DAYS ==========")

print(df["Delivery_Days"].describe())

negative_count = (df["Delivery_Days"] < 0).sum()
zero_count = (df["Delivery_Days"] == 0).sum()

print("\nNegative Delivery Days  :", negative_count)
print("Zero-Day Shipments      :", zero_count)

print("\n========== FINAL RESULT ==========")

if (
    len(df) == 10194
    and df["Order Date"].isna().sum() == 0
    and df["Ship Date"].isna().sum() == 0
    and df["Delivery_Days"].isna().sum() == 0
    and negative_count == 0
):
    print("✓ SUCCESS")
    print("✓ All 10,194 records have valid dates.")
    print("✓ All 10,194 records have valid Delivery_Days.")
    print("✓ No negative delivery times found.")
else:
    print("⚠ VALIDATION FAILED — DO NOT CONTINUE")

========== FINAL DATE CORRECTION ==========

Total Rows              : 10194
Missing Order Date      : 0
Missing Ship Date       : 0
Missing Delivery Days   : 0

========== DATE RANGE ==========
Order Date Minimum      : 2024-01-02 00:00:00
Order Date Maximum      : 2025-12-31 00:00:00
Ship Date Minimum       : 2026-06-30 00:00:00
Ship Date Maximum       : 2030-06-28 00:00:00

========== DELIVERY DAYS ==========
count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
Name: Delivery_Days, dtype: float64

Negative Delivery Days  : 0
Zero-Day Shipments      : 0

========== FINAL RESULT ==========
✓ SUCCESS
✓ All 10,194 records have valid dates.
✓ All 10,194 records have valid Delivery_Days.
✓ No negative delivery times found.

In [52]:
# ============================================================
# STEP 12E: LEAD TIME DISTRIBUTION & OPERATIONAL SEGMENTATION
# ============================================================

print("========== LEAD TIME DISTRIBUTION ANALYSIS ==========\n")

# Calculate data-driven thresholds
q1 = df["Delivery_Days"].quantile(0.25)
median = df["Delivery_Days"].quantile(0.50)
q3 = df["Delivery_Days"].quantile(0.75)

print("Lead Time Thresholds:")
print(f"Q1 / 25th Percentile  : {q1:.0f} days")
print(f"Median / 50th         : {median:.0f} days")
print(f"Q3 / 75th Percentile  : {q3:.0f} days")

# ------------------------------------------------------------
# Create operational lead-time segments
# ------------------------------------------------------------

def classify_lead_time(days):
    if days <= q1:
        return "Fast"
    elif days <= q3:
        return "Moderate"
    else:
        return "Slow"

df["Lead_Time_Category"] = df["Delivery_Days"].apply(
    classify_lead_time
)

# ------------------------------------------------------------
# Category counts
# ------------------------------------------------------------

category_counts = (
    df["Lead_Time_Category"]
    .value_counts()
    .reindex(["Fast", "Moderate", "Slow"])
)

category_percentage = (
    category_counts / len(df) * 100
)

print("\n========== LEAD TIME CATEGORIES ==========")

for category in ["Fast", "Moderate", "Slow"]:
    print(
        f"{category:<10} : "
        f"{category_counts[category]:,} orders "
        f"({category_percentage[category]:.2f}%)"
    )

# ------------------------------------------------------------
# Category performance
# ------------------------------------------------------------

category_analysis = (
    df.groupby("Lead_Time_Category", observed=True)
    .agg(
        Orders=("Order ID", "nunique"),
        Records=("Order ID", "size"),
        Average_Lead_Time=("Delivery_Days", "mean"),
        Median_Lead_Time=("Delivery_Days", "median"),
        Total_Sales=("Sales", "sum"),
        Total_Units=("Units", "sum"),
        Total_Gross_Profit=("Gross Profit", "sum")
    )
    .reindex(["Fast", "Moderate", "Slow"])
)

print("\n========== CATEGORY PERFORMANCE ==========")
print(category_analysis.to_string())

# ------------------------------------------------------------
# Final validation
# ------------------------------------------------------------

print("\n========== VALIDATION ==========")

print("Total records classified :", df["Lead_Time_Category"].notna().sum())
print("Unclassified records     :", df["Lead_Time_Category"].isna().sum())

if df["Lead_Time_Category"].isna().sum() == 0:
    print("✓ All records successfully classified.")
else:
    print("⚠ Some records were not classified.")

print("\n✓ STEP 12E COMPLETED")

========== LEAD TIME DISTRIBUTION ANALYSIS ==========

Lead Time Thresholds:
Q1 / 25th Percentile  : 1271 days
Median / 50th         : 1274 days
Q3 / 75th Percentile  : 1638 days

========== LEAD TIME CATEGORIES ==========
Fast       : 3,075 orders (30.16%)
Moderate   : 4,972 orders (48.77%)
Slow       : 2,147 orders (21.06%)

========== CATEGORY PERFORMANCE ==========
                    Orders  Records  Average_Lead_Time  Median_Lead_Time  Total_Sales  Total_Units  Total_Gross_Profit
Lead_Time_Category
Fast                  2581     3075        1028.707317             909.0     42660.08        11520            27958.95
Moderate              4150     4972        1363.719228            1274.0     69582.66        19040            45971.25
Slow                  1818     2147        1639.951095            1640.0     29540.89         8094            19512.60

========== VALIDATION ==========
Total records classified : 10194
Unclassified records     : 0
✓ All records successfully classified.

✓ STEP 12E COMPLETED

In [53]:
# ============================================================
# STEP 13: REGION & DIVISION LEAD-TIME ANALYSIS
# ============================================================

print("========== REGION & DIVISION LEAD-TIME ANALYSIS ==========\n")

# ------------------------------------------------------------
# 1. REGION ANALYSIS
# ------------------------------------------------------------

region_analysis = (
    df.groupby("Region", observed=True)
    .agg(
        Orders=("Order ID", "nunique"),
        Records=("Order ID", "size"),
        Average_Lead_Time=("Delivery_Days", "mean"),
        Median_Lead_Time=("Delivery_Days", "median"),
        Total_Sales=("Sales", "sum"),
        Total_Units=("Units", "sum"),
        Total_Gross_Profit=("Gross Profit", "sum")
    )
    .sort_values("Average_Lead_Time", ascending=False)
)

print("========== REGION PERFORMANCE ==========")
print(region_analysis.to_string())

# ------------------------------------------------------------
# 2. DIVISION ANALYSIS
# ------------------------------------------------------------

division_analysis = (
    df.groupby("Division", observed=True)
    .agg(
        Orders=("Order ID", "nunique"),
        Records=("Order ID", "size"),
        Average_Lead_Time=("Delivery_Days", "mean"),
        Median_Lead_Time=("Delivery_Days", "median"),
        Total_Sales=("Sales", "sum"),
        Total_Units=("Units", "sum"),
        Total_Gross_Profit=("Gross Profit", "sum")
    )
    .sort_values("Average_Lead_Time", ascending=False)
)

print("\n========== DIVISION PERFORMANCE ==========")
print(division_analysis.to_string())

# ------------------------------------------------------------
# 3. REGION × LEAD-TIME CATEGORY
# ------------------------------------------------------------

region_category = pd.crosstab(
    df["Region"],
    df["Lead_Time_Category"],
    normalize="index"
) * 100

region_category = region_category.reindex(
    columns=["Fast", "Moderate", "Slow"],
    fill_value=0
)

print("\n========== REGION × LEAD-TIME CATEGORY (%) ==========")
print(region_category.round(2).to_string())

# ------------------------------------------------------------
# 4. DIVISION × LEAD-TIME CATEGORY
# ------------------------------------------------------------

division_category = pd.crosstab(
    df["Division"],
    df["Lead_Time_Category"],
    normalize="index"
) * 100

division_category = division_category.reindex(
    columns=["Fast", "Moderate", "Slow"],
    fill_value=0
)

print("\n========== DIVISION × LEAD-TIME CATEGORY (%) ==========")
print(division_category.round(2).to_string())

# ------------------------------------------------------------
# 5. IDENTIFY BOTTLENECKS
# ------------------------------------------------------------

slowest_region = region_analysis["Average_Lead_Time"].idxmax()
fastest_region = region_analysis["Average_Lead_Time"].idxmin()

slowest_division = division_analysis["Average_Lead_Time"].idxmax()
fastest_division = division_analysis["Average_Lead_Time"].idxmin()

print("\n========== KEY FINDINGS ==========")

print(
    f"Slowest Region   : {slowest_region} "
    f"({region_analysis.loc[slowest_region, 'Average_Lead_Time']:.2f} days)"
)

print(
    f"Fastest Region   : {fastest_region} "
    f"({region_analysis.loc[fastest_region, 'Average_Lead_Time']:.2f} days)"
)

print(
    f"Slowest Division : {slowest_division} "
    f"({division_analysis.loc[slowest_division, 'Average_Lead_Time']:.2f} days)"
)

print(
    f"Fastest Division : {fastest_division} "
    f"({division_analysis.loc[fastest_division, 'Average_Lead_Time']:.2f} days)"
)

print("\n✓ STEP 13 COMPLETED")

========== REGION & DIVISION LEAD-TIME ANALYSIS ==========

========== REGION PERFORMANCE ==========
          Orders  Records  Average_Lead_Time  Median_Lead_Time  Total_Sales  Total_Units  Total_Gross_Profit
Region
Interior    1979     2335        1323.091221            1274.0     32037.60         8820            21282.49
Atlantic    2476     2986        1322.745144            1274.0     41197.24        11159            26973.70
Pacific     2744     3253        1322.194897            1274.0     46301.53        12466            30485.94
Gulf        1350     1620        1311.374691            1274.0     22247.26         6209            14700.67

========== DIVISION PERFORMANCE ==========
           Orders  Records  Average_Lead_Time  Median_Lead_Time  Total_Sales  Total_Units  Total_Gross_Profit
Division
Sugar          40       40        1355.650000            1274.5       427.48          137              284.73
Chocolate    8205     9844        1321.166904            1274.0    131692.90        37275            88824.62
Other         304      310        1306.029032            1273.0      9663.25         1242             4333.45

========== REGION × LEAD-TIME CATEGORY (%) ==========
Lead_Time_Category   Fast  Moderate   Slow
Region
Atlantic            30.21     48.89  20.90
Gulf                30.62     48.89  20.49
Interior            28.01     50.49  21.50
Pacific             31.45     47.37  21.18

========== DIVISION × LEAD-TIME CATEGORY (%) ==========
Lead_Time_Category   Fast  Moderate   Slow
Division
Chocolate           30.01     48.91  21.08
Other               36.13     43.87  20.00
Sugar               22.50     52.50  25.00

========== KEY FINDINGS ==========
Slowest Region   : Interior (1323.09 days)
Fastest Region   : Gulf (1311.37 days)
Slowest Division : Sugar (1355.65 days)
Fastest Division : Other (1306.03 days)

✓ STEP 13 COMPLETED

In [54]:
# ============================================================
# STEP 14: PRODUCT × LEAD TIME ANALYSIS
# ============================================================

print("========== PRODUCT × LEAD TIME ANALYSIS ==========\n")

# ------------------------------------------------------------
# PRODUCT PERFORMANCE
# ------------------------------------------------------------

product_leadtime = (
    df.groupby("Product Name", observed=True)
    .agg(
        Orders=("Order ID", "nunique"),
        Records=("Order ID", "size"),
        Average_Lead_Time=("Delivery_Days", "mean"),
        Median_Lead_Time=("Delivery_Days", "median"),
        Min_Lead_Time=("Delivery_Days", "min"),
        Max_Lead_Time=("Delivery_Days", "max"),
        Total_Sales=("Sales", "sum"),
        Total_Units=("Units", "sum"),
        Total_Gross_Profit=("Gross Profit", "sum")
    )
    .sort_values("Average_Lead_Time", ascending=False)
)

print("========== ALL PRODUCT LEAD-TIME PERFORMANCE ==========")
print(product_leadtime.to_string())

# ------------------------------------------------------------
# SLOWEST PRODUCTS
# ------------------------------------------------------------

print("\n========== TOP 5 SLOWEST PRODUCTS ==========")

slowest_products = product_leadtime.head(5)

print(
    slowest_products[
        [
            "Orders",
            "Average_Lead_Time",
            "Median_Lead_Time",
            "Total_Sales",
            "Total_Gross_Profit"
        ]
    ].to_string()
)

# ------------------------------------------------------------
# FASTEST PRODUCTS
# ------------------------------------------------------------

print("\n========== TOP 5 FASTEST PRODUCTS ==========")

fastest_products = product_leadtime.sort_values(
    "Average_Lead_Time",
    ascending=True
).head(5)

print(
    fastest_products[
        [
            "Orders",
            "Average_Lead_Time",
            "Median_Lead_Time",
            "Total_Sales",
            "Total_Gross_Profit"
        ]
    ].to_string()
)

# ------------------------------------------------------------
# PRODUCT × LEAD-TIME CATEGORY
# ------------------------------------------------------------

product_category = pd.crosstab(
    df["Product Name"],
    df["Lead_Time_Category"],
    normalize="index"
) * 100

product_category = product_category.reindex(
    columns=["Fast", "Moderate", "Slow"],
    fill_value=0
)

print("\n========== PRODUCT × LEAD-TIME CATEGORY (%) ==========")

print(product_category.round(2).to_string())

# ------------------------------------------------------------
# PRODUCT SLOW-SHIPMENT RATE
# ------------------------------------------------------------

product_slow_rate = (
    product_category["Slow"]
    .sort_values(ascending=False)
)

print("\n========== TOP 5 PRODUCTS BY SLOW-SHIPMENT RATE ==========")

print(
    product_slow_rate.head(5).round(2).to_string()
)

# ------------------------------------------------------------
# KEY FINDINGS
# ------------------------------------------------------------

slowest_product = product_leadtime["Average_Lead_Time"].idxmax()
fastest_product = product_leadtime["Average_Lead_Time"].idxmin()

print("\n========== KEY FINDINGS ==========")

print(
    f"Slowest Product : {slowest_product}"
)
print(
    f"Average Lead Time : "
    f"{product_leadtime.loc[slowest_product, 'Average_Lead_Time']:.2f} days"
)

print(
    f"\nFastest Product : {fastest_product}"
)
print(
    f"Average Lead Time : "
    f"{product_leadtime.loc[fastest_product, 'Average_Lead_Time']:.2f} days"
)

print("\n✓ STEP 14 COMPLETED")

========== PRODUCT × LEAD TIME ANALYSIS ==========

========== ALL PRODUCT LEAD-TIME PERFORMANCE ==========
                                   Orders  Records  Average_Lead_Time  Median_Lead_Time  Min_Lead_Time  Max_Lead_Time  Total_Sales  Total_Units  Total_Gross_Profit
Product Name
Hair Toffee                             4        4        1455.250000            1455.0           1272           1639        76.50           17               59.50
Everlasting Gobstopper                  3        3        1394.666667            1273.0           1270           1641       130.00           13              104.00
SweeTARTS                              10       10        1383.500000            1274.0            910           1641        61.50           41               28.70
Laffy Taffy                            10       10        1383.100000            1275.0            909           1642        53.73           27               33.48
Lickable Wallpaper                     92       94        1339.138298            1274.0            904           1641      7860.00          393             3930.00
Wonka Bar - Nutty Crunch Surprise    1529     1810        1328.915470            1274.0            904           1642     23574.95         6755            16819.95
Wonka Bar - Triple Dazzle Caramel    1677     2015        1325.661042            1274.0            904           1642     28485.00         7596            18610.20
Wonka Bar -Scrumdiddlyumptious       1704     2064        1320.641957            1274.0            904           1642     27874.80         7743            19357.50
Wonka Bar - Milk Chocolate           1768     2137        1316.764623            1274.0            904           1642     26867.75         8267            17443.37
Wonka Bar - Fudge Mallows            1527     1818        1314.242024            1274.0            904           1642     24890.40         6914            16593.60
Wonka Gum                             118      120        1306.525000            1273.5            904           1642       597.50          478              310.70
Nerds                                   4        4        1274.000000            1274.0            908           1640        15.00           10                7.00
Fizzy Lifting Drinks                    6        6        1273.500000            1274.0            907           1640        78.75           21               47.25
Kazookles                              94       96        1272.989583            1273.0            904           1641      1205.75          371               92.75
Fun Dip                                 3        3        1272.666667            1272.0           1271           1275        12.00            8                4.80

========== TOP 5 SLOWEST PRODUCTS ==========
                        Orders  Average_Lead_Time  Median_Lead_Time  Total_Sales  Total_Gross_Profit
Product Name
Hair Toffee                  4        1455.250000            1455.0        76.50               59.50
Everlasting Gobstopper       3        1394.666667            1273.0       130.00              104.00
SweeTARTS                   10        1383.500000            1274.0        61.50               28.70
Laffy Taffy                 10        1383.100000            1275.0        53.73               33.48
Lickable Wallpaper          92        1339.138298            1274.0      7860.00             3930.00

========== TOP 5 FASTEST PRODUCTS ==========
                      Orders  Average_Lead_Time  Median_Lead_Time  Total_Sales  Total_Gross_Profit
Product Name
Fun Dip                    3        1272.666667            1272.0        12.00                4.80
Kazookles                 94        1272.989583            1273.0      1205.75               92.75
Fizzy Lifting Drinks       6        1273.500000            1274.0        78.75               47.25
Nerds                      4        1274.000000            1274.0        15.00                7.00
Wonka Gum                118        1306.525000            1273.5       597.50              310.70

========== PRODUCT × LEAD-TIME CATEGORY (%) ==========
Lead_Time_Category                  Fast  Moderate   Slow
Product Name
Everlasting Gobstopper             33.33     33.33  33.33
Fizzy Lifting Drinks               33.33     50.00  16.67
Fun Dip                            33.33     66.67   0.00
Hair Toffee                         0.00     75.00  25.00
Kazookles                          37.50     46.88  15.62
Laffy Taffy                        20.00     60.00  20.00
Lickable Wallpaper                 34.04     42.55  23.40
Nerds                              50.00      0.00  50.00
SweeTARTS                          10.00     60.00  30.00
Wonka Bar - Fudge Mallows          32.01     47.25  20.74
Wonka Bar - Milk Chocolate         30.00     48.06  21.95
Wonka Bar - Nutty Crunch Surprise  29.17     49.56  21.27
Wonka Bar - Triple Dazzle Caramel  29.43     49.38  21.19
Wonka Bar -Scrumdiddlyumptious     29.55     50.24  20.20
Wonka Gum                          36.67     42.50  20.83

========== TOP 5 PRODUCTS BY SLOW-SHIPMENT RATE ==========
Product Name
Nerds                     50.00
Everlasting Gobstopper    33.33
SweeTARTS                 30.00
Hair Toffee               25.00
Lickable Wallpaper        23.40

========== KEY FINDINGS ==========
Slowest Product : Hair Toffee
Average Lead Time : 1455.25 days

Fastest Product : Fun Dip
Average Lead Time : 1272.67 days

✓ STEP 14 COMPLETED

In [55]:
# ============================================================
# STEP 15: PRODUCT × SHIPPING MODE LEAD-TIME ANALYSIS
# ============================================================

print("========== PRODUCT × SHIPPING MODE ANALYSIS ==========\n")

# ------------------------------------------------------------
# PRODUCT + SHIPPING MODE PERFORMANCE
# ------------------------------------------------------------

product_shipmode = (
    df.groupby(
        ["Product Name", "Ship Mode"],
        observed=True
    )
    .agg(
        Orders=("Order ID", "nunique"),
        Records=("Order ID", "size"),
        Average_Lead_Time=("Delivery_Days", "mean"),
        Median_Lead_Time=("Delivery_Days", "median"),
        Total_Sales=("Sales", "sum"),
        Total_Gross_Profit=("Gross Profit", "sum")
    )
    .reset_index()
)

print("========== PRODUCT × SHIPPING MODE ==========\n")
print(product_shipmode.to_string(index=False))

# ------------------------------------------------------------
# SHIPPING MODE OVERALL PERFORMANCE
# ------------------------------------------------------------

shipmode_summary = (
    df.groupby("Ship Mode", observed=True)
    .agg(
        Orders=("Order ID", "nunique"),
        Records=("Order ID", "size"),
        Average_Lead_Time=("Delivery_Days", "mean"),
        Median_Lead_Time=("Delivery_Days", "median"),
        Total_Sales=("Sales", "sum"),
        Total_Gross_Profit=("Gross Profit", "sum")
    )
    .sort_values("Average_Lead_Time")
)

print("\n========== OVERALL SHIPPING MODE PERFORMANCE ==========\n")
print(shipmode_summary.to_string())

# ------------------------------------------------------------
# PRODUCT × SHIPPING MODE PIVOT
# ------------------------------------------------------------

product_shipmode_pivot = df.pivot_table(
    index="Product Name",
    columns="Ship Mode",
    values="Delivery_Days",
    aggfunc="mean"
)

print("\n========== AVERAGE LEAD TIME BY PRODUCT & SHIPPING MODE ==========\n")
print(product_shipmode_pivot.round(2).to_string())

# ------------------------------------------------------------
# BEST AND WORST SHIPPING MODE FOR EACH PRODUCT
# ------------------------------------------------------------

print("\n========== BEST & WORST SHIPPING MODE BY PRODUCT ==========\n")

for product in product_shipmode_pivot.index:

    product_modes = product_shipmode_pivot.loc[product].dropna()

    if len(product_modes) > 0:

        best_mode = product_modes.idxmin()
        best_days = product_modes.min()

        worst_mode = product_modes.idxmax()
        worst_days = product_modes.max()

        print(f"\nProduct: {product}")
        print(
            f"  Best Mode  : {best_mode} "
            f"({best_days:.2f} days)"
        )
        print(
            f"  Worst Mode : {worst_mode} "
            f"({worst_days:.2f} days)"
        )

# ------------------------------------------------------------
# VALIDATION
# ------------------------------------------------------------

print("\n========== VALIDATION ==========")

print("Product × Shipping Mode combinations:",
      len(product_shipmode))

print("Shipping Modes:",
      df["Ship Mode"].nunique())

print("Products:",
      df["Product Name"].nunique())

print("\n✓ STEP 15 COMPLETED")

========== PRODUCT × SHIPPING MODE ANALYSIS ==========

========== PRODUCT × SHIPPING MODE ==========

                     Product Name      Ship Mode  Orders  Records  Average_Lead_Time  Median_Lead_Time  Total_Sales  Total_Gross_Profit
           Everlasting Gobstopper    First Class       1        1        1270.000000            1270.0        60.00               48.00
           Everlasting Gobstopper Standard Class       2        2        1457.000000            1457.0        70.00               56.00
             Fizzy Lifting Drinks    First Class       2        2        1272.000000            1272.0        22.50               13.50
             Fizzy Lifting Drinks Standard Class       4        4        1274.250000            1274.0        56.25               33.75
                          Fun Dip   Second Class       2        2        1271.500000            1271.5         6.00                2.40
                          Fun Dip Standard Class       1        1        1275.000000            1275.0         6.00                2.40
                      Hair Toffee    First Class       1        1        1272.000000            1272.0        22.50               17.50
                      Hair Toffee       Same Day       1        1        1635.000000            1635.0         9.00                7.00
                      Hair Toffee Standard Class       2        2        1457.000000            1457.0        45.00               35.00
                        Kazookles    First Class      16       16        1294.687500            1272.0       191.75               14.75
                        Kazookles       Same Day       6        6        1269.166667            1269.0        71.50                5.50
                        Kazookles   Second Class      21       21        1271.952381            1271.0       253.50               19.50
                        Kazookles Standard Class      51       53        1267.283019            1274.0       689.00               53.00
                      Laffy Taffy    First Class       2        2        1271.500000            1271.5         3.98                2.48
                      Laffy Taffy       Same Day       1        1        1635.000000            1635.0         7.96                4.96
                      Laffy Taffy Standard Class       7        7        1379.000000            1275.0        41.79               26.04
               Lickable Wallpaper    First Class      19       19        1367.736842            1272.0      1580.00              790.00
               Lickable Wallpaper       Same Day       4        4        1269.250000            1269.0       260.00              130.00
               Lickable Wallpaper   Second Class      19       19        1406.789474            1637.0      1760.00              880.00
               Lickable Wallpaper Standard Class      50       52        1309.346154            1274.5      4260.00             2130.00
                            Nerds Standard Class       4        4        1274.000000            1274.0        15.00                7.00
                        SweeTARTS   Second Class       3        3        1516.666667            1638.0        16.50                7.70
                        SweeTARTS Standard Class       7        7        1326.428571            1273.0        45.00               21.00
        Wonka Bar - Fudge Mallows    First Class     231      276        1336.355072            1272.0      3578.40             2385.60
        Wonka Bar - Fudge Mallows       Same Day      80       98        1317.734694            1269.0      1285.20              856.80
        Wonka Bar - Fudge Mallows   Second Class     296      346        1332.673410            1273.0      4827.60             3218.40
        Wonka Bar - Fudge Mallows Standard Class     920     1098        1302.563752            1274.0     15199.20            10132.80
       Wonka Bar - Milk Chocolate    First Class     261      313        1331.022364            1272.0      3526.25             2289.35
       Wonka Bar - Milk Chocolate       Same Day      90      108        1292.990741            1269.0      1319.50              856.66
       Wonka Bar - Milk Chocolate   Second Class     332      403        1329.781638            1273.0      5265.00             3418.20
       Wonka Bar - Milk Chocolate Standard Class    1085     1313        1311.325971            1274.0     16757.00            10879.16
Wonka Bar - Nutty Crunch Surprise    First Class     246      286        1330.167832            1272.0      3695.91             2636.91
Wonka Bar - Nutty Crunch Surprise       Same Day      77      103        1390.000000            1269.0      1235.46              881.46
Wonka Bar - Nutty Crunch Surprise   Second Class     299      355        1320.876056            1273.0      4599.82             3281.82
Wonka Bar - Nutty Crunch Surprise Standard Class     907     1066        1325.354597            1274.0     14043.76            10019.76
Wonka Bar - Triple Dazzle Caramel    First Class     238      277        1349.335740            1272.0      3922.50             2562.70
Wonka Bar - Triple Dazzle Caramel       Same Day      93      115        1345.600000            1269.0      1593.75             1041.25
Wonka Bar - Triple Dazzle Caramel   Second Class     321      387        1329.105943            1273.0      5666.25             3701.95
Wonka Bar - Triple Dazzle Caramel Standard Class    1025     1236        1317.421521            1274.0     17302.50            11304.30
   Wonka Bar -Scrumdiddlyumptious    First Class     268      328        1351.664634            1272.0      4575.60             3177.50
   Wonka Bar -Scrumdiddlyumptious       Same Day      83      104        1318.451923            1269.0      1288.80              895.00
   Wonka Bar -Scrumdiddlyumptious   Second Class     337      419        1303.906921            1273.0      5356.80             3720.00
   Wonka Bar -Scrumdiddlyumptious Standard Class    1016     1213        1318.221764            1274.0     16653.60            11565.00
                        Wonka Gum    First Class      27       27        1271.703704            1271.0       140.00               72.80
                        Wonka Gum       Same Day       7        7        1373.857143            1270.0        42.50               22.10
                        Wonka Gum   Second Class      23       24        1364.083333            1274.0       108.75               56.55
                        Wonka Gum Standard Class      61       62        1291.806452            1274.0       306.25              159.25

========== OVERALL SHIPPING MODE PERFORMANCE ==========

                Orders  Records  Average_Lead_Time  Median_Lead_Time  Total_Sales  Total_Gross_Profit
Ship Mode
Standard Class    5142     6120        1314.334641            1274.0     85490.35            56424.46
Second Class      1653     1979        1323.845376            1273.0     27860.22            18306.52
Same Day           442      547        1333.442413            1269.0      7113.67             4700.73
First Class       1312     1548        1338.275840            1272.0     21319.39            14011.09

========== AVERAGE LEAD TIME BY PRODUCT & SHIPPING MODE ==========

Ship Mode                          First Class  Same Day  Second Class  Standard Class
Product Name
Everlasting Gobstopper                 1270.00       NaN           NaN         1457.00
Fizzy Lifting Drinks                   1272.00       NaN           NaN         1274.25
Fun Dip                                    NaN       NaN       1271.50         1275.00
Hair Toffee                            1272.00   1635.00           NaN         1457.00
Kazookles                              1294.69   1269.17       1271.95         1267.28
Laffy Taffy                            1271.50   1635.00           NaN         1379.00
Lickable Wallpaper                     1367.74   1269.25       1406.79         1309.35
Nerds                                      NaN       NaN           NaN         1274.00
SweeTARTS                                  NaN       NaN       1516.67         1326.43
Wonka Bar - Fudge Mallows              1336.36   1317.73       1332.67         1302.56
Wonka Bar - Milk Chocolate             1331.02   1292.99       1329.78         1311.33
Wonka Bar - Nutty Crunch Surprise      1330.17   1390.00       1320.88         1325.35
Wonka Bar - Triple Dazzle Caramel      1349.34   1345.60       1329.11         1317.42
Wonka Bar -Scrumdiddlyumptious         1351.66   1318.45       1303.91         1318.22
Wonka Gum                              1271.70   1373.86       1364.08         1291.81

========== BEST & WORST SHIPPING MODE BY PRODUCT ==========


Product: Everlasting Gobstopper
  Best Mode  : First Class (1270.00 days)
  Worst Mode : Standard Class (1457.00 days)

Product: Fizzy Lifting Drinks
  Best Mode  : First Class (1272.00 days)
  Worst Mode : Standard Class (1274.25 days)

Product: Fun Dip
  Best Mode  : Second Class (1271.50 days)
  Worst Mode : Standard Class (1275.00 days)

Product: Hair Toffee
  Best Mode  : First Class (1272.00 days)
  Worst Mode : Same Day (1635.00 days)

Product: Kazookles
  Best Mode  : Standard Class (1267.28 days)
  Worst Mode : First Class (1294.69 days)

Product: Laffy Taffy
  Best Mode  : First Class (1271.50 days)
  Worst Mode : Same Day (1635.00 days)

Product: Lickable Wallpaper
  Best Mode  : Same Day (1269.25 days)
  Worst Mode : Second Class (1406.79 days)

Product: Nerds
  Best Mode  : Standard Class (1274.00 days)
  Worst Mode : Standard Class (1274.00 days)

Product: SweeTARTS
  Best Mode  : Standard Class (1326.43 days)
  Worst Mode : Second Class (1516.67 days)

Product: Wonka Bar - Fudge Mallows
  Best Mode  : Standard Class (1302.56 days)
  Worst Mode : First Class (1336.36 days)

Product: Wonka Bar - Milk Chocolate
  Best Mode  : Same Day (1292.99 days)
  Worst Mode : First Class (1331.02 days)

Product: Wonka Bar - Nutty Crunch Surprise
  Best Mode  : Second Class (1320.88 days)
  Worst Mode : Same Day (1390.00 days)

Product: Wonka Bar - Triple Dazzle Caramel
  Best Mode  : Standard Class (1317.42 days)
  Worst Mode : First Class (1349.34 days)

Product: Wonka Bar -Scrumdiddlyumptious
  Best Mode  : Second Class (1303.91 days)
  Worst Mode : First Class (1351.66 days)

Product: Wonka Gum
  Best Mode  : First Class (1271.70 days)
  Worst Mode : Same Day (1373.86 days)

========== VALIDATION ==========
Product × Shipping Mode combinations: 47
Shipping Modes: 4
Products: 15

✓ STEP 15 COMPLETED

In [57]:
# ============================================================
# STEP 16: PRODUCT OPERATIONAL PRIORITY / RISK MATRIX
# ROBUST VERSION - SAFE AFTER KERNEL RESTART
# ============================================================

import pandas as pd
from pathlib import Path

print("========== STEP 16: PRODUCT OPERATIONAL PRIORITY ==========\n")


# ------------------------------------------------------------
# 1. ENSURE DATAFRAME EXISTS
# ------------------------------------------------------------

if "df" not in globals():

    print("df not found in current kernel.")
    print("Loading Nassau Candy dataset...\n")

    data_folder = Path("../data")

    csv_files = list(data_folder.glob("*.csv"))

    if not csv_files:
        raise FileNotFoundError(
            "No CSV file found inside the data folder."
        )

    # Find Nassau Candy CSV
    nassau_files = [
        f for f in csv_files
        if "nassau" in f.name.lower()
    ]

    if not nassau_files:
        raise FileNotFoundError(
            "Nassau Candy CSV file was not found."
        )

    csv_path = nassau_files[0]

    df = pd.read_csv(csv_path)

    print(f"Dataset loaded: {csv_path.name}")
    print(f"Rows loaded: {len(df):,}")


else:

    print("Existing dataframe 'df' found.")
    print(f"Rows available: {len(df):,}")


# ------------------------------------------------------------
# 2. ENSURE DATE COLUMNS ARE CORRECT
# ------------------------------------------------------------

df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    dayfirst=True,
    errors="coerce"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    dayfirst=True,
    errors="coerce"
)


# ------------------------------------------------------------
# 3. ENSURE DELIVERY DAYS EXISTS
# ------------------------------------------------------------

df["Delivery_Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days


# ------------------------------------------------------------
# 4. VALIDATE DELIVERY DAYS
# ------------------------------------------------------------

missing_delivery = df["Delivery_Days"].isna().sum()
negative_delivery = (df["Delivery_Days"] < 0).sum()

print("\n========== DATA VALIDATION ==========")

print(f"Total Records       : {len(df):,}")
print(f"Missing Delivery    : {missing_delivery:,}")
print(f"Negative Delivery   : {negative_delivery:,}")


if missing_delivery > 0:
    raise ValueError(
        "Delivery_Days contains missing values. "
        "Fix date parsing before continuing."
    )

if negative_delivery > 0:
    raise ValueError(
        "Negative Delivery_Days detected. "
        "Fix date data before continuing."
    )


# ------------------------------------------------------------
# 5. ENSURE LEAD TIME CATEGORY EXISTS
# ------------------------------------------------------------

q1 = df["Delivery_Days"].quantile(0.25)
q3 = df["Delivery_Days"].quantile(0.75)

df["Lead_Time_Category"] = "Moderate"

df.loc[
    df["Delivery_Days"] <= q1,
    "Lead_Time_Category"
] = "Fast"

df.loc[
    df["Delivery_Days"] > q3,
    "Lead_Time_Category"
] = "Slow"


print("\n========== LEAD-TIME THRESHOLDS ==========")

print(f"Fast threshold     : <= {q1:.0f} days")
print(f"Slow threshold     : >  {q3:.0f} days")


# ------------------------------------------------------------
# 6. PRODUCT BASE ANALYSIS
# ------------------------------------------------------------

product_priority = (
    df.groupby("Product Name", observed=True)
    .agg(
        Orders=("Order ID", "nunique"),
        Records=("Order ID", "size"),
        Average_Lead_Time=("Delivery_Days", "mean"),
        Median_Lead_Time=("Delivery_Days", "median"),
        Total_Sales=("Sales", "sum"),
        Total_Gross_Profit=("Gross Profit", "sum")
    )
)


# ------------------------------------------------------------
# 7. SLOW SHIPMENT RATE
# ------------------------------------------------------------

slow_rate = (
    (df["Lead_Time_Category"] == "Slow")
    .astype(int)
    .groupby(df["Product Name"], observed=True)
    .mean()
    * 100
)

product_priority["Slow_Shipment_%"] = slow_rate


# ------------------------------------------------------------
# 8. GROSS PROFIT MARGIN
# ------------------------------------------------------------

product_priority["Gross_Margin_%"] = (
    product_priority["Total_Gross_Profit"]
    / product_priority["Total_Sales"]
    * 100
)


# ------------------------------------------------------------
# 9. DATA-DRIVEN SCORES
# ------------------------------------------------------------

product_priority["Lead_Time_Score"] = (
    product_priority["Average_Lead_Time"]
    .rank(pct=True)
    * 100
)

product_priority["Slow_Rate_Score"] = (
    product_priority["Slow_Shipment_%"]
    .rank(pct=True)
    * 100
)

product_priority["Sales_Score"] = (
    product_priority["Total_Sales"]
    .rank(pct=True)
    * 100
)

product_priority["Profit_Score"] = (
    product_priority["Total_Gross_Profit"]
    .rank(pct=True)
    * 100
)


# ------------------------------------------------------------
# 10. PRIORITY SCORE
# ------------------------------------------------------------

product_priority["Priority_Score"] = (
    product_priority["Lead_Time_Score"] * 0.40
    + product_priority["Slow_Rate_Score"] * 0.30
    + product_priority["Sales_Score"] * 0.20
    + product_priority["Profit_Score"] * 0.10
)


# ------------------------------------------------------------
# 11. PRIORITY CATEGORY
# ------------------------------------------------------------

def assign_priority(score):

    if score >= 75:
        return "High Priority"

    elif score >= 50:
        return "Medium Priority"

    else:
        return "Low Priority"


product_priority["Priority_Category"] = (
    product_priority["Priority_Score"]
    .apply(assign_priority)
)


# ------------------------------------------------------------
# 12. SORT RESULTS
# ------------------------------------------------------------

product_priority = product_priority.sort_values(
    "Priority_Score",
    ascending=False
)


# ------------------------------------------------------------
# 13. DISPLAY RESULTS
# ------------------------------------------------------------

display_columns = [
    "Orders",
    "Records",
    "Average_Lead_Time",
    "Median_Lead_Time",
    "Slow_Shipment_%",
    "Total_Sales",
    "Total_Gross_Profit",
    "Gross_Margin_%",
    "Priority_Score",
    "Priority_Category"
]

print("\n========== PRODUCT PRIORITY TABLE ==========\n")

print(
    product_priority[display_columns]
    .round(2)
    .to_string()
)


# ------------------------------------------------------------
# 14. TOP 5 PRIORITY PRODUCTS
# ------------------------------------------------------------

print("\n========== TOP 5 PRIORITY PRODUCTS ==========\n")

print(
    product_priority[
        [
            "Average_Lead_Time",
            "Slow_Shipment_%",
            "Total_Sales",
            "Total_Gross_Profit",
            "Priority_Score",
            "Priority_Category"
        ]
    ]
    .head(5)
    .round(2)
    .to_string()
)


# ------------------------------------------------------------
# 15. PRIORITY DISTRIBUTION
# ------------------------------------------------------------

print("\n========== PRIORITY DISTRIBUTION ==========\n")

print(
    product_priority["Priority_Category"]
    .value_counts()
    .to_string()
)


# ------------------------------------------------------------
# 16. VALIDATION
# ------------------------------------------------------------

print("\n========== FINAL VALIDATION ==========")

print(
    f"Products analyzed          : {len(product_priority)}"
)

print(
    f"Missing Priority Scores    : "
    f"{product_priority['Priority_Score'].isna().sum()}"
)

print(
    f"Missing Priority Categories: "
    f"{product_priority['Priority_Category'].isna().sum()}"
)

print(
    f"Total dataset records      : {len(df):,}"
)

print("\n✓ STEP 16 COMPLETED SUCCESSFULLY")

========== STEP 16: PRODUCT OPERATIONAL PRIORITY ==========

Existing dataframe 'df' found.
Rows available: 10,194

========== DATA VALIDATION ==========
Total Records       : 10,194
Missing Delivery    : 0
Negative Delivery   : 0

========== LEAD-TIME THRESHOLDS ==========
Fast threshold     : <= 1271 days
Slow threshold     : >  1638 days

========== PRODUCT PRIORITY TABLE ==========

                                   Orders  Records  Average_Lead_Time  Median_Lead_Time  Slow_Shipment_%  Total_Sales  Total_Gross_Profit  Gross_Margin_%  Priority_Score Priority_Category
Product Name
Everlasting Gobstopper                  3        3            1394.67            1273.0            33.33       130.00              104.00           80.00           80.00     High Priority
Hair Toffee                             4        4            1455.25            1455.0            25.00        76.50               59.50           77.78           74.67   Medium Priority
Lickable Wallpaper                     92       94            1339.14            1274.0            23.40      7860.00             3930.00           50.00           71.33   Medium Priority
Wonka Bar - Triple Dazzle Caramel    1677     2015            1325.66            1274.0            21.19     28485.00            18610.20           65.33           69.33   Medium Priority
SweeTARTS                              10       10            1383.50            1274.0            30.00        61.50               28.70           46.67           68.00   Medium Priority
Wonka Bar - Nutty Crunch Surprise    1529     1810            1328.92            1274.0            21.27     23574.95            16819.95           71.35           67.33   Medium Priority
Wonka Bar - Milk Chocolate           1768     2137            1316.76            1274.0            21.95     26867.75            17443.37           64.92           64.67   Medium Priority
Wonka Bar -Scrumdiddlyumptious       1704     2064            1320.64            1274.0            20.20     27874.80            19357.50           69.44           60.00   Medium Priority
Wonka Bar - Fudge Mallows            1527     1818            1314.24            1274.0            20.74     24890.40            16593.60           66.67           51.33   Medium Priority
Laffy Taffy                            10       10            1383.10            1275.0            20.00        53.73               33.48           62.31           46.67      Low Priority
Nerds                                   4        4            1274.00            1274.0            50.00        15.00                7.00           46.67           44.67      Low Priority
Wonka Gum                             118      120            1306.53            1273.5            20.83       597.50              310.70           52.00           44.00      Low Priority
Kazookles                              94       96            1272.99            1273.0            15.62      1205.75               92.75            7.69           26.00      Low Priority
Fizzy Lifting Drinks                    6        6            1273.50            1274.0            16.67        78.75               47.25           60.00           25.33      Low Priority
Fun Dip                                 3        3            1272.67            1272.0             0.00        12.00                4.80           40.00            6.67      Low Priority

========== TOP 5 PRIORITY PRODUCTS ==========

                                   Average_Lead_Time  Slow_Shipment_%  Total_Sales  Total_Gross_Profit  Priority_Score Priority_Category
Product Name
Everlasting Gobstopper                       1394.67            33.33        130.0               104.0           80.00     High Priority
Hair Toffee                                  1455.25            25.00         76.5                59.5           74.67   Medium Priority
Lickable Wallpaper                           1339.14            23.40       7860.0              3930.0           71.33   Medium Priority
Wonka Bar - Triple Dazzle Caramel            1325.66            21.19      28485.0             18610.2           69.33   Medium Priority
SweeTARTS                                    1383.50            30.00         61.5                28.7           68.00   Medium Priority

========== PRIORITY DISTRIBUTION ==========

Priority_Category
Medium Priority    8
Low Priority       6
High Priority      1

========== FINAL VALIDATION ==========
Products analyzed          : 15
Missing Priority Scores    : 0
Missing Priority Categories: 0
Total dataset records      : 10,194

✓ STEP 16 COMPLETED SUCCESSFULLY

In [64]:
# ============================================================
# STEP 17: VALIDATED PRODUCT → FACTORY MAPPING
# FINAL CORRECTED VERSION
# ============================================================

import pandas as pd
from pathlib import Path
import re
import unicodedata

print("=" * 70)
print("STEP 17: VALIDATED PRODUCT → FACTORY MAPPING")
print("=" * 70)


# ============================================================
# 1. LOAD DATASET SAFELY
# ============================================================

if "df" not in globals():

    print("\nDataframe 'df' not found. Loading CSV...")

    possible_paths = [
        Path("../data/Nassau Candy Distributor.csv"),
        Path("data/Nassau Candy Distributor.csv"),
        Path("Nassau Candy Distributor.csv")
    ]

    csv_path = next(
        (p for p in possible_paths if p.exists()),
        None
    )

    if csv_path is None:
        raise FileNotFoundError(
            "Nassau Candy Distributor.csv was not found."
        )

    df = pd.read_csv(csv_path)

    print(f"Dataset loaded from: {csv_path}")

else:

    print("\nExisting dataframe 'df' found.")


# ============================================================
# 2. BASIC VALIDATION
# ============================================================

required_columns = [
    "Product Name",
    "Order ID",
    "Sales",
    "Units",
    "Gross Profit"
]

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

if missing_columns:

    raise KeyError(
        f"Required columns missing from dataset: {missing_columns}"
    )


print(f"Dataset rows       : {len(df):,}")
print(f"Unique products    : {df['Product Name'].nunique()}")


# ============================================================
# 3. CANONICAL PRODUCT NAME FUNCTION
# ============================================================
# This handles formatting differences such as:
#
# Wonka Bar -Scrumdiddlyumptious
# Wonka Bar - Scrumdiddlyumptious
#
# Both become:
# Wonka Bar - Scrumdiddlyumptious
#
# IMPORTANT:
# Original Product Name column is NOT changed.
# Only the temporary matching key is normalized.
# ============================================================

def canonical_product_name(value):

    if pd.isna(value):
        return ""

    text = str(value)

    # Unicode normalization
    text = unicodedata.normalize("NFKC", text)

    # Convert non-breaking spaces to normal spaces
    text = text.replace("\u00A0", " ")

    # Remove leading/trailing whitespace
    text = text.strip()

    # Normalize spaces around hyphens
    text = re.sub(r"\s*-\s*", " - ", text)

    # Remove repeated spaces
    text = re.sub(r"\s+", " ", text)

    return text


# Create temporary matching key
df["_Product_Key"] = df["Product Name"].apply(
    canonical_product_name
)


# ============================================================
# 4. FACTORY MAPPING
# ============================================================

factory_mapping = {

    # --------------------------------------------------------
    # LOT'S O' NUTS
    # --------------------------------------------------------
    "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
    "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
    "Wonka Bar - Scrumdiddlyumptious": "Lot's O' Nuts",

    # --------------------------------------------------------
    # WICKED CHOCCY'S
    # --------------------------------------------------------
    "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
    "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",

    # --------------------------------------------------------
    # SUGAR SHACK
    # --------------------------------------------------------
    "Laffy Taffy": "Sugar Shack",
    "SweeTARTS": "Sugar Shack",
    "Nerds": "Sugar Shack",
    "Fun Dip": "Sugar Shack",
    "Fizzy Lifting Drinks": "Sugar Shack",

    # --------------------------------------------------------
    # SECRET FACTORY
    # --------------------------------------------------------
    "Everlasting Gobstopper": "Secret Factory",
    "Lickable Wallpaper": "Secret Factory",
    "Wonka Gum": "Secret Factory",

    # --------------------------------------------------------
    # THE OTHER FACTORY
    # --------------------------------------------------------
    "Hair Toffee": "The Other Factory",
    "Kazookles": "The Other Factory"
}


# ============================================================
# 5. NORMALIZE MAPPING KEYS
# ============================================================

normalized_mapping = {
    canonical_product_name(product): factory
    for product, factory in factory_mapping.items()
}


# ============================================================
# 6. VALIDATE MAPPING COUNT
# ============================================================

if len(factory_mapping) != 15:

    raise ValueError(
        f"ERROR: Expected 15 mappings, "
        f"but found {len(factory_mapping)}."
    )


if len(normalized_mapping) != 15:

    raise ValueError(
        "ERROR: Duplicate product names detected "
        "after normalization."
    )


print("\nMapping products  :", len(factory_mapping))
print("Mapping factories :", len(set(factory_mapping.values())))


# ============================================================
# 7. COMPARE DATASET PRODUCTS WITH MAPPING
# ============================================================

dataset_products = set(
    df["_Product_Key"].dropna().unique()
)

mapping_products = set(
    normalized_mapping.keys()
)


missing_products = dataset_products - mapping_products
extra_products = mapping_products - dataset_products


# ------------------------------------------------------------
# Missing products
# ------------------------------------------------------------

if missing_products:

    print("\n❌ PRODUCTS WITHOUT FACTORY MAPPING:")

    for product in sorted(missing_products):
        print("   -", product)

    raise ValueError(
        "Factory mapping validation failed because "
        "one or more dataset products are unmapped."
    )


# ------------------------------------------------------------
# Extra mapping products
# ------------------------------------------------------------

if extra_products:

    print("\n❌ EXTRA PRODUCTS IN FACTORY MAPPING:")

    for product in sorted(extra_products):
        print("   -", product)

    raise ValueError(
        "Factory mapping contains products that "
        "do not exist in the dataset."
    )


# ============================================================
# 8. ASSIGN FACTORY
# ============================================================

df["Factory"] = df["_Product_Key"].map(
    normalized_mapping
)


# ============================================================
# 9. CHECK UNMAPPED ROWS
# ============================================================

unmapped_rows = df["Factory"].isna().sum()


if unmapped_rows != 0:

    raise ValueError(
        f"ERROR: {unmapped_rows:,} rows have no factory."
    )


# ============================================================
# 10. REMOVE TEMPORARY COLUMN
# ============================================================

df.drop(
    columns=["_Product_Key"],
    inplace=True
)


# ============================================================
# 11. PRODUCT → FACTORY VALIDATION TABLE
# ============================================================

product_factory_check = (
    df[["Product Name", "Factory"]]
    .drop_duplicates()
    .sort_values(
        ["Factory", "Product Name"]
    )
    .reset_index(drop=True)
)


# ============================================================
# 12. VERIFY EACH PRODUCT HAS EXACTLY ONE FACTORY
# ============================================================

factory_count_per_product = (
    product_factory_check
    .groupby("Product Name")["Factory"]
    .nunique()
)


invalid_products = (
    factory_count_per_product[
        factory_count_per_product != 1
    ]
)


if len(invalid_products) != 0:

    print("\n❌ PRODUCTS WITH MULTIPLE FACTORIES:")

    print(invalid_products)

    raise ValueError(
        "A product is assigned to more than one factory."
    )


# ============================================================
# 13. DISPLAY PRODUCT → FACTORY MAPPING
# ============================================================

print("\n")
print("=" * 70)
print("PRODUCT → FACTORY MAPPING")
print("=" * 70)

print(
    product_factory_check.to_string(index=False)
)


# ============================================================
# 14. FACTORY PERFORMANCE SUMMARY
# ============================================================

factory_summary = (
    df.groupby("Factory")
      .agg(
          Products=("Product Name", "nunique"),
          Records=("Product Name", "size"),
          Orders=("Order ID", "nunique"),
          Sales=("Sales", "sum"),
          Units=("Units", "sum"),
          Gross_Profit=("Gross Profit", "sum")
      )
      .reset_index()
      .sort_values(
          "Sales",
          ascending=False
      )
)


print("\n")
print("=" * 70)
print("FACTORY SUMMARY")
print("=" * 70)

print(
    factory_summary.to_string(index=False)
)


# ============================================================
# 15. FINAL AUTOMATED VALIDATION
# ============================================================

assert df["Factory"].notna().all(), \
    "Validation failed: NULL factory values exist."

assert df["Product Name"].nunique() == 15, \
    "Validation failed: dataset should contain 15 products."

assert len(factory_mapping) == 15, \
    "Validation failed: mapping should contain 15 products."

assert df["Factory"].nunique() == 5, \
    "Validation failed: dataset should contain 5 factories."

assert len(product_factory_check) == 15, \
    "Validation failed: product-factory table should contain 15 products."

assert (factory_count_per_product == 1).all(), \
    "Validation failed: every product must have exactly one factory."


# ============================================================
# 16. SUCCESS
# ============================================================

print("\n")
print("=" * 70)
print("✅ STEP 17 COMPLETED SUCCESSFULLY")
print("=" * 70)

print("\nValidation Results:")
print(f"✔ Dataset rows              : {len(df):,}")
print(f"✔ Dataset products          : {df['Product Name'].nunique()}")
print(f"✔ Mapped products           : {len(factory_mapping)}")
print(f"✔ Factories                 : {df['Factory'].nunique()}")
print(f"✔ Unmapped rows             : {df['Factory'].isna().sum():,}")
print(f"✔ Products with >1 factory  : {len(invalid_products)}")

print("\n🎯 Factory mapping is VALIDATED.")

======================================================================
STEP 17: VALIDATED PRODUCT → FACTORY MAPPING
======================================================================

Existing dataframe 'df' found.
Dataset rows       : 10,194
Unique products    : 15

Mapping products  : 15
Mapping factories : 5


======================================================================
PRODUCT → FACTORY MAPPING
======================================================================
                     Product Name           Factory
        Wonka Bar - Fudge Mallows     Lot's O' Nuts
Wonka Bar - Nutty Crunch Surprise     Lot's O' Nuts
   Wonka Bar -Scrumdiddlyumptious     Lot's O' Nuts
           Everlasting Gobstopper    Secret Factory
               Lickable Wallpaper    Secret Factory
                        Wonka Gum    Secret Factory
             Fizzy Lifting Drinks       Sugar Shack
                          Fun Dip       Sugar Shack
                      Laffy Taffy       Sugar Shack
                            Nerds       Sugar Shack
                        SweeTARTS       Sugar Shack
                      Hair Toffee The Other Factory
                        Kazookles The Other Factory
       Wonka Bar - Milk Chocolate   Wicked Choccy's
Wonka Bar - Triple Dazzle Caramel   Wicked Choccy's


======================================================================
FACTORY SUMMARY
======================================================================
          Factory  Products  Records  Orders    Sales  Units  Gross_Profit
    Lot's O' Nuts         3     5692    4760 76340.15  21412      52771.05
  Wicked Choccy's         2     4152    3445 55352.75  15863      36053.57
   Secret Factory         3      217     213  8587.50    884       4344.70
The Other Factory         2      100      98  1282.25    388        152.25
      Sugar Shack         5       33      33   220.98    107        121.23


======================================================================
✅ STEP 17 COMPLETED SUCCESSFULLY
======================================================================

Validation Results:
✔ Dataset rows              : 10,194
✔ Dataset products          : 15
✔ Mapped products           : 15
✔ Factories                 : 5
✔ Unmapped rows             : 0
✔ Products with >1 factory  : 0

🎯 Factory mapping is VALIDATED.

In [65]:
# ============================================================
# STEP 18: FACTORY PERFORMANCE BASELINE ANALYSIS
# ============================================================

import pandas as pd
from pathlib import Path

print("=" * 70)
print("STEP 18: FACTORY PERFORMANCE BASELINE ANALYSIS")
print("=" * 70)


# ============================================================
# 1. ENSURE DATAFRAME EXISTS
# ============================================================

if "df" not in globals():

    print("\nDataframe 'df' not found. Loading dataset...")

    possible_paths = [
        Path("../data/Nassau Candy Distributor.csv"),
        Path("data/Nassau Candy Distributor.csv"),
        Path("Nassau Candy Distributor.csv")
    ]

    csv_path = next(
        (p for p in possible_paths if p.exists()),
        None
    )

    if csv_path is None:
        raise FileNotFoundError(
            "Nassau Candy Distributor.csv was not found."
        )

    df = pd.read_csv(csv_path)

    print(f"Dataset loaded from: {csv_path}")


else:

    print("\nExisting dataframe 'df' found.")


# ============================================================
# 2. REQUIRED COLUMNS CHECK
# ============================================================

required_columns = [
    "Factory",
    "Product Name",
    "Order ID",
    "Sales",
    "Units",
    "Gross Profit"
]

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

if missing_columns:

    raise KeyError(
        f"Required columns are missing: {missing_columns}"
    )


# ============================================================
# 3. ENSURE DELIVERY_DAYS EXISTS
# ============================================================

if "Delivery_Days" not in df.columns:

    if "Order Date" not in df.columns or "Ship Date" not in df.columns:

        raise KeyError(
            "Delivery_Days is missing and Order Date/Ship Date "
            "are not available."
        )

    # Handle both datetime and raw string columns safely
    if not pd.api.types.is_datetime64_any_dtype(df["Order Date"]):

        df["Order Date"] = pd.to_datetime(
            df["Order Date"],
            format="%d-%m-%Y",
            errors="raise"
        )

    if not pd.api.types.is_datetime64_any_dtype(df["Ship Date"]):

        df["Ship Date"] = pd.to_datetime(
            df["Ship Date"],
            format="%d-%m-%Y",
            errors="raise"
        )

    df["Delivery_Days"] = (
        df["Ship Date"] - df["Order Date"]
    ).dt.days


# ============================================================
# 4. VALIDATE DELIVERY DAYS
# ============================================================

if df["Delivery_Days"].isna().any():

    raise ValueError(
        "Delivery_Days contains missing values."
    )

if (df["Delivery_Days"] < 0).any():

    raise ValueError(
        "Negative Delivery_Days detected."
    )


# ============================================================
# 5. VALIDATE FACTORY ASSIGNMENT
# ============================================================

if df["Factory"].isna().any():

    raise ValueError(
        "Factory column contains unmapped rows."
    )

factory_count = df["Factory"].nunique()

if factory_count != 5:

    raise ValueError(
        f"Expected 5 factories, but found {factory_count}."
    )


print(f"\nRows                  : {len(df):,}")
print(f"Factories             : {df['Factory'].nunique()}")
print(f"Unmapped factory rows : {df['Factory'].isna().sum():,}")


# ============================================================
# 6. FACTORY PERFORMANCE SUMMARY
# ============================================================

factory_performance = (
    df.groupby("Factory")
      .agg(
          Products=("Product Name", "nunique"),
          Records=("Product Name", "size"),
          Orders=("Order ID", "nunique"),
          Sales=("Sales", "sum"),
          Units=("Units", "sum"),
          Gross_Profit=("Gross Profit", "sum"),
          Avg_Lead_Time=("Delivery_Days", "mean"),
          Median_Lead_Time=("Delivery_Days", "median")
      )
      .reset_index()
)


# ============================================================
# 7. CALCULATE PROFIT MARGIN
# ============================================================

factory_performance["Gross_Profit_Margin_%"] = (
    factory_performance["Gross_Profit"]
    / factory_performance["Sales"]
    * 100
)


# ============================================================
# 8. CALCULATE SLOW-SHIPMENT RATE
# ============================================================
# Slow threshold is based on the previously established
# dataset-level Q3 lead-time threshold.

q3_lead_time = df["Delivery_Days"].quantile(0.75)

factory_performance["Slow_Shipment_%"] = (
    df.assign(
        Slow_Shipment=df["Delivery_Days"] > q3_lead_time
    )
    .groupby("Factory")["Slow_Shipment"]
    .mean()
    .reindex(factory_performance["Factory"])
    .values
    * 100
)


# ============================================================
# 9. ROUND NUMERIC VALUES FOR DISPLAY
# ============================================================

display_table = factory_performance.copy()

display_table["Sales"] = display_table["Sales"].round(2)
display_table["Gross_Profit"] = display_table["Gross_Profit"].round(2)
display_table["Avg_Lead_Time"] = display_table["Avg_Lead_Time"].round(2)
display_table["Median_Lead_Time"] = display_table["Median_Lead_Time"].round(2)
display_table["Gross_Profit_Margin_%"] = (
    display_table["Gross_Profit_Margin_%"].round(2)
)
display_table["Slow_Shipment_%"] = (
    display_table["Slow_Shipment_%"].round(2)
)


# ============================================================
# 10. RANK FACTORIES
# ============================================================

display_table["Sales_Rank"] = (
    display_table["Sales"]
    .rank(method="min", ascending=False)
    .astype(int)
)

display_table["Profit_Rank"] = (
    display_table["Gross_Profit"]
    .rank(method="min", ascending=False)
    .astype(int)
)

display_table["Lead_Time_Rank"] = (
    display_table["Avg_Lead_Time"]
    .rank(method="min", ascending=True)
    .astype(int)
)


# ============================================================
# 11. SORT BY SALES
# ============================================================

display_table = (
    display_table
    .sort_values("Sales", ascending=False)
    .reset_index(drop=True)
)


# ============================================================
# 12. DISPLAY FACTORY PERFORMANCE
# ============================================================

print("\n")
print("=" * 70)
print("FACTORY PERFORMANCE SUMMARY")
print("=" * 70)

print(
    display_table.to_string(index=False)
)


# ============================================================
# 13. IDENTIFY BEST / WORST FACTORIES
# ============================================================

best_sales_factory = (
    factory_performance.loc[
        factory_performance["Sales"].idxmax(),
        "Factory"
    ]
)

best_profit_factory = (
    factory_performance.loc[
        factory_performance["Gross_Profit"].idxmax(),
        "Factory"
    ]
)

fastest_factory = (
    factory_performance.loc[
        factory_performance["Avg_Lead_Time"].idxmin(),
        "Factory"
    ]
)

slowest_factory = (
    factory_performance.loc[
        factory_performance["Avg_Lead_Time"].idxmax(),
        "Factory"
    ]
)

highest_margin_factory = (
    factory_performance.loc[
        factory_performance["Gross_Profit_Margin_%"].idxmax(),
        "Factory"
    ]
)


# ============================================================
# 14. KEY FINDINGS
# ============================================================

print("\n")
print("=" * 70)
print("KEY FACTORY FINDINGS")
print("=" * 70)

print(f"Highest Sales Factory       : {best_sales_factory}")
print(f"Highest Gross Profit Factory: {best_profit_factory}")
print(f"Fastest Factory             : {fastest_factory}")
print(f"Slowest Factory             : {slowest_factory}")
print(f"Highest Margin Factory      : {highest_margin_factory}")


# ============================================================
# 15. AUTOMATED VALIDATION
# ============================================================

assert len(factory_performance) == 5

assert factory_performance["Sales"].notna().all()

assert factory_performance["Gross_Profit"].notna().all()

assert factory_performance["Gross_Profit_Margin_%"].notna().all()

assert factory_performance["Avg_Lead_Time"].notna().all()

assert factory_performance["Slow_Shipment_%"].notna().all()

assert (factory_performance["Gross_Profit_Margin_%"] >= 0).all()

assert (factory_performance["Gross_Profit_Margin_%"] <= 100).all()

assert (factory_performance["Slow_Shipment_%"] >= 0).all()

assert (factory_performance["Slow_Shipment_%"] <= 100).all()


# ============================================================
# 16. SUCCESS
# ============================================================

print("\n")
print("=" * 70)
print("✅ STEP 18 COMPLETED SUCCESSFULLY")
print("=" * 70)

print(
    "\nFactory baseline performance has been calculated "
    "and validated for all 5 factories."
)

======================================================================
STEP 18: FACTORY PERFORMANCE BASELINE ANALYSIS
======================================================================

Existing dataframe 'df' found.

Rows                  : 10,194
Factories             : 5
Unmapped factory rows : 0


======================================================================
FACTORY PERFORMANCE SUMMARY
======================================================================
          Factory  Products  Records  Orders    Sales  Units  Gross_Profit  Avg_Lead_Time  Median_Lead_Time  Gross_Profit_Margin_%  Slow_Shipment_%  Sales_Rank  Profit_Rank  Lead_Time_Rank
    Lot's O' Nuts         3     5692    4760 76340.15  21412      52771.05        1321.23            1274.0                  69.13            20.71           1            1               3
  Wicked Choccy's         2     4152    3445 55352.75  15863      36053.57        1321.08            1274.0                  65.13            21.58           2            2               2
   Secret Factory         3      217     213  8587.50    884       4344.70        1321.87            1274.0                  50.59            22.12           3            3               4
The Other Factory         2      100      98  1282.25    388        152.25        1280.28            1273.0                  11.87            16.00           4            4               1
      Sugar Shack         5       33      33   220.98    107        121.23        1340.03            1274.0                  54.86            24.24           5            5               5


======================================================================
KEY FACTORY FINDINGS
======================================================================
Highest Sales Factory       : Lot's O' Nuts
Highest Gross Profit Factory: Lot's O' Nuts
Fastest Factory             : The Other Factory
Slowest Factory             : Sugar Shack
Highest Margin Factory      : Lot's O' Nuts


======================================================================
✅ STEP 18 COMPLETED SUCCESSFULLY
======================================================================

Factory baseline performance has been calculated and validated for all 5 factories.

In [66]:
# ============================================================
# STEP 19: PRODUCT × FACTORY OPERATIONAL ANALYSIS
# ============================================================

import pandas as pd
from pathlib import Path

print("=" * 75)
print("STEP 19: PRODUCT × FACTORY OPERATIONAL ANALYSIS")
print("=" * 75)


# ============================================================
# 1. ENSURE DATAFRAME EXISTS
# ============================================================

if "df" not in globals():

    print("\nDataframe 'df' not found. Loading dataset...")

    possible_paths = [
        Path("../data/Nassau Candy Distributor.csv"),
        Path("data/Nassau Candy Distributor.csv"),
        Path("Nassau Candy Distributor.csv")
    ]

    csv_path = next(
        (p for p in possible_paths if p.exists()),
        None
    )

    if csv_path is None:
        raise FileNotFoundError(
            "Nassau Candy Distributor.csv was not found."
        )

    df = pd.read_csv(csv_path)

    # Correct raw CSV date format
    if "Order Date" in df.columns:
        df["Order Date"] = pd.to_datetime(
            df["Order Date"],
            format="%d-%m-%Y",
            errors="raise"
        )

    if "Ship Date" in df.columns:
        df["Ship Date"] = pd.to_datetime(
            df["Ship Date"],
            format="%d-%m-%Y",
            errors="raise"
        )

    if "Delivery_Days" not in df.columns:
        df["Delivery_Days"] = (
            df["Ship Date"] - df["Order Date"]
        ).dt.days

    print(f"Dataset loaded from: {csv_path}")

else:

    print("\nExisting dataframe 'df' found.")


# ============================================================
# 2. REQUIRED COLUMNS
# ============================================================

required_columns = [
    "Product Name",
    "Factory",
    "Order ID",
    "Sales",
    "Units",
    "Gross Profit",
    "Delivery_Days"
]

missing_columns = [
    column
    for column in required_columns
    if column not in df.columns
]

if missing_columns:

    raise KeyError(
        f"Required columns missing: {missing_columns}"
    )


# ============================================================
# 3. DATA VALIDATION
# ============================================================

if df["Factory"].isna().any():

    raise ValueError(
        "Factory contains unmapped rows."
    )


if df["Product Name"].isna().any():

    raise ValueError(
        "Product Name contains missing values."
    )


if df["Delivery_Days"].isna().any():

    raise ValueError(
        "Delivery_Days contains missing values."
    )


if (df["Delivery_Days"] < 0).any():

    raise ValueError(
        "Negative Delivery_Days detected."
    )


# ============================================================
# 4. DATASET-LEVEL LEAD TIME THRESHOLD
# ============================================================

q3_lead_time = df["Delivery_Days"].quantile(0.75)

print(f"\nDataset Q3 Lead Time : {q3_lead_time:.2f} days")


# ============================================================
# 5. CREATE SLOW SHIPMENT FLAG
# ============================================================

analysis_df = df.copy()

analysis_df["_Slow_Shipment"] = (
    analysis_df["Delivery_Days"] > q3_lead_time
)


# ============================================================
# 6. PRODUCT × FACTORY SUMMARY
# ============================================================

product_factory_analysis = (
    analysis_df
    .groupby(
        ["Product Name", "Factory"],
        as_index=False
    )
    .agg(
        Orders=("Order ID", "nunique"),
        Records=("Product Name", "size"),
        Sales=("Sales", "sum"),
        Units=("Units", "sum"),
        Gross_Profit=("Gross Profit", "sum"),
        Avg_Lead_Time=("Delivery_Days", "mean"),
        Median_Lead_Time=("Delivery_Days", "median"),
        Slow_Shipment_Rate=("_Slow_Shipment", "mean")
    )
)


# ============================================================
# 7. CALCULATE GROSS PROFIT MARGIN
# ============================================================

product_factory_analysis["Gross_Profit_Margin_%"] = (
    product_factory_analysis["Gross_Profit"]
    / product_factory_analysis["Sales"]
    * 100
)


# Convert slow shipment rate to percentage
product_factory_analysis["Slow_Shipment_%"] = (
    product_factory_analysis["Slow_Shipment_Rate"] * 100
)


product_factory_analysis.drop(
    columns=["Slow_Shipment_Rate"],
    inplace=True
)


# ============================================================
# 8. ROUND VALUES
# ============================================================

numeric_columns = [
    "Sales",
    "Gross_Profit",
    "Avg_Lead_Time",
    "Median_Lead_Time",
    "Gross_Profit_Margin_%",
    "Slow_Shipment_%"
]

for column in numeric_columns:

    product_factory_analysis[column] = (
        product_factory_analysis[column].round(2)
    )


# ============================================================
# 9. OPERATIONAL PRIORITY SCORE
# ============================================================
# This is NOT an ML prediction.
# It is only a baseline screening indicator.
#
# Higher priority is assigned to products with:
# - longer lead time
# - higher slow-shipment rate
# - meaningful sales volume
#
# The score is intentionally transparent and will NOT be used
# as the final reallocation recommendation.
# ============================================================

lead_min = product_factory_analysis["Avg_Lead_Time"].min()
lead_max = product_factory_analysis["Avg_Lead_Time"].max()

slow_min = product_factory_analysis["Slow_Shipment_%"].min()
slow_max = product_factory_analysis["Slow_Shipment_%"].max()

sales_min = product_factory_analysis["Sales"].min()
sales_max = product_factory_analysis["Sales"].max()


def min_max_scale(series, minimum, maximum):

    if maximum == minimum:
        return pd.Series(
            0.0,
            index=series.index
        )

    return (
        (series - minimum)
        / (maximum - minimum)
    )


lead_score = min_max_scale(
    product_factory_analysis["Avg_Lead_Time"],
    lead_min,
    lead_max
)

slow_score = min_max_scale(
    product_factory_analysis["Slow_Shipment_%"],
    slow_min,
    slow_max
)

sales_score = min_max_scale(
    product_factory_analysis["Sales"],
    sales_min,
    sales_max
)


product_factory_analysis["Operational_Priority_Score"] = (
    0.45 * lead_score
    + 0.35 * slow_score
    + 0.20 * sales_score
)


# ============================================================
# 10. PRIORITY CATEGORY
# ============================================================

product_factory_analysis["Operational_Priority"] = pd.cut(
    product_factory_analysis["Operational_Priority_Score"],
    bins=[
        -float("inf"),
        0.33,
        0.66,
        float("inf")
    ],
    labels=[
        "Low",
        "Medium",
        "High"
    ],
    include_lowest=True
)


product_factory_analysis[
    "Operational_Priority_Score"
] = (
    product_factory_analysis[
        "Operational_Priority_Score"
    ].round(3)
)


# ============================================================
# 11. SORT BY PRIORITY
# ============================================================

product_factory_analysis = (
    product_factory_analysis
    .sort_values(
        [
            "Operational_Priority_Score",
            "Sales"
        ],
        ascending=[False, False]
    )
    .reset_index(drop=True)
)


# ============================================================
# 12. DISPLAY COMPLETE ANALYSIS
# ============================================================

print("\n")
print("=" * 75)
print("PRODUCT × FACTORY OPERATIONAL ANALYSIS")
print("=" * 75)

print(
    product_factory_analysis.to_string(index=False)
)


# ============================================================
# 13. TOP OPERATIONAL PRIORITY PRODUCTS
# ============================================================

top_priority = (
    product_factory_analysis
    .head(10)
    .copy()
)


print("\n")
print("=" * 75)
print("TOP 10 OPERATIONAL PRIORITY PRODUCTS")
print("=" * 75)

print(
    top_priority[
        [
            "Product Name",
            "Factory",
            "Sales",
            "Avg_Lead_Time",
            "Slow_Shipment_%",
            "Gross_Profit_Margin_%",
            "Operational_Priority_Score",
            "Operational_Priority"
        ]
    ].to_string(index=False)
)


# ============================================================
# 14. FACTORY × PRODUCT COUNT
# ============================================================

factory_product_count = (
    product_factory_analysis
    .groupby("Factory")
    .agg(
        Products=("Product Name", "nunique"),
        Sales=("Sales", "sum"),
        Gross_Profit=("Gross_Profit", "sum"),
        Avg_Lead_Time=("Avg_Lead_Time", "mean")
    )
    .reset_index()
)


factory_product_count["Gross_Profit_Margin_%"] = (
    factory_product_count["Gross_Profit"]
    / factory_product_count["Sales"]
    * 100
)


factory_product_count["Avg_Lead_Time"] = (
    factory_product_count["Avg_Lead_Time"].round(2)
)

factory_product_count["Gross_Profit_Margin_%"] = (
    factory_product_count["Gross_Profit_Margin_%"].round(2)
)


print("\n")
print("=" * 75)
print("FACTORY PRODUCT PORTFOLIO")
print("=" * 75)

print(
    factory_product_count.to_string(index=False)
)


# ============================================================
# 15. AUTOMATED VALIDATION
# ============================================================

# Exactly 15 product-factory combinations should exist
assert len(product_factory_analysis) == 15, (
    "Validation failed: expected exactly 15 "
    "product-factory combinations."
)


# Every product should have exactly one current factory
product_factory_counts = (
    product_factory_analysis
    .groupby("Product Name")["Factory"]
    .nunique()
)

assert (
    product_factory_counts == 1
).all(), (
    "Validation failed: a product has "
    "more than one current factory."
)


# Exactly 5 factories
assert (
    product_factory_analysis["Factory"].nunique() == 5
), (
    "Validation failed: expected 5 factories."
)


# No missing values in important metrics
assert (
    product_factory_analysis[
        [
            "Sales",
            "Units",
            "Gross_Profit",
            "Avg_Lead_Time",
            "Gross_Profit_Margin_%",
            "Slow_Shipment_%",
            "Operational_Priority_Score"
        ]
    ]
    .notna()
    .all()
    .all()
), (
    "Validation failed: missing analytical values detected."
)


# Margin must be between 0 and 100
assert (
    product_factory_analysis[
        "Gross_Profit_Margin_%"
    ].between(0, 100).all()
), (
    "Validation failed: invalid gross profit margin."
)


# Slow shipment percentage must be between 0 and 100
assert (
    product_factory_analysis[
        "Slow_Shipment_%"
    ].between(0, 100).all()
), (
    "Validation failed: invalid slow shipment percentage."
)


# Priority score must be between 0 and 1
assert (
    product_factory_analysis[
        "Operational_Priority_Score"
    ].between(0, 1).all()
), (
    "Validation failed: operational priority score "
    "outside expected range."
)


# ============================================================
# 16. SUCCESS
# ============================================================

print("\n")
print("=" * 75)
print("✅ STEP 19 COMPLETED SUCCESSFULLY")
print("=" * 75)

print(
    "\nProduct × Factory operational baseline "
    "has been calculated and validated."
)

print(
    "\nImportant: Operational Priority is a screening metric "
    "only. It is NOT the final factory-reallocation decision."
)

===========================================================================
STEP 19: PRODUCT × FACTORY OPERATIONAL ANALYSIS
===========================================================================

Existing dataframe 'df' found.

Dataset Q3 Lead Time : 1638.00 days


===========================================================================
PRODUCT × FACTORY OPERATIONAL ANALYSIS
===========================================================================
                     Product Name           Factory  Orders  Records    Sales  Units  Gross_Profit  Avg_Lead_Time  Median_Lead_Time  Gross_Profit_Margin_%  Slow_Shipment_%  Operational_Priority_Score Operational_Priority
                      Hair Toffee The Other Factory       4        4    76.50     17         59.50        1455.25            1455.0                  77.78            25.00                       0.625               Medium
           Everlasting Gobstopper    Secret Factory       3        3   130.00     13        104.00        1394.67            1273.0                  80.00            33.33                       0.535               Medium
                        SweeTARTS       Sugar Shack      10       10    61.50     41         28.70        1383.50            1274.0                  46.67            30.00                       0.484               Medium
Wonka Bar - Triple Dazzle Caramel   Wicked Choccy's    1677     2015 28485.00   7596      18610.20        1325.66            1274.0                  65.33            21.19                       0.479               Medium
   Wonka Bar -Scrumdiddlyumptious     Lot's O' Nuts    1704     2064 27874.80   7743      19357.50        1320.64            1274.0                  69.44            20.20                       0.455               Medium
Wonka Bar - Nutty Crunch Surprise     Lot's O' Nuts    1529     1810 23574.95   6755      16819.95        1328.92            1274.0                  71.35            21.27                       0.453               Medium
       Wonka Bar - Milk Chocolate   Wicked Choccy's    1768     2137 26867.75   8267      17443.37        1316.76            1274.0                  64.92            21.95                       0.451               Medium
        Wonka Bar - Fudge Mallows     Lot's O' Nuts    1527     1818 24890.40   6914      16593.60        1314.24            1274.0                  66.67            20.74                       0.422               Medium
                      Laffy Taffy       Sugar Shack      10       10    53.73     27         33.48        1383.10            1275.0                  62.31            20.00                       0.412               Medium
               Lickable Wallpaper    Secret Factory      92       94  7860.00    393       3930.00        1339.14            1274.0                  50.00            23.40                       0.383               Medium
                            Nerds       Sugar Shack       4        4    15.00     10          7.00        1274.00            1274.0                  46.67            50.00                       0.353               Medium
                        Wonka Gum    Secret Factory     118      120   597.50    478        310.70        1306.53            1273.5                  52.00            20.83                       0.233                  Low
                        Kazookles The Other Factory      94       96  1205.75    371         92.75        1272.99            1273.0                   7.69            15.62                       0.119                  Low
             Fizzy Lifting Drinks       Sugar Shack       6        6    78.75     21         47.25        1273.50            1274.0                  60.00            16.67                       0.119                  Low
                          Fun Dip       Sugar Shack       3        3    12.00      8          4.80        1272.67            1272.0                  40.00             0.00                       0.000                  Low


===========================================================================
TOP 10 OPERATIONAL PRIORITY PRODUCTS
===========================================================================
                     Product Name           Factory    Sales  Avg_Lead_Time  Slow_Shipment_%  Gross_Profit_Margin_%  Operational_Priority_Score Operational_Priority
                      Hair Toffee The Other Factory    76.50        1455.25            25.00                  77.78                       0.625               Medium
           Everlasting Gobstopper    Secret Factory   130.00        1394.67            33.33                  80.00                       0.535               Medium
                        SweeTARTS       Sugar Shack    61.50        1383.50            30.00                  46.67                       0.484               Medium
Wonka Bar - Triple Dazzle Caramel   Wicked Choccy's 28485.00        1325.66            21.19                  65.33                       0.479               Medium
   Wonka Bar -Scrumdiddlyumptious     Lot's O' Nuts 27874.80        1320.64            20.20                  69.44                       0.455               Medium
Wonka Bar - Nutty Crunch Surprise     Lot's O' Nuts 23574.95        1328.92            21.27                  71.35                       0.453               Medium
       Wonka Bar - Milk Chocolate   Wicked Choccy's 26867.75        1316.76            21.95                  64.92                       0.451               Medium
        Wonka Bar - Fudge Mallows     Lot's O' Nuts 24890.40        1314.24            20.74                  66.67                       0.422               Medium
                      Laffy Taffy       Sugar Shack    53.73        1383.10            20.00                  62.31                       0.412               Medium
               Lickable Wallpaper    Secret Factory  7860.00        1339.14            23.40                  50.00                       0.383               Medium


===========================================================================
FACTORY PRODUCT PORTFOLIO
===========================================================================
          Factory  Products    Sales  Gross_Profit  Avg_Lead_Time  Gross_Profit_Margin_%
    Lot's O' Nuts         3 76340.15      52771.05        1321.27                  69.13
   Secret Factory         3  8587.50       4344.70        1346.78                  50.59
      Sugar Shack         5   220.98        121.23        1317.35                  54.86
The Other Factory         2  1282.25        152.25        1364.12                  11.87
  Wicked Choccy's         2 55352.75      36053.57        1321.21                  65.13


===========================================================================
✅ STEP 19 COMPLETED SUCCESSFULLY
===========================================================================

Product × Factory operational baseline has been calculated and validated.

Important: Operational Priority is a screening metric only. It is NOT the final factory-reallocation decision.

In [67]:
# ============================================================
# STEP 20A: FACTORY COORDINATE SOURCE AUDIT
# ============================================================

from pathlib import Path
import pandas as pd

print("=" * 75)
print("STEP 20A: FACTORY COORDINATE SOURCE AUDIT")
print("=" * 75)

# ------------------------------------------------------------
# 1. EXPECTED FACTORIES
# ------------------------------------------------------------

expected_factories = {
    "Lot's O' Nuts",
    "Wicked Choccy's",
    "Sugar Shack",
    "Secret Factory",
    "The Other Factory"
}

print("\nExpected factories:")
for factory in sorted(expected_factories):
    print(" -", factory)


# ------------------------------------------------------------
# 2. VERIFY CURRENT DATAFRAME
# ------------------------------------------------------------

if "df" not in globals():
    raise RuntimeError(
        "Dataframe 'df' is not available. "
        "Do not continue until the project dataframe is loaded."
    )

if "Factory" not in df.columns:
    raise KeyError(
        "Factory column is missing from df."
    )

actual_factories = set(
    df["Factory"]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
)

print("\nFactories currently present in df:")
for factory in sorted(actual_factories):
    print(" -", factory)


# ------------------------------------------------------------
# 3. FACTORY NAME VALIDATION
# ------------------------------------------------------------

missing_factories = expected_factories - actual_factories
extra_factories = actual_factories - expected_factories

print("\n========== FACTORY NAME VALIDATION ==========")

print("Expected factory count :", len(expected_factories))
print("Actual factory count   :", len(actual_factories))
print("Missing factories      :", missing_factories)
print("Unexpected factories   :", extra_factories)

if missing_factories:
    raise ValueError(
        f"Missing expected factories: {missing_factories}"
    )

if extra_factories:
    raise ValueError(
        f"Unexpected factory names found: {extra_factories}"
    )

print("✓ Factory names validated.")


# ------------------------------------------------------------
# 4. SEARCH PROJECT FOLDERS FOR LOCATION FILES
# ------------------------------------------------------------

project_root = Path(".")

candidate_files = []

for pattern in [
    "*.csv",
    "*.xlsx",
    "*.xls",
    "*.json"
]:
    candidate_files.extend(project_root.rglob(pattern))


location_keywords = [
    "factory",
    "location",
    "coordinate",
    "latitude",
    "longitude",
    "geo",
    "zip"
]

location_candidates = []

for file_path in candidate_files:

    file_name = file_path.name.lower()

    if any(keyword in file_name for keyword in location_keywords):
        location_candidates.append(file_path)


print("\n========== POSSIBLE LOCATION FILES ==========")

if location_candidates:

    for file_path in sorted(location_candidates):
        print(" -", file_path)

else:

    print("No obvious factory/location/coordinate file found.")


# ------------------------------------------------------------
# 5. FINAL STATUS
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("STEP 20A STATUS")
print("=" * 75)

if location_candidates:
    print("✓ Possible coordinate source file(s) found.")
    print("Next: inspect the candidate file before using coordinates.")
else:
    print("⚠ No coordinate source file found in the project folders.")
    print("STOP — Do NOT invent factory coordinates.")

print("\nSTEP 20A completed.")

===========================================================================
STEP 20A: FACTORY COORDINATE SOURCE AUDIT
===========================================================================

Expected factories:
 - Lot's O' Nuts
 - Secret Factory
 - Sugar Shack
 - The Other Factory
 - Wicked Choccy's

Factories currently present in df:
 - Lot's O' Nuts
 - Secret Factory
 - Sugar Shack
 - The Other Factory
 - Wicked Choccy's

========== FACTORY NAME VALIDATION ==========
Expected factory count : 5
Actual factory count   : 5
Missing factories      : set()
Unexpected factories   : set()
✓ Factory names validated.

========== POSSIBLE LOCATION FILES ==========
No obvious factory/location/coordinate file found.

===========================================================================
STEP 20A STATUS
===========================================================================
⚠ No coordinate source file found in the project folders.
STOP — Do NOT invent factory coordinates.

STEP 20A completed.

In [68]:
# ============================================================
# STEP 20B: FACTORY COORDINATE MASTER TABLE
# ============================================================

import pandas as pd

print("=" * 70)
print("STEP 20B: FACTORY COORDINATE MASTER TABLE")
print("=" * 70)

# ------------------------------------------------------------
# 1. Expected factory names
# ------------------------------------------------------------
expected_factories = [
    "Lot's O' Nuts",
    "Wicked Choccy's",
    "Sugar Shack",
    "Secret Factory",
    "The Other Factory"
]

# ------------------------------------------------------------
# 2. Create the master table structure
# ------------------------------------------------------------
factory_master = pd.DataFrame({
    "Factory": expected_factories,
    "Latitude": pd.Series([pd.NA] * len(expected_factories), dtype="Float64"),
    "Longitude": pd.Series([pd.NA] * len(expected_factories), dtype="Float64"),
    "Coordinate_Source": ["NOT_AVAILABLE"] * len(expected_factories)
})

# ------------------------------------------------------------
# 3. Validate factory names
# ------------------------------------------------------------
actual_factories = sorted(df["Factory"].dropna().unique().tolist())

expected_set = set(expected_factories)
actual_set = set(actual_factories)

missing_factories = expected_set - actual_set
unexpected_factories = actual_set - expected_set

print("\nFactory Master Table:")
print(factory_master.to_string(index=False))

print("\n" + "=" * 70)
print("VALIDATION")
print("=" * 70)

print(f"Expected factory count : {len(expected_factories)}")
print(f"Actual factory count   : {len(actual_factories)}")
print(f"Missing factories      : {missing_factories}")
print(f"Unexpected factories   : {unexpected_factories}")

# ------------------------------------------------------------
# 4. Structural validation
# ------------------------------------------------------------
assert len(factory_master) == 5, "ERROR: Factory master table must contain exactly 5 factories."

assert factory_master["Factory"].is_unique, \
    "ERROR: Factory names must be unique."

assert missing_factories == set(), \
    f"ERROR: Missing factories detected: {missing_factories}"

assert unexpected_factories == set(), \
    f"ERROR: Unexpected factories detected: {unexpected_factories}"

assert factory_master["Latitude"].isna().all(), \
    "ERROR: Latitude should remain empty until a verified source is available."

assert factory_master["Longitude"].isna().all(), \
    "ERROR: Longitude should remain empty until a verified source is available."

print("\n✓ Factory master structure validated.")
print("✓ No coordinates have been invented.")
print("✓ Coordinate fields intentionally remain empty.")
print("\nSTEP 20B completed.")

======================================================================
STEP 20B: FACTORY COORDINATE MASTER TABLE
======================================================================

Factory Master Table:
          Factory  Latitude  Longitude Coordinate_Source
    Lot's O' Nuts      <NA>       <NA>     NOT_AVAILABLE
  Wicked Choccy's      <NA>       <NA>     NOT_AVAILABLE
      Sugar Shack      <NA>       <NA>     NOT_AVAILABLE
   Secret Factory      <NA>       <NA>     NOT_AVAILABLE
The Other Factory      <NA>       <NA>     NOT_AVAILABLE

======================================================================
VALIDATION
======================================================================
Expected factory count : 5
Actual factory count   : 5
Missing factories      : set()
Unexpected factories   : set()

✓ Factory master structure validated.
✓ No coordinates have been invented.
✓ Coordinate fields intentionally remain empty.

STEP 20B completed.

In [69]:
# ============================================================
# STEP 20C: FACTORY COORDINATE VALIDATION
# ============================================================

import pandas as pd

print("=" * 70)
print("STEP 20C: FACTORY COORDINATE VALIDATION")
print("=" * 70)

# ------------------------------------------------------------
# 1. Required columns
# ------------------------------------------------------------
required_columns = [
    "Factory",
    "Latitude",
    "Longitude",
    "Coordinate_Source"
]

missing_columns = [
    col for col in required_columns
    if col not in factory_master.columns
]

print("\nRequired columns:")
print(required_columns)

print("\nMissing columns:")
print(missing_columns)

assert not missing_columns, (
    f"ERROR: Required columns are missing: {missing_columns}"
)

# ------------------------------------------------------------
# 2. Validate factory count
# ------------------------------------------------------------
print("\nFactory count:")
print(f"Expected : 5")
print(f"Actual   : {len(factory_master)}")

assert len(factory_master) == 5, (
    "ERROR: Factory master table must contain exactly 5 factories."
)

# ------------------------------------------------------------
# 3. Validate factory names
# ------------------------------------------------------------
expected_factories = {
    "Lot's O' Nuts",
    "Wicked Choccy's",
    "Sugar Shack",
    "Secret Factory",
    "The Other Factory"
}

actual_factories = set(factory_master["Factory"].tolist())

print("\nFactory name validation:")
print(f"Missing   : {expected_factories - actual_factories}")
print(f"Unexpected: {actual_factories - expected_factories}")

assert expected_factories == actual_factories, (
    "ERROR: Factory names do not match the validated factory list."
)

# ------------------------------------------------------------
# 4. Check latitude and longitude availability
# ------------------------------------------------------------
latitude_missing = factory_master["Latitude"].isna().sum()
longitude_missing = factory_master["Longitude"].isna().sum()

print("\nCoordinate availability:")
print(f"Factories missing Latitude  : {latitude_missing}")
print(f"Factories missing Longitude : {longitude_missing}")

# ------------------------------------------------------------
# 5. Check coordinate ranges ONLY if coordinates exist
# ------------------------------------------------------------
coordinates_available = (
    factory_master["Latitude"].notna().all()
    and factory_master["Longitude"].notna().all()
)

if coordinates_available:

    latitude_valid = factory_master["Latitude"].between(-90, 90).all()
    longitude_valid = factory_master["Longitude"].between(-180, 180).all()

    print("\nCoordinate range validation:")
    print(f"Latitude valid  : {latitude_valid}")
    print(f"Longitude valid : {longitude_valid}")

    assert latitude_valid, (
        "ERROR: Latitude contains values outside -90 to 90."
    )

    assert longitude_valid, (
        "ERROR: Longitude contains values outside -180 to 180."
    )

    print("\n✓ All factory coordinates are valid.")
    print("✓ Coordinate table is READY for distance calculation.")

else:

    print("\n" + "=" * 70)
    print("COORDINATE STATUS")
    print("=" * 70)

    print("⚠ Factory coordinates are not available yet.")
    print("⚠ No coordinates will be invented or assumed.")
    print("⚠ Distance calculation must NOT start yet.")
    print("⚠ A verified factory-coordinate source is required.")

print("\n" + "=" * 70)
print("STEP 20C completed.")
print("=" * 70)

======================================================================
STEP 20C: FACTORY COORDINATE VALIDATION
======================================================================

Required columns:
['Factory', 'Latitude', 'Longitude', 'Coordinate_Source']

Missing columns:
[]

Factory count:
Expected : 5
Actual   : 5

Factory name validation:
Missing   : set()
Unexpected: set()

Coordinate availability:
Factories missing Latitude  : 5
Factories missing Longitude : 5

======================================================================
COORDINATE STATUS
======================================================================
⚠ Factory coordinates are not available yet.
⚠ No coordinates will be invented or assumed.
⚠ Distance calculation must NOT start yet.
⚠ A verified factory-coordinate source is required.

======================================================================
STEP 20C completed.
======================================================================

In [70]:
# ============================================================
# STEP 20D: FACTORY MAPPING + MASTER VALIDATION
# ============================================================

import pandas as pd
import os

print("=" * 75)
print("STEP 20D: FACTORY MAPPING + MASTER VALIDATION")
print("=" * 75)

# ------------------------------------------------------------
# 1. Load dataframe safely
# ------------------------------------------------------------

if "df" not in globals():
    data_path = "../data/Nassau Candy Distributor.csv"

    if not os.path.exists(data_path):
        raise FileNotFoundError(
            f"Dataset not found at: {data_path}"
        )

    df = pd.read_csv(data_path)

    print("\n✓ DataFrame was not in memory.")
    print("✓ Dataset loaded successfully.")

else:
    print("\n✓ Existing DataFrame 'df' detected.")


# ------------------------------------------------------------
# 2. Required columns validation
# ------------------------------------------------------------

required_df_columns = [
    "Product Name",
    "Order ID",
    "Sales",
    "Units",
    "Gross Profit",
    "Cost"
]

missing_df_columns = [
    col for col in required_df_columns
    if col not in df.columns
]

print("\nRequired dataset columns:")
print(required_df_columns)

print("\nMissing dataset columns:")
print(missing_df_columns)

assert not missing_df_columns, (
    f"ERROR: Missing dataset columns: {missing_df_columns}"
)


# ------------------------------------------------------------
# 3. Validate factory_master exists
# ------------------------------------------------------------

if "factory_master" not in globals():
    raise NameError(
        "ERROR: 'factory_master' is not available. "
        "Please run STEP 20B before STEP 20D."
    )

print("\n✓ factory_master detected.")


# ------------------------------------------------------------
# 4. Validate Factory column
# ------------------------------------------------------------

assert "Factory" in df.columns, (
    "ERROR: 'Factory' column is missing from df."
)

assert "Factory" in factory_master.columns, (
    "ERROR: 'Factory' column is missing from factory_master."
)

print("✓ Factory columns detected in both tables.")


# ------------------------------------------------------------
# 5. Validate product → factory mapping
# ------------------------------------------------------------

product_factory_check = (
    df.groupby("Product Name")["Factory"]
      .nunique()
)

products_with_multiple_factories = (
    product_factory_check[
        product_factory_check > 1
    ]
)

print("\nProduct → Factory validation:")
print(
    f"Total unique products              : "
    f"{df['Product Name'].nunique()}"
)

print(
    f"Products assigned to multiple factories: "
    f"{len(products_with_multiple_factories)}"
)

assert len(products_with_multiple_factories) == 0, (
    "ERROR: One or more products are assigned "
    "to multiple factories."
)


# ------------------------------------------------------------
# 6. Validate no missing factory assignments
# ------------------------------------------------------------

missing_factory_rows = df["Factory"].isna().sum()

print(
    f"Rows with missing Factory assignment : "
    f"{missing_factory_rows}"
)

assert missing_factory_rows == 0, (
    "ERROR: Some dataset rows have no Factory assignment."
)


# ------------------------------------------------------------
# 7. Validate factory names against master
# ------------------------------------------------------------

dataset_factories = set(
    df["Factory"].dropna().unique()
)

master_factories = set(
    factory_master["Factory"].dropna().unique()
)

missing_in_master = dataset_factories - master_factories
missing_in_dataset = master_factories - dataset_factories

print("\nFactory master consistency:")
print(f"Factories in dataset : {len(dataset_factories)}")
print(f"Factories in master  : {len(master_factories)}")

print(f"Missing in master    : {missing_in_master}")
print(f"Missing in dataset   : {missing_in_dataset}")

assert missing_in_master == set(), (
    "ERROR: Dataset contains a factory not present "
    "in factory_master."
)

assert missing_in_dataset == set(), (
    "ERROR: factory_master contains a factory not "
    "present in dataset."
)


# ------------------------------------------------------------
# 8. Create a clean factory validation table
# ------------------------------------------------------------

factory_validation = (
    df.groupby("Factory")
      .agg(
          Products=("Product Name", "nunique"),
          Records=("Order ID", "size"),
          Orders=("Order ID", "nunique"),
          Sales=("Sales", "sum"),
          Units=("Units", "sum"),
          Gross_Profit=("Gross Profit", "sum"),
          Cost=("Cost", "sum")
      )
      .reset_index()
)

factory_validation["Profit_Margin_%"] = (
    factory_validation["Gross_Profit"]
    / factory_validation["Sales"]
    * 100
)

# Merge only validated factory master information.
# Coordinates remain unavailable and are NOT invented.

factory_validation = factory_validation.merge(
    factory_master[
        [
            "Factory",
            "Latitude",
            "Longitude",
            "Coordinate_Source"
        ]
    ],
    on="Factory",
    how="left",
    validate="one_to_one"
)


# ------------------------------------------------------------
# 9. Final validation
# ------------------------------------------------------------

assert len(factory_validation) == 5, (
    "ERROR: Factory validation table must contain exactly 5 factories."
)

assert factory_validation["Coordinate_Source"].notna().all(), (
    "ERROR: Coordinate_Source is missing for a factory."
)

assert factory_validation["Profit_Margin_%"].between(
    0, 100
).all(), (
    "ERROR: Profit margin contains invalid values."
)


# ------------------------------------------------------------
# 10. Display final validation table
# ------------------------------------------------------------

display_columns = [
    "Factory",
    "Products",
    "Records",
    "Orders",
    "Sales",
    "Units",
    "Gross_Profit",
    "Profit_Margin_%",
    "Latitude",
    "Longitude",
    "Coordinate_Source"
]

print("\n" + "=" * 75)
print("FACTORY VALIDATION TABLE")
print("=" * 75)

print(
    factory_validation[display_columns]
    .to_string(index=False)
)


# ------------------------------------------------------------
# 11. Final status
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("STEP 20D STATUS")
print("=" * 75)

print("✓ Product → Factory mapping is consistent.")
print("✓ Every product has exactly one factory.")
print("✓ No rows have missing factory assignment.")
print("✓ All 5 factories match factory_master.")
print("✓ Factory-level financial metrics validated.")
print("✓ Coordinate columns preserved as unavailable.")
print("✓ No coordinates were invented.")
print("✓ Distance calculation remains intentionally pending.")

print("\nSTEP 20D completed successfully.")
print("=" * 75)

===========================================================================
STEP 20D: FACTORY MAPPING + MASTER VALIDATION
===========================================================================

✓ Existing DataFrame 'df' detected.

Required dataset columns:
['Product Name', 'Order ID', 'Sales', 'Units', 'Gross Profit', 'Cost']

Missing dataset columns:
[]

✓ factory_master detected.
✓ Factory columns detected in both tables.

Product → Factory validation:
Total unique products              : 15
Products assigned to multiple factories: 0
Rows with missing Factory assignment : 0

Factory master consistency:
Factories in dataset : 5
Factories in master  : 5
Missing in master    : set()
Missing in dataset   : set()

===========================================================================
FACTORY VALIDATION TABLE
===========================================================================
          Factory  Products  Records  Orders    Sales  Units  Gross_Profit  Profit_Margin_%  Latitude  Longitude Coordinate_Source
    Lot's O' Nuts         3     5692    4760 76340.15  21412      52771.05        69.126207      <NA>       <NA>     NOT_AVAILABLE
   Secret Factory         3      217     213  8587.50    884       4344.70        50.593304      <NA>       <NA>     NOT_AVAILABLE
      Sugar Shack         5       33      33   220.98    107        121.23        54.860168      <NA>       <NA>     NOT_AVAILABLE
The Other Factory         2      100      98  1282.25    388        152.25        11.873660      <NA>       <NA>     NOT_AVAILABLE
  Wicked Choccy's         2     4152    3445 55352.75  15863      36053.57        65.134198      <NA>       <NA>     NOT_AVAILABLE

===========================================================================
STEP 20D STATUS
===========================================================================
✓ Product → Factory mapping is consistent.
✓ Every product has exactly one factory.
✓ No rows have missing factory assignment.
✓ All 5 factories match factory_master.
✓ Factory-level financial metrics validated.
✓ Coordinate columns preserved as unavailable.
✓ No coordinates were invented.
✓ Distance calculation remains intentionally pending.

STEP 20D completed successfully.
===========================================================================

In [71]:
# ============================================================
# STEP 21: CUSTOMER GEOGRAPHY ANALYSIS
# ============================================================

import pandas as pd
import os

print("=" * 75)
print("STEP 21: CUSTOMER GEOGRAPHY ANALYSIS")
print("=" * 75)


# ------------------------------------------------------------
# 1. Safely load dataframe
# ------------------------------------------------------------

if "df" not in globals():

    data_path = "../data/Nassau Candy Distributor.csv"

    if not os.path.exists(data_path):
        raise FileNotFoundError(
            f"Dataset not found at: {data_path}"
        )

    df = pd.read_csv(data_path)

    print("\n✓ DataFrame was not in memory.")
    print("✓ Dataset loaded successfully.")

else:

    print("\n✓ Existing DataFrame 'df' detected.")


# ------------------------------------------------------------
# 2. Required geography columns
# ------------------------------------------------------------

required_columns = [
    "Customer ID",
    "Country/Region",
    "City",
    "State/Province",
    "Postal Code",
    "Region",
    "Order ID",
    "Sales",
    "Units",
    "Gross Profit",
    "Cost"
]

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

print("\nRequired columns:")
print(required_columns)

print("\nMissing columns:")
print(missing_columns)

assert not missing_columns, (
    f"ERROR: Required columns are missing: {missing_columns}"
)


# ------------------------------------------------------------
# 3. Basic geography validation
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("GEOGRAPHY DATA VALIDATION")
print("=" * 75)

print(f"Total records              : {len(df):,}")
print(f"Unique customers           : {df['Customer ID'].nunique():,}")
print(f"Unique countries/regions   : {df['Country/Region'].nunique():,}")
print(f"Unique states/provinces    : {df['State/Province'].nunique():,}")
print(f"Unique cities              : {df['City'].nunique():,}")
print(f"Unique postal codes        : {df['Postal Code'].nunique():,}")
print(f"Unique sales regions       : {df['Region'].nunique():,}")


# ------------------------------------------------------------
# 4. Check missing geography values
# ------------------------------------------------------------

geography_columns = [
    "Customer ID",
    "Country/Region",
    "City",
    "State/Province",
    "Postal Code",
    "Region"
]

geography_missing = (
    df[geography_columns]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

print("\nMissing geography values:")
print(geography_missing.to_string())

assert df["Customer ID"].notna().all(), (
    "ERROR: Customer ID contains missing values."
)

assert df["State/Province"].notna().all(), (
    "ERROR: State/Province contains missing values."
)

assert df["Region"].notna().all(), (
    "ERROR: Region contains missing values."
)


# ------------------------------------------------------------
# 5. REGION-LEVEL ANALYSIS
# ------------------------------------------------------------

region_summary = (
    df.groupby("Region")
      .agg(
          Customers=("Customer ID", "nunique"),
          Orders=("Order ID", "nunique"),
          Records=("Order ID", "size"),
          Sales=("Sales", "sum"),
          Units=("Units", "sum"),
          Gross_Profit=("Gross Profit", "sum"),
          Cost=("Cost", "sum")
      )
      .reset_index()
)

region_summary["Profit_Margin_%"] = (
    region_summary["Gross_Profit"]
    / region_summary["Sales"]
    * 100
)

region_summary["Sales_Share_%"] = (
    region_summary["Sales"]
    / region_summary["Sales"].sum()
    * 100
)

region_summary = region_summary.sort_values(
    "Sales",
    ascending=False
).reset_index(drop=True)

print("\n" + "=" * 75)
print("REGION-LEVEL CUSTOMER & SALES ANALYSIS")
print("=" * 75)

print(
    region_summary.to_string(
        index=False,
        formatters={
            "Sales": "{:,.2f}".format,
            "Gross_Profit": "{:,.2f}".format,
            "Cost": "{:,.2f}".format,
            "Profit_Margin_%": "{:.2f}".format,
            "Sales_Share_%": "{:.2f}".format
        }
    )
)


# ------------------------------------------------------------
# 6. STATE/PROVINCE-LEVEL ANALYSIS
# ------------------------------------------------------------

state_summary = (
    df.groupby("State/Province")
      .agg(
          Customers=("Customer ID", "nunique"),
          Orders=("Order ID", "nunique"),
          Records=("Order ID", "size"),
          Sales=("Sales", "sum"),
          Units=("Units", "sum"),
          Gross_Profit=("Gross Profit", "sum"),
          Cost=("Cost", "sum")
      )
      .reset_index()
)

state_summary["Profit_Margin_%"] = (
    state_summary["Gross_Profit"]
    / state_summary["Sales"]
    * 100
)

state_summary["Sales_Share_%"] = (
    state_summary["Sales"]
    / state_summary["Sales"].sum()
    * 100
)

state_summary = state_summary.sort_values(
    "Sales",
    ascending=False
).reset_index(drop=True)

print("\n" + "=" * 75)
print("TOP 15 STATES / PROVINCES BY SALES")
print("=" * 75)

print(
    state_summary.head(15).to_string(
        index=False,
        formatters={
            "Sales": "{:,.2f}".format,
            "Gross_Profit": "{:,.2f}".format,
            "Cost": "{:,.2f}".format,
            "Profit_Margin_%": "{:.2f}".format,
            "Sales_Share_%": "{:.2f}".format
        }
    )
)


# ------------------------------------------------------------
# 7. CITY-LEVEL ANALYSIS
# ------------------------------------------------------------

city_summary = (
    df.groupby(
        ["State/Province", "City"],
        dropna=False
    )
    .agg(
        Customers=("Customer ID", "nunique"),
        Orders=("Order ID", "nunique"),
        Records=("Order ID", "size"),
        Sales=("Sales", "sum"),
        Units=("Units", "sum"),
        Gross_Profit=("Gross Profit", "sum")
    )
    .reset_index()
)

city_summary["Profit_Margin_%"] = (
    city_summary["Gross_Profit"]
    / city_summary["Sales"]
    * 100
)

city_summary = city_summary.sort_values(
    "Sales",
    ascending=False
).reset_index(drop=True)

print("\n" + "=" * 75)
print("TOP 15 CUSTOMER CITIES BY SALES")
print("=" * 75)

print(
    city_summary.head(15).to_string(
        index=False,
        formatters={
            "Sales": "{:,.2f}".format,
            "Gross_Profit": "{:,.2f}".format,
            "Profit_Margin_%": "{:.2f}".format
        }
    )
)


# ------------------------------------------------------------
# 8. COUNTRY / REGION ANALYSIS
# ------------------------------------------------------------

country_summary = (
    df.groupby("Country/Region")
      .agg(
          Customers=("Customer ID", "nunique"),
          Orders=("Order ID", "nunique"),
          Records=("Order ID", "size"),
          Sales=("Sales", "sum"),
          Units=("Units", "sum"),
          Gross_Profit=("Gross Profit", "sum")
      )
      .reset_index()
)

country_summary["Sales_Share_%"] = (
    country_summary["Sales"]
    / country_summary["Sales"].sum()
    * 100
)

country_summary = country_summary.sort_values(
    "Sales",
    ascending=False
).reset_index(drop=True)

print("\n" + "=" * 75)
print("COUNTRY / REGION ANALYSIS")
print("=" * 75)

print(
    country_summary.to_string(
        index=False,
        formatters={
            "Sales": "{:,.2f}".format,
            "Gross_Profit": "{:,.2f}".format,
            "Sales_Share_%": "{:.2f}".format
        }
    )
)


# ------------------------------------------------------------
# 9. Geography concentration metrics
# ------------------------------------------------------------

top_5_state_sales_share = (
    state_summary.head(5)["Sales"].sum()
    / state_summary["Sales"].sum()
    * 100
)

top_10_state_sales_share = (
    state_summary.head(10)["Sales"].sum()
    / state_summary["Sales"].sum()
    * 100
)

top_5_city_sales_share = (
    city_summary.head(5)["Sales"].sum()
    / city_summary["Sales"].sum()
    * 100
)

print("\n" + "=" * 75)
print("GEOGRAPHIC CONCENTRATION")
print("=" * 75)

print(
    f"Top 5 states/provinces sales share : "
    f"{top_5_state_sales_share:.2f}%"
)

print(
    f"Top 10 states/provinces sales share: "
    f"{top_10_state_sales_share:.2f}%"
)

print(
    f"Top 5 cities sales share           : "
    f"{top_5_city_sales_share:.2f}%"
)


# ------------------------------------------------------------
# 10. Final validation
# ------------------------------------------------------------

assert len(region_summary) == df["Region"].nunique(), (
    "ERROR: Region summary count mismatch."
)

assert len(state_summary) == df["State/Province"].nunique(), (
    "ERROR: State summary count mismatch."
)

assert len(city_summary) == (
    df[["State/Province", "City"]]
    .drop_duplicates()
    .shape[0]
), (
    "ERROR: City summary count mismatch."
)

assert abs(
    region_summary["Sales"].sum()
    - df["Sales"].sum()
) < 0.01, (
    "ERROR: Region sales do not reconcile with total dataset sales."
)

assert abs(
    state_summary["Sales"].sum()
    - df["Sales"].sum()
) < 0.01, (
    "ERROR: State sales do not reconcile with total dataset sales."
)


# ------------------------------------------------------------
# 11. Final status
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("STEP 21 STATUS")
print("=" * 75)

print("✓ Customer geography validated.")
print("✓ Region-level analysis completed.")
print("✓ State/Province-level analysis completed.")
print("✓ City-level analysis completed.")
print("✓ Country/Region analysis completed.")
print("✓ Sales totals reconcile with the source dataset.")
print("✓ Geographic concentration metrics calculated.")
print("✓ No factory coordinates were assumed.")
print("✓ Distance calculation remains pending verified coordinates.")

print("\nSTEP 21 completed successfully.")
print("=" * 75)

===========================================================================
STEP 21: CUSTOMER GEOGRAPHY ANALYSIS
===========================================================================

✓ Existing DataFrame 'df' detected.

Required columns:
['Customer ID', 'Country/Region', 'City', 'State/Province', 'Postal Code', 'Region', 'Order ID', 'Sales', 'Units', 'Gross Profit', 'Cost']

Missing columns:
[]

===========================================================================
GEOGRAPHY DATA VALIDATION
===========================================================================
Total records              : 10,194
Unique customers           : 5,044
Unique countries/regions   : 2
Unique states/provinces    : 59
Unique cities              : 542
Unique postal codes        : 654
Unique sales regions       : 4

Missing geography values:
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0

===========================================================================
REGION-LEVEL CUSTOMER & SALES ANALYSIS
===========================================================================
  Region  Customers  Orders  Records     Sales  Units Gross_Profit      Cost Profit_Margin_% Sales_Share_%
 Pacific       1614    2744     3253 46,301.53  12466    30,485.94 15,815.59           65.84         32.66
Atlantic       1435    2476     2986 41,197.24  11159    26,973.70 14,223.54           65.47         29.06
Interior       1176    1979     2335 32,037.60   8820    21,282.49 10,755.11           66.43         22.60
    Gulf        822    1350     1620 22,247.26   6209    14,700.67  7,546.59           66.08         15.69

===========================================================================
TOP 15 STATES / PROVINCES BY SALES
===========================================================================
State/Province  Customers  Orders  Records     Sales  Units Gross_Profit     Cost Profit_Margin_% Sales_Share_%
    California       1021    1686     2001 27,917.40   7667    18,479.42 9,437.98           66.19         19.69
      New York        562     942     1128 15,541.03   4224    10,222.44 5,318.59           65.78         10.96
         Texas        487     833      985 13,416.09   3724     8,909.53 4,506.56           66.41          9.46
  Pennsylvania        288     487      587  8,027.03   2153     5,225.47 2,801.56           65.10          5.66
    Washington        256     432      506  6,921.15   1883     4,566.64 2,354.51           65.98          4.88
      Illinois        276     433      492  6,898.96   1845     4,557.68 2,341.28           66.06          4.87
          Ohio        236     392      469  6,768.95   1759     4,413.03 2,355.92           65.20          4.77
       Florida        200     319      383  4,804.02   1379     3,207.11 1,596.91           66.76          3.39
       Arizona        108     190      224  3,587.55    862     2,290.11 1,297.44           63.83          2.53
North Carolina        136     216      249  3,450.86    983     2,331.16 1,119.70           67.55          2.43
      Michigan        117     209      255  3,331.00    946     2,236.21 1,094.79           67.13          2.35
      Virginia        115     185      224  3,177.84    893     2,080.84 1,097.00           65.48          2.24
       Georgia         91     151      184  2,692.84    705     1,751.32   941.52           65.04          1.90
      Colorado         79     140      182  2,544.91    693     1,694.63   850.28           66.59          1.79
     Tennessee         91     151      183  2,383.56    681     1,573.52   810.04           66.02          1.68

===========================================================================
TOP 15 CUSTOMER CITIES BY SALES
===========================================================================
State/Province          City  Customers  Orders  Records     Sales  Units Gross_Profit Profit_Margin_%
      New York New York City        450     761      915 12,514.90   3417     8,240.51           65.85
    California   Los Angeles        384     629      747 10,408.75   2879     6,898.61           66.28
  Pennsylvania  Philadelphia        265     450      537  7,415.52   1981     4,813.82           64.92
    California San Francisco        265     430      510  7,018.61   1935     4,650.77           66.26
    Washington       Seattle        212     362      428  5,893.39   1590     3,880.68           65.85
         Texas       Houston        188     323      377  5,429.41   1466     3,547.43           65.34
      Illinois       Chicago        171     276      314  4,263.92   1132     2,800.58           65.68
    California     San Diego         88     149      170  2,348.88    670     1,567.52           66.73
         Texas        Dallas         80     129      157  1,947.51    555     1,299.77           66.74
          Ohio      Columbus         55      98      120  1,845.30    464     1,203.86           65.24
      Michigan       Detroit         53      90      115  1,532.97    441     1,034.17           67.46
       Georgia      Columbus         40      60       68  1,120.55    258       688.37           61.43
         Texas   San Antonio         27      46       59    873.11    247       588.85           67.44
North Carolina     Charlotte         24      42       52    870.38    243       582.60           66.94
       Florida  Jacksonville         38      63       75    856.29    248       572.27           66.83

===========================================================================
COUNTRY / REGION ANALYSIS
===========================================================================
Country/Region  Customers  Orders  Records      Sales  Units Gross_Profit Sales_Share_%
 United States       5009    8389     9994 138,830.34  37873    91,508.23         97.92
        Canada         63     160      200   2,953.29    781     1,934.57          2.08

===========================================================================
GEOGRAPHIC CONCENTRATION
===========================================================================
Top 5 states/provinces sales share : 50.66%
Top 10 states/provinces sales share: 68.65%
Top 5 cities sales share           : 30.51%

===========================================================================
STEP 21 STATUS
===========================================================================
✓ Customer geography validated.
✓ Region-level analysis completed.
✓ State/Province-level analysis completed.
✓ City-level analysis completed.
✓ Country/Region analysis completed.
✓ Sales totals reconcile with the source dataset.
✓ Geographic concentration metrics calculated.
✓ No factory coordinates were assumed.
✓ Distance calculation remains pending verified coordinates.

STEP 21 completed successfully.
===========================================================================

In [72]:
# ============================================================
# STEP 22: FACTORY × CUSTOMER REGION OPERATIONAL ANALYSIS
# ============================================================

import pandas as pd
import numpy as np
import os
import re
import unicodedata

print("=" * 80)
print("STEP 22: FACTORY × CUSTOMER REGION OPERATIONAL ANALYSIS")
print("=" * 80)


# ------------------------------------------------------------
# 1. LOAD DATA SAFELY
# ------------------------------------------------------------

data_path = "../data/Nassau Candy Distributor.csv"

if not os.path.exists(data_path):
    raise FileNotFoundError(
        f"ERROR: Dataset not found at: {data_path}"
    )

df_step22 = pd.read_csv(data_path)

print("\n✓ Raw dataset loaded successfully.")
print(f"✓ Records loaded: {len(df_step22):,}")


# ------------------------------------------------------------
# 2. REQUIRED COLUMN VALIDATION
# ------------------------------------------------------------

required_columns = [
    "Order ID",
    "Order Date",
    "Ship Date",
    "Customer ID",
    "Region",
    "Product Name",
    "Sales",
    "Units",
    "Gross Profit",
    "Cost"
]

missing_columns = [
    col for col in required_columns
    if col not in df_step22.columns
]

print("\nRequired columns:")
print(required_columns)

print("\nMissing columns:")
print(missing_columns)

assert not missing_columns, (
    f"ERROR: Required columns are missing: {missing_columns}"
)

print("✓ Required columns validated.")


# ------------------------------------------------------------
# 3. PARSE DATES FROM RAW CSV
# ------------------------------------------------------------

df_step22["Order Date"] = pd.to_datetime(
    df_step22["Order Date"],
    format="%d-%m-%Y",
    errors="raise"
)

df_step22["Ship Date"] = pd.to_datetime(
    df_step22["Ship Date"],
    format="%d-%m-%Y",
    errors="raise"
)

df_step22["Delivery_Days"] = (
    df_step22["Ship Date"] - df_step22["Order Date"]
).dt.days

assert df_step22["Order Date"].notna().all()
assert df_step22["Ship Date"].notna().all()
assert df_step22["Delivery_Days"].notna().all()
assert (df_step22["Delivery_Days"] >= 0).all()

print("✓ Dates parsed successfully.")
print("✓ Delivery_Days calculated successfully.")
print("✓ No negative delivery days found.")


# ------------------------------------------------------------
# 4. PRODUCT NAME NORMALIZATION
# ------------------------------------------------------------

def canonical_product_name(value):
    if pd.isna(value):
        return ""

    text = str(value)

    text = unicodedata.normalize("NFKC", text)
    text = text.replace("\u00A0", " ")
    text = text.strip()

    # Normalize spaces around hyphen
    text = re.sub(r"\s*-\s*", " - ", text)

    # Normalize repeated spaces
    text = re.sub(r"\s+", " ", text)

    return text


df_step22["_Product_Key"] = (
    df_step22["Product Name"]
    .apply(canonical_product_name)
)


# ------------------------------------------------------------
# 5. VALIDATED PRODUCT → FACTORY MAPPING
# ------------------------------------------------------------

product_factory_mapping = {

    # Lot's O' Nuts
    "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
    "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
    "Wonka Bar - Scrumdiddlyumptious": "Lot's O' Nuts",

    # Wicked Choccy's
    "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
    "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",

    # Sugar Shack
    "Laffy Taffy": "Sugar Shack",
    "SweeTARTS": "Sugar Shack",
    "Nerds": "Sugar Shack",
    "Fun Dip": "Sugar Shack",
    "Fizzy Lifting Drinks": "Sugar Shack",

    # Secret Factory
    "Everlasting Gobstopper": "Secret Factory",
    "Lickable Wallpaper": "Secret Factory",
    "Wonka Gum": "Secret Factory",

    # The Other Factory
    "Hair Toffee": "The Other Factory",
    "Kazookles": "The Other Factory"
}


# Normalize mapping keys too
normalized_mapping = {
    canonical_product_name(product): factory
    for product, factory in product_factory_mapping.items()
}


df_step22["Factory"] = (
    df_step22["_Product_Key"]
    .map(normalized_mapping)
)


# ------------------------------------------------------------
# 6. FACTORY ASSIGNMENT VALIDATION
# ------------------------------------------------------------

missing_factory_rows = df_step22["Factory"].isna().sum()

print("\nFactory assignment validation:")
print(f"Unique products : {df_step22['Product Name'].nunique()}")
print(f"Unique factories: {df_step22['Factory'].nunique()}")
print(f"Missing factory rows: {missing_factory_rows}")

assert missing_factory_rows == 0, (
    "ERROR: Some products could not be mapped to a factory."
)

expected_factories = {
    "Lot's O' Nuts",
    "Wicked Choccy's",
    "Sugar Shack",
    "Secret Factory",
    "The Other Factory"
}

actual_factories = set(df_step22["Factory"].unique())

assert actual_factories == expected_factories, (
    f"ERROR: Factory set mismatch.\n"
    f"Expected: {expected_factories}\n"
    f"Actual: {actual_factories}"
)

assert df_step22["Product Name"].nunique() == 15
assert df_step22["Factory"].nunique() == 5

print("✓ All 15 products mapped.")
print("✓ Exactly 5 validated factories detected.")


# ------------------------------------------------------------
# 7. DATA-DRIVEN LEAD-TIME THRESHOLD
# ------------------------------------------------------------

lead_time_q3 = df_step22["Delivery_Days"].quantile(0.75)

df_step22["Slow_Shipment"] = (
    df_step22["Delivery_Days"] > lead_time_q3
)

print("\nLead-time threshold:")
print(f"Q3 lead time: {lead_time_q3:.0f} days")
print("✓ Slow shipment flag created.")


# ------------------------------------------------------------
# 8. FACTORY × REGION SUMMARY
# ------------------------------------------------------------

factory_region_summary = (
    df_step22
    .groupby(["Factory", "Region"])
    .agg(
        Customers=("Customer ID", "nunique"),
        Orders=("Order ID", "nunique"),
        Records=("Order ID", "size"),
        Sales=("Sales", "sum"),
        Units=("Units", "sum"),
        Gross_Profit=("Gross Profit", "sum"),
        Cost=("Cost", "sum"),
        Avg_Lead_Days=("Delivery_Days", "mean"),
        Median_Lead_Days=("Delivery_Days", "median"),
        Slow_Shipments=("Slow_Shipment", "sum")
    )
    .reset_index()
)


# ------------------------------------------------------------
# 9. CALCULATE BUSINESS KPIs
# ------------------------------------------------------------

factory_region_summary["Profit_Margin_%"] = np.where(
    factory_region_summary["Sales"] != 0,
    (
        factory_region_summary["Gross_Profit"]
        / factory_region_summary["Sales"]
        * 100
    ),
    0
)

factory_region_summary["Slow_Shipment_%"] = np.where(
    factory_region_summary["Records"] != 0,
    (
        factory_region_summary["Slow_Shipments"]
        / factory_region_summary["Records"]
        * 100
    ),
    0
)

factory_region_summary["Sales_Share_%"] = (
    factory_region_summary["Sales"]
    / df_step22["Sales"].sum()
    * 100
)


# ------------------------------------------------------------
# 10. SORT BY SALES
# ------------------------------------------------------------

factory_region_summary = (
    factory_region_summary
    .sort_values(
        ["Sales", "Orders"],
        ascending=[False, False]
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 11. DISPLAY FACTORY × REGION ANALYSIS
# ------------------------------------------------------------

display_columns = [
    "Factory",
    "Region",
    "Customers",
    "Orders",
    "Records",
    "Sales",
    "Units",
    "Gross_Profit",
    "Cost",
    "Profit_Margin_%",
    "Avg_Lead_Days",
    "Median_Lead_Days",
    "Slow_Shipment_%",
    "Sales_Share_%"
]

print("\n" + "=" * 80)
print("FACTORY × CUSTOMER REGION PERFORMANCE")
print("=" * 80)

print(
    factory_region_summary[display_columns].to_string(
        index=False,
        formatters={
            "Sales": "{:,.2f}".format,
            "Gross_Profit": "{:,.2f}".format,
            "Cost": "{:,.2f}".format,
            "Profit_Margin_%": "{:.2f}".format,
            "Avg_Lead_Days": "{:.2f}".format,
            "Median_Lead_Days": "{:.0f}".format,
            "Slow_Shipment_%": "{:.2f}".format,
            "Sales_Share_%": "{:.2f}".format
        }
    )
)


# ------------------------------------------------------------
# 12. WORST FACTORY-REGION LANES
# ------------------------------------------------------------

worst_lanes = (
    factory_region_summary
    .sort_values(
        ["Avg_Lead_Days", "Slow_Shipment_%"],
        ascending=[False, False]
    )
    .head(10)
    .reset_index(drop=True)
)

print("\n" + "=" * 80)
print("TOP 10 FACTORY × REGION LANES BY LEAD-TIME RISK")
print("=" * 80)

print(
    worst_lanes[
        [
            "Factory",
            "Region",
            "Orders",
            "Sales",
            "Avg_Lead_Days",
            "Median_Lead_Days",
            "Slow_Shipment_%",
            "Profit_Margin_%"
        ]
    ].to_string(
        index=False,
        formatters={
            "Sales": "{:,.2f}".format,
            "Avg_Lead_Days": "{:.2f}".format,
            "Median_Lead_Days": "{:.0f}".format,
            "Slow_Shipment_%": "{:.2f}".format,
            "Profit_Margin_%": "{:.2f}".format
        }
    )
)


# ------------------------------------------------------------
# 13. FACTORY PERFORMANCE ACROSS REGIONS
# ------------------------------------------------------------

factory_summary = (
    df_step22
    .groupby("Factory")
    .agg(
        Regions=("Region", "nunique"),
        Orders=("Order ID", "nunique"),
        Records=("Order ID", "size"),
        Sales=("Sales", "sum"),
        Units=("Units", "sum"),
        Gross_Profit=("Gross Profit", "sum"),
        Avg_Lead_Days=("Delivery_Days", "mean")
    )
    .reset_index()
)

factory_summary["Profit_Margin_%"] = (
    factory_summary["Gross_Profit"]
    / factory_summary["Sales"]
    * 100
)

factory_summary = factory_summary.sort_values(
    "Sales",
    ascending=False
).reset_index(drop=True)

print("\n" + "=" * 80)
print("FACTORY-LEVEL SUMMARY")
print("=" * 80)

print(
    factory_summary.to_string(
        index=False,
        formatters={
            "Sales": "{:,.2f}".format,
            "Gross_Profit": "{:,.2f}".format,
            "Avg_Lead_Days": "{:.2f}".format,
            "Profit_Margin_%": "{:.2f}".format
        }
    )
)


# ------------------------------------------------------------
# 14. RECONCILIATION CHECKS
# ------------------------------------------------------------

factory_region_sales = factory_region_summary["Sales"].sum()
dataset_sales = df_step22["Sales"].sum()

factory_region_orders = factory_region_summary["Orders"].sum()

print("\n" + "=" * 80)
print("STEP 22 VALIDATION")
print("=" * 80)

print(f"Dataset records              : {len(df_step22):,}")
print(f"Factory-region combinations  : {len(factory_region_summary):,}")
print(f"Dataset sales                : {dataset_sales:,.2f}")
print(f"Factory-region sales         : {factory_region_sales:,.2f}")
print(f"Unique dataset orders        : {df_step22['Order ID'].nunique():,}")
print(f"Factory-region order count   : {factory_region_orders:,}")


# Sales must reconcile exactly
assert abs(factory_region_sales - dataset_sales) < 0.01, (
    "ERROR: Factory-region sales do not reconcile with dataset sales."
)

# Factory count
assert df_step22["Factory"].nunique() == 5, (
    "ERROR: Expected exactly 5 factories."
)

# Region count
assert df_step22["Region"].nunique() == 4, (
    "ERROR: Expected exactly 4 regions."
)

# Product count
assert df_step22["Product Name"].nunique() == 15, (
    "ERROR: Expected exactly 15 products."
)

# No missing important values
assert factory_region_summary[
    ["Factory", "Region", "Sales", "Orders", "Avg_Lead_Days"]
].notna().all().all(), (
    "ERROR: Important KPI values contain missing values."
)

# Margin validity
assert factory_region_summary[
    "Profit_Margin_%"
].between(0, 100).all(), (
    "ERROR: Profit margin contains invalid values."
)

# Lead time validity
assert (
    factory_region_summary["Avg_Lead_Days"] >= 0
).all(), (
    "ERROR: Average lead time contains negative values."
)


# ------------------------------------------------------------
# 15. FINAL STATUS
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("STEP 22 STATUS")
print("=" * 80)

print("✓ Factory × Region analysis completed.")
print("✓ Factory assignments validated.")
print("✓ Customer regions validated.")
print("✓ Orders, sales and profit metrics calculated.")
print("✓ Average and median lead time calculated.")
print("✓ Slow-shipment rate calculated.")
print("✓ Factory-region sales reconcile with source dataset.")
print("✓ 5 factories validated.")
print("✓ 4 customer regions validated.")
print("✓ 15 products validated.")
print("✓ No factory coordinates were invented.")
print("✓ Distance calculation remains pending verified coordinates.")

print("\nSTEP 22 completed successfully.")
print("=" * 80)

================================================================================
STEP 22: FACTORY × CUSTOMER REGION OPERATIONAL ANALYSIS
================================================================================

✓ Raw dataset loaded successfully.
✓ Records loaded: 10,194

Required columns:
['Order ID', 'Order Date', 'Ship Date', 'Customer ID', 'Region', 'Product Name', 'Sales', 'Units', 'Gross Profit', 'Cost']

Missing columns:
[]
✓ Required columns validated.
✓ Dates parsed successfully.
✓ Delivery_Days calculated successfully.
✓ No negative delivery days found.

Factory assignment validation:
Unique products : 15
Unique factories: 5
Missing factory rows: 0
✓ All 15 products mapped.
✓ Exactly 5 validated factories detected.

Lead-time threshold:
Q3 lead time: 1638 days
✓ Slow shipment flag created.

================================================================================
FACTORY × CUSTOMER REGION PERFORMANCE
================================================================================
          Factory   Region  Customers  Orders  Records     Sales  Units Gross_Profit     Cost Profit_Margin_% Avg_Lead_Days Median_Lead_Days Slow_Shipment_% Sales_Share_%
    Lot's O' Nuts  Pacific       1143    1524     1813 24,294.04   6813    16,788.44 7,505.60           69.11       1317.53             1274           20.74         17.13
    Lot's O' Nuts Atlantic       1030    1378     1661 22,166.13   6214    15,315.63 6,850.50           69.09       1326.83             1274           20.65         15.63
  Wicked Choccy's  Pacific        947    1123     1342 18,525.75   5301    12,067.41 6,458.34           65.14       1329.10             1274           22.28         13.07
    Lot's O' Nuts Interior        852    1113     1321 17,856.86   5012    12,353.56 5,503.30           69.18       1324.20             1274           21.04         12.59
  Wicked Choccy's Atlantic        830     973     1197 15,414.50   4422    10,039.66 5,374.84           65.13       1315.97             1274           20.72         10.87
  Wicked Choccy's Interior        686     802      950 12,419.25   3561     8,088.99 4,330.26           65.13       1324.55             1274           22.53          8.76
    Lot's O' Nuts     Gulf        576     745      897 12,023.12   3373     8,313.42 3,709.70           69.15       1313.98             1274           20.29          8.48
  Wicked Choccy's     Gulf        467     547      663  8,993.25   2579     5,857.51 3,135.74           65.13       1309.11             1274           20.36          6.34
   Secret Factory  Pacific         61      63       63  3,076.25    229     1,558.05 1,518.20           50.65       1307.73             1274           15.87          2.17
   Secret Factory Atlantic         67      70       72  2,991.25    308     1,499.85 1,491.40           50.14       1349.25             1275           25.00          2.11
   Secret Factory Interior         44      45       45  1,590.00    186       806.80   783.20           50.74       1289.09             1273           17.78          1.12
   Secret Factory     Gulf         35      35       37    930.00    161       480.00   450.00           51.61       1332.54             1274           32.43          0.66
The Other Factory Atlantic         37      37       38    506.75    154        54.75   452.00           10.80       1282.74             1273           23.68          0.36
The Other Factory  Pacific         31      31       32    386.25    115        61.25   325.00           15.86       1307.22             1273           12.50          0.27
The Other Factory     Gulf         19      19       19    262.50     80        26.50   236.00           10.10       1272.63             1273           15.79          0.19
The Other Factory Interior         11      11       11    126.75     39         9.75   117.00            7.69       1206.64             1273            0.00          0.09
      Sugar Shack Atlantic         18      18       18    118.61     61        63.81    54.80           53.80       1375.39             1275           33.33          0.08
      Sugar Shack Interior          8       8        8     44.74     22        23.39    21.35           52.28       1318.62             1272           25.00          0.03
      Sugar Shack     Gulf          3       4        4     38.39     16        23.24    15.15           60.54       1091.25             1090            0.00          0.03
      Sugar Shack  Pacific          3       3        3     19.24      8        10.79     8.45           56.08       1516.67             1638            0.00          0.01

================================================================================
TOP 10 FACTORY × REGION LANES BY LEAD-TIME RISK
================================================================================
        Factory   Region  Orders     Sales Avg_Lead_Days Median_Lead_Days Slow_Shipment_% Profit_Margin_%
    Sugar Shack  Pacific       3     19.24       1516.67             1638            0.00           56.08
    Sugar Shack Atlantic      18    118.61       1375.39             1275           33.33           53.80
 Secret Factory Atlantic      70  2,991.25       1349.25             1275           25.00           50.14
 Secret Factory     Gulf      35    930.00       1332.54             1274           32.43           51.61
Wicked Choccy's  Pacific    1123 18,525.75       1329.10             1274           22.28           65.14
  Lot's O' Nuts Atlantic    1378 22,166.13       1326.83             1274           20.65           69.09
Wicked Choccy's Interior     802 12,419.25       1324.55             1274           22.53           65.13
  Lot's O' Nuts Interior    1113 17,856.86       1324.20             1274           21.04           69.18
    Sugar Shack Interior       8     44.74       1318.62             1272           25.00           52.28
  Lot's O' Nuts  Pacific    1524 24,294.04       1317.53             1274           20.74           69.11

================================================================================
FACTORY-LEVEL SUMMARY
================================================================================
          Factory  Regions  Orders  Records     Sales  Units Gross_Profit Avg_Lead_Days Profit_Margin_%
    Lot's O' Nuts        4    4760     5692 76,340.15  21412    52,771.05       1321.23           69.13
  Wicked Choccy's        4    3445     4152 55,352.75  15863    36,053.57       1321.08           65.13
   Secret Factory        4     213      217  8,587.50    884     4,344.70       1321.87           50.59
The Other Factory        4      98      100  1,282.25    388       152.25       1280.28           11.87
      Sugar Shack        4      33       33    220.98    107       121.23       1340.03           54.86

================================================================================
STEP 22 VALIDATION
================================================================================
Dataset records              : 10,194
Factory-region combinations  : 20
Dataset sales                : 141,783.63
Factory-region sales         : 141,783.63
Unique dataset orders        : 8,549
Factory-region order count   : 8,549

================================================================================
STEP 22 STATUS
================================================================================
✓ Factory × Region analysis completed.
✓ Factory assignments validated.
✓ Customer regions validated.
✓ Orders, sales and profit metrics calculated.
✓ Average and median lead time calculated.
✓ Slow-shipment rate calculated.
✓ Factory-region sales reconcile with source dataset.
✓ 5 factories validated.
✓ 4 customer regions validated.
✓ 15 products validated.
✓ No factory coordinates were invented.
✓ Distance calculation remains pending verified coordinates.

STEP 22 completed successfully.
================================================================================

In [73]:
# ============================================================
# STEP 23: SHIPPING MODE EFFICIENCY ANALYSIS
# ============================================================

import pandas as pd
import numpy as np
import os
import re
import unicodedata

print("=" * 80)
print("STEP 23: SHIPPING MODE EFFICIENCY ANALYSIS")
print("=" * 80)


# ------------------------------------------------------------
# 1. LOAD RAW DATA
# ------------------------------------------------------------

data_path = "../data/Nassau Candy Distributor.csv"

if not os.path.exists(data_path):
    raise FileNotFoundError(
        f"ERROR: Dataset not found at: {data_path}"
    )

df_step23 = pd.read_csv(data_path)

print("\n✓ Raw dataset loaded successfully.")
print(f"✓ Records loaded: {len(df_step23):,}")


# ------------------------------------------------------------
# 2. REQUIRED COLUMN VALIDATION
# ------------------------------------------------------------

required_columns = [
    "Order ID",
    "Order Date",
    "Ship Date",
    "Ship Mode",
    "Customer ID",
    "Region",
    "Product Name",
    "Sales",
    "Units",
    "Gross Profit",
    "Cost"
]

missing_columns = [
    col for col in required_columns
    if col not in df_step23.columns
]

print("\nRequired columns:")
print(required_columns)

print("\nMissing columns:")
print(missing_columns)

assert not missing_columns, (
    f"ERROR: Required columns are missing: {missing_columns}"
)

print("✓ Required columns validated.")


# ------------------------------------------------------------
# 3. BASIC DATA VALIDATION
# ------------------------------------------------------------

assert len(df_step23) == 10194, (
    f"ERROR: Expected 10,194 records, found {len(df_step23):,}."
)

assert df_step23["Ship Mode"].notna().all(), (
    "ERROR: Ship Mode contains missing values."
)

assert df_step23["Region"].notna().all(), (
    "ERROR: Region contains missing values."
)

assert df_step23["Order ID"].notna().all(), (
    "ERROR: Order ID contains missing values."
)

print("✓ Record count validated.")
print("✓ Ship Mode values contain no missing values.")
print("✓ Region values contain no missing values.")
print("✓ Order IDs contain no missing values.")


# ------------------------------------------------------------
# 4. PARSE DATES FROM RAW CSV
# ------------------------------------------------------------

df_step23["Order Date"] = pd.to_datetime(
    df_step23["Order Date"],
    format="%d-%m-%Y",
    errors="raise"
)

df_step23["Ship Date"] = pd.to_datetime(
    df_step23["Ship Date"],
    format="%d-%m-%Y",
    errors="raise"
)

df_step23["Delivery_Days"] = (
    df_step23["Ship Date"] -
    df_step23["Order Date"]
).dt.days

assert df_step23["Delivery_Days"].notna().all(), (
    "ERROR: Delivery_Days contains missing values."
)

assert (df_step23["Delivery_Days"] >= 0).all(), (
    "ERROR: Negative delivery days detected."
)

print("✓ Dates parsed successfully.")
print("✓ Delivery_Days calculated successfully.")
print("✓ No negative delivery days found.")


# ------------------------------------------------------------
# 5. VALIDATED PRODUCT → FACTORY MAPPING
# ------------------------------------------------------------

def canonical_product_name(value):

    if pd.isna(value):
        return ""

    text = str(value)

    text = unicodedata.normalize("NFKC", text)
    text = text.replace("\u00A0", " ")
    text = text.strip()

    text = re.sub(r"\s*-\s*", " - ", text)
    text = re.sub(r"\s+", " ", text)

    return text


product_factory_mapping = {

    # Lot's O' Nuts
    "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
    "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
    "Wonka Bar - Scrumdiddlyumptious": "Lot's O' Nuts",

    # Wicked Choccy's
    "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
    "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",

    # Sugar Shack
    "Laffy Taffy": "Sugar Shack",
    "SweeTARTS": "Sugar Shack",
    "Nerds": "Sugar Shack",
    "Fun Dip": "Sugar Shack",
    "Fizzy Lifting Drinks": "Sugar Shack",

    # Secret Factory
    "Everlasting Gobstopper": "Secret Factory",
    "Lickable Wallpaper": "Secret Factory",
    "Wonka Gum": "Secret Factory",

    # The Other Factory
    "Hair Toffee": "The Other Factory",
    "Kazookles": "The Other Factory"
}


normalized_mapping = {
    canonical_product_name(product): factory
    for product, factory
    in product_factory_mapping.items()
}


df_step23["_Product_Key"] = (
    df_step23["Product Name"]
    .apply(canonical_product_name)
)

df_step23["Factory"] = (
    df_step23["_Product_Key"]
    .map(normalized_mapping)
)


# ------------------------------------------------------------
# 6. FACTORY MAPPING VALIDATION
# ------------------------------------------------------------

missing_factory_rows = df_step23["Factory"].isna().sum()

assert missing_factory_rows == 0, (
    "ERROR: Some products could not be mapped to a factory."
)

assert df_step23["Product Name"].nunique() == 15, (
    "ERROR: Expected exactly 15 products."
)

assert df_step23["Factory"].nunique() == 5, (
    "ERROR: Expected exactly 5 factories."
)

print("✓ Factory mapping validated.")
print("✓ 15 products mapped to 5 factories.")


# ------------------------------------------------------------
# 7. SHIPPING MODE VALIDATION
# ------------------------------------------------------------

expected_ship_modes = {
    "Standard Class",
    "First Class",
    "Second Class",
    "Same Day"
}

actual_ship_modes = set(
    df_step23["Ship Mode"].dropna().unique()
)

print("\nShipping modes detected:")
print(sorted(actual_ship_modes))

assert actual_ship_modes == expected_ship_modes, (
    f"ERROR: Shipping mode mismatch.\n"
    f"Expected: {expected_ship_modes}\n"
    f"Actual: {actual_ship_modes}"
)

print("✓ Exactly 4 expected shipping modes detected.")


# ------------------------------------------------------------
# 8. DATA-DRIVEN SLOW SHIPMENT THRESHOLD
# ------------------------------------------------------------

lead_time_q3 = (
    df_step23["Delivery_Days"]
    .quantile(0.75)
)

df_step23["Slow_Shipment"] = (
    df_step23["Delivery_Days"] > lead_time_q3
)

print("\nLead-time threshold:")
print(f"Q3 Lead Time: {lead_time_q3:.0f} days")
print("✓ Slow shipment flag created.")


# ============================================================
# 9. OVERALL SHIPPING MODE ANALYSIS
# ============================================================

ship_mode_summary = (
    df_step23
    .groupby("Ship Mode")
    .agg(
        Customers=("Customer ID", "nunique"),
        Orders=("Order ID", "nunique"),
        Records=("Order ID", "size"),
        Sales=("Sales", "sum"),
        Units=("Units", "sum"),
        Gross_Profit=("Gross Profit", "sum"),
        Cost=("Cost", "sum"),
        Avg_Lead_Days=("Delivery_Days", "mean"),
        Median_Lead_Days=("Delivery_Days", "median"),
        Slow_Shipments=("Slow_Shipment", "sum")
    )
    .reset_index()
)


ship_mode_summary["Profit_Margin_%"] = (
    ship_mode_summary["Gross_Profit"]
    / ship_mode_summary["Sales"]
    * 100
)

ship_mode_summary["Slow_Shipment_%"] = (
    ship_mode_summary["Slow_Shipments"]
    / ship_mode_summary["Records"]
    * 100
)

ship_mode_summary["Sales_Share_%"] = (
    ship_mode_summary["Sales"]
    / df_step23["Sales"].sum()
    * 100
)

ship_mode_summary = (
    ship_mode_summary
    .sort_values("Sales", ascending=False)
    .reset_index(drop=True)
)


print("\n" + "=" * 80)
print("OVERALL SHIPPING MODE PERFORMANCE")
print("=" * 80)

print(
    ship_mode_summary.to_string(
        index=False,
        formatters={
            "Sales": "{:,.2f}".format,
            "Gross_Profit": "{:,.2f}".format,
            "Cost": "{:,.2f}".format,
            "Profit_Margin_%": "{:.2f}".format,
            "Avg_Lead_Days": "{:.2f}".format,
            "Median_Lead_Days": "{:.0f}".format,
            "Slow_Shipment_%": "{:.2f}".format,
            "Sales_Share_%": "{:.2f}".format
        }
    )
)


# ============================================================
# 10. FACTORY × SHIPPING MODE
# ============================================================

factory_ship_summary = (
    df_step23
    .groupby(["Factory", "Ship Mode"])
    .agg(
        Orders=("Order ID", "nunique"),
        Records=("Order ID", "size"),
        Sales=("Sales", "sum"),
        Units=("Units", "sum"),
        Gross_Profit=("Gross Profit", "sum"),
        Avg_Lead_Days=("Delivery_Days", "mean"),
        Median_Lead_Days=("Delivery_Days", "median"),
        Slow_Shipments=("Slow_Shipment", "sum")
    )
    .reset_index()
)

factory_ship_summary["Profit_Margin_%"] = (
    factory_ship_summary["Gross_Profit"]
    / factory_ship_summary["Sales"]
    * 100
)

factory_ship_summary["Slow_Shipment_%"] = (
    factory_ship_summary["Slow_Shipments"]
    / factory_ship_summary["Records"]
    * 100
)

factory_ship_summary = (
    factory_ship_summary
    .sort_values(
        ["Factory", "Avg_Lead_Days"],
        ascending=[True, False]
    )
    .reset_index(drop=True)
)


print("\n" + "=" * 80)
print("FACTORY × SHIPPING MODE PERFORMANCE")
print("=" * 80)

print(
    factory_ship_summary.to_string(
        index=False,
        formatters={
            "Sales": "{:,.2f}".format,
            "Gross_Profit": "{:,.2f}".format,
            "Profit_Margin_%": "{:.2f}".format,
            "Avg_Lead_Days": "{:.2f}".format,
            "Median_Lead_Days": "{:.0f}".format,
            "Slow_Shipment_%": "{:.2f}".format
        }
    )
)


# ============================================================
# 11. REGION × SHIPPING MODE
# ============================================================

region_ship_summary = (
    df_step23
    .groupby(["Region", "Ship Mode"])
    .agg(
        Orders=("Order ID", "nunique"),
        Records=("Order ID", "size"),
        Sales=("Sales", "sum"),
        Units=("Units", "sum"),
        Gross_Profit=("Gross Profit", "sum"),
        Avg_Lead_Days=("Delivery_Days", "mean"),
        Median_Lead_Days=("Delivery_Days", "median"),
        Slow_Shipments=("Slow_Shipment", "sum")
    )
    .reset_index()
)

region_ship_summary["Profit_Margin_%"] = (
    region_ship_summary["Gross_Profit"]
    / region_ship_summary["Sales"]
    * 100
)

region_ship_summary["Slow_Shipment_%"] = (
    region_ship_summary["Slow_Shipments"]
    / region_ship_summary["Records"]
    * 100
)

region_ship_summary = (
    region_ship_summary
    .sort_values(
        ["Region", "Avg_Lead_Days"],
        ascending=[True, False]
    )
    .reset_index(drop=True)
)


print("\n" + "=" * 80)
print("REGION × SHIPPING MODE PERFORMANCE")
print("=" * 80)

print(
    region_ship_summary.to_string(
        index=False,
        formatters={
            "Sales": "{:,.2f}".format,
            "Gross_Profit": "{:,.2f}".format,
            "Profit_Margin_%": "{:.2f}".format,
            "Avg_Lead_Days": "{:.2f}".format,
            "Median_Lead_Days": "{:.0f}".format,
            "Slow_Shipment_%": "{:.2f}".format
        }
    )
)


# ============================================================
# 12. SHIPPING MODE RISK RANKING
# ============================================================

shipping_risk = (
    ship_mode_summary[
        [
            "Ship Mode",
            "Orders",
            "Records",
            "Sales",
            "Avg_Lead_Days",
            "Median_Lead_Days",
            "Slow_Shipment_%",
            "Profit_Margin_%"
        ]
    ]
    .copy()
)

shipping_risk = shipping_risk.sort_values(
    ["Slow_Shipment_%", "Avg_Lead_Days"],
    ascending=[False, False]
).reset_index(drop=True)

shipping_risk["Risk_Rank"] = (
    shipping_risk.index + 1
)

shipping_risk = shipping_risk[
    [
        "Risk_Rank",
        "Ship Mode",
        "Orders",
        "Records",
        "Sales",
        "Avg_Lead_Days",
        "Median_Lead_Days",
        "Slow_Shipment_%",
        "Profit_Margin_%"
    ]
]


print("\n" + "=" * 80)
print("SHIPPING MODE OPERATIONAL RISK RANKING")
print("=" * 80)

print(
    shipping_risk.to_string(
        index=False,
        formatters={
            "Sales": "{:,.2f}".format,
            "Avg_Lead_Days": "{:.2f}".format,
            "Median_Lead_Days": "{:.0f}".format,
            "Slow_Shipment_%": "{:.2f}".format,
            "Profit_Margin_%": "{:.2f}".format
        }
    )
)


# ============================================================
# 13. RECONCILIATION CHECKS
# ============================================================

dataset_sales = df_step23["Sales"].sum()
ship_mode_sales = ship_mode_summary["Sales"].sum()

dataset_records = len(df_step23)
ship_mode_records = ship_mode_summary["Records"].sum()


print("\n" + "=" * 80)
print("STEP 23 VALIDATION")
print("=" * 80)

print(f"Dataset records       : {dataset_records:,}")
print(f"Ship-mode records     : {ship_mode_records:,}")

print(f"Dataset sales         : {dataset_sales:,.2f}")
print(f"Ship-mode sales       : {ship_mode_sales:,.2f}")

print(f"Shipping modes        : {df_step23['Ship Mode'].nunique()}")
print(f"Factories             : {df_step23['Factory'].nunique()}")
print(f"Regions               : {df_step23['Region'].nunique()}")


# Records must reconcile
assert ship_mode_records == dataset_records, (
    "ERROR: Shipping-mode records do not reconcile."
)

# Sales must reconcile
assert abs(ship_mode_sales - dataset_sales) < 0.01, (
    "ERROR: Shipping-mode sales do not reconcile."
)

# Exactly four shipping modes
assert df_step23["Ship Mode"].nunique() == 4, (
    "ERROR: Expected exactly 4 shipping modes."
)

# Exactly five factories
assert df_step23["Factory"].nunique() == 5, (
    "ERROR: Expected exactly 5 factories."
)

# Exactly four regions
assert df_step23["Region"].nunique() == 4, (
    "ERROR: Expected exactly 4 regions."
)

# No invalid lead times
assert (
    df_step23["Delivery_Days"] >= 0
).all(), (
    "ERROR: Negative delivery days detected."
)

# Valid margins
assert ship_mode_summary[
    "Profit_Margin_%"
].between(0, 100).all(), (
    "ERROR: Invalid shipping-mode profit margin detected."
)

# Valid slow shipment rates
assert ship_mode_summary[
    "Slow_Shipment_%"
].between(0, 100).all(), (
    "ERROR: Invalid slow-shipment percentage detected."
)


# ============================================================
# 14. FINAL STATUS
# ============================================================

print("\n" + "=" * 80)
print("STEP 23 STATUS")
print("=" * 80)

print("✓ Shipping-mode analysis completed.")
print("✓ All 4 shipping modes validated.")
print("✓ Overall shipping performance calculated.")
print("✓ Factory × shipping mode analysis completed.")
print("✓ Region × shipping mode analysis completed.")
print("✓ Lead-time metrics calculated.")
print("✓ Slow-shipment rates calculated.")
print("✓ Shipping-mode sales reconcile with source dataset.")
print("✓ No factory coordinates were assumed.")
print("✓ Distance calculation remains pending verified coordinates.")

print("\nSTEP 23 completed successfully.")
print("=" * 80)

================================================================================
STEP 23: SHIPPING MODE EFFICIENCY ANALYSIS
================================================================================

✓ Raw dataset loaded successfully.
✓ Records loaded: 10,194

Required columns:
['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Region', 'Product Name', 'Sales', 'Units', 'Gross Profit', 'Cost']

Missing columns:
[]
✓ Required columns validated.
✓ Record count validated.
✓ Ship Mode values contain no missing values.
✓ Region values contain no missing values.
✓ Order IDs contain no missing values.
✓ Dates parsed successfully.
✓ Delivery_Days calculated successfully.
✓ No negative delivery days found.
✓ Factory mapping validated.
✓ 15 products mapped to 5 factories.

Shipping modes detected:
['First Class', 'Same Day', 'Second Class', 'Standard Class']
✓ Exactly 4 expected shipping modes detected.

Lead-time threshold:
Q3 Lead Time: 1638 days
✓ Slow shipment flag created.

================================================================================
OVERALL SHIPPING MODE PERFORMANCE
================================================================================
     Ship Mode  Customers  Orders  Records     Sales  Units Gross_Profit      Cost Avg_Lead_Days Median_Lead_Days  Slow_Shipments Profit_Margin_% Slow_Shipment_% Sales_Share_%
Standard Class       3027    5142     6120 85,490.35  23409    56,424.46 29,065.89       1314.33             1274            1891           66.00           30.90         60.30
  Second Class        966    1653     1979 27,860.22   7546    18,306.52  9,553.70       1323.85             1273             256           65.71           12.94         19.65
   First Class        787    1312     1548 21,319.39   5724    14,011.09  7,308.30       1338.28             1272               0           65.72            0.00         15.04
      Same Day        264     442      547  7,113.67   1975     4,700.73  2,412.94       1333.44             1269               0           66.08            0.00          5.02

================================================================================
FACTORY × SHIPPING MODE PERFORMANCE
================================================================================
          Factory      Ship Mode  Orders  Records     Sales  Units Gross_Profit Avg_Lead_Days Median_Lead_Days  Slow_Shipments Profit_Margin_% Slow_Shipment_%
    Lot's O' Nuts       Same Day     240      305  3,809.46   1069     2,633.26       1342.38             1269               0           69.12            0.00
    Lot's O' Nuts    First Class     745      890 11,849.91   3324     8,200.01       1340.01             1272               0           69.20            0.00
    Lot's O' Nuts   Second Class     932     1120 14,784.22   4147    10,220.22       1318.17             1273             132           69.13           11.79
    Lot's O' Nuts Standard Class    2843     3377 45,896.56  12872    31,717.56       1315.38             1274            1047           69.11           31.00
   Secret Factory   Second Class      42       43  1,868.75    175       936.55       1382.95             1274               7           50.12           16.28
   Secret Factory       Same Day      11       11    302.50     47       152.10       1335.82             1269               0           50.28            0.00
   Secret Factory    First Class      47       47  1,780.00    197       910.80       1310.49             1271               0           51.17            0.00
   Secret Factory Standard Class     113      116  4,636.25    465     2,345.25       1302.52             1274              41           50.59           35.34
      Sugar Shack       Same Day       1        1      7.96      4         4.96       1635.00             1635               0           62.31            0.00
      Sugar Shack   Second Class       5        5     22.50     15        10.10       1418.60             1272               1           44.89           20.00
      Sugar Shack Standard Class      23       23    164.04     80        90.19       1322.00             1275               7           54.98           30.43
      Sugar Shack    First Class       4        4     26.48      8        15.98       1271.75             1272               0           60.35            0.00
The Other Factory       Same Day       7        7     80.50     24        12.50       1321.43             1269               0           15.53            0.00
The Other Factory    First Class      17       17    214.25     64        32.25       1293.35             1272               0           15.05            0.00
The Other Factory Standard Class      53       55    734.00    222        88.00       1274.18             1274              13           11.99           23.64
The Other Factory   Second Class      21       21    253.50     78        19.50       1271.95             1271               3            7.69           14.29
  Wicked Choccy's    First Class     499      590  7,448.75   2131     4,852.05       1339.62             1272               0           65.14            0.00
  Wicked Choccy's   Second Class     653      790 10,931.25   3131     7,120.15       1329.45             1273             113           65.14           14.30
  Wicked Choccy's       Same Day     183      223  2,913.25    831     1,897.91       1320.12             1269               0           65.15            0.00
  Wicked Choccy's Standard Class    2110     2549 34,059.50   9770    22,183.46       1314.28             1274             783           65.13           30.72

================================================================================
REGION × SHIPPING MODE PERFORMANCE
================================================================================
  Region      Ship Mode  Orders  Records     Sales  Units Gross_Profit Avg_Lead_Days Median_Lead_Days  Slow_Shipments Profit_Margin_% Slow_Shipment_%
Atlantic    First Class     407      496  6,975.24   1828     4,546.35       1335.57             1272               0           65.18            0.00
Atlantic   Second Class     456      548  7,670.60   2074     5,031.62       1329.86             1273              73           65.60           13.32
Atlantic Standard Class    1487     1783 24,394.28   6669    15,978.33       1319.30             1274             551           65.50           30.90
Atlantic       Same Day     126      159  2,157.12    588     1,417.40       1296.82             1269               0           65.71            0.00
    Gulf   Second Class     276      329  4,614.62   1294     3,055.72       1324.72             1273              43           66.22           13.07
    Gulf    First Class     201      234  2,937.37    830     1,936.95       1319.82             1272               0           65.94            0.00
    Gulf Standard Class     808      974 13,563.60   3761     8,961.27       1306.93             1274             289           66.07           29.67
    Gulf       Same Day      65       83  1,131.67    324       746.73       1286.86             1269               0           65.98            0.00
Interior       Same Day      98      120  1,433.34    392       949.82       1397.23             1269               0           66.27            0.00
Interior    First Class     273      303  4,160.97   1164     2,755.48       1352.44             1272               0           66.22            0.00
Interior Standard Class    1230     1447 19,703.42   5469    13,131.28       1314.66             1274             451           66.64           31.17
Interior   Second Class     378      465  6,739.87   1795     4,445.91       1311.08             1273              51           65.96           10.97
 Pacific       Same Day     153      185  2,391.54    671     1,586.78       1344.44             1269               0           66.35            0.00
 Pacific    First Class     431      515  7,245.81   1902     4,772.31       1340.94             1272               0           65.86            0.00
 Pacific   Second Class     543      637  8,835.13   2383     5,773.27       1327.54             1273              89           65.34           13.97
 Pacific Standard Class    1617     1916 27,829.05   7510    18,353.58       1313.23             1274             600           65.95           31.32

================================================================================
SHIPPING MODE OPERATIONAL RISK RANKING
================================================================================
 Risk_Rank      Ship Mode  Orders  Records     Sales Avg_Lead_Days Median_Lead_Days Slow_Shipment_% Profit_Margin_%
         1 Standard Class    5142     6120 85,490.35       1314.33             1274           30.90           66.00
         2   Second Class    1653     1979 27,860.22       1323.85             1273           12.94           65.71
         3    First Class    1312     1548 21,319.39       1338.28             1272            0.00           65.72
         4       Same Day     442      547  7,113.67       1333.44             1269            0.00           66.08

================================================================================
STEP 23 VALIDATION
================================================================================
Dataset records       : 10,194
Ship-mode records     : 10,194
Dataset sales         : 141,783.63
Ship-mode sales       : 141,783.63
Shipping modes        : 4
Factories             : 5
Regions               : 4

================================================================================
STEP 23 STATUS
================================================================================
✓ Shipping-mode analysis completed.
✓ All 4 shipping modes validated.
✓ Overall shipping performance calculated.
✓ Factory × shipping mode analysis completed.
✓ Region × shipping mode analysis completed.
✓ Lead-time metrics calculated.
✓ Slow-shipment rates calculated.
✓ Shipping-mode sales reconcile with source dataset.
✓ No factory coordinates were assumed.
✓ Distance calculation remains pending verified coordinates.

STEP 23 completed successfully.
================================================================================

In [1]:
# ============================================================
# STEP 24: ML-READY DATASET & DATA LEAKAGE AUDIT
# ============================================================

import pandas as pd
import numpy as np
import re
import unicodedata
from pathlib import Path

print("=" * 80)
print("STEP 24: ML-READY DATASET & DATA LEAKAGE AUDIT")
print("=" * 80)


# ============================================================
# 1. LOCATE DATASET
# ============================================================

possible_paths = [
    Path("../data/Nassau Candy Distributor.csv"),
    Path("data/Nassau Candy Distributor.csv"),
    Path("Nassau Candy Distributor.csv"),
]

DATA_PATH = next(
    (path for path in possible_paths if path.exists()),
    None
)

if DATA_PATH is None:
    raise FileNotFoundError(
        "Nassau Candy Distributor.csv was not found."
    )

print(f"\n✓ Dataset found: {DATA_PATH}")


# ============================================================
# 2. LOAD RAW DATASET
# ============================================================

ml_df = pd.read_csv(DATA_PATH)

print(f"✓ Raw records loaded: {len(ml_df):,}")


# ============================================================
# 3. REQUIRED COLUMN VALIDATION
# ============================================================

required_columns = [
    "Order ID",
    "Order Date",
    "Ship Date",
    "Ship Mode",
    "Customer ID",
    "Country/Region",
    "State/Province",
    "Division",
    "Region",
    "Product Name",
    "Sales",
    "Units",
    "Gross Profit",
    "Cost"
]

missing_columns = [
    column
    for column in required_columns
    if column not in ml_df.columns
]

print("\nRequired columns missing:")
print(missing_columns)

if missing_columns:
    raise KeyError(
        f"Required columns are missing: {missing_columns}"
    )

print("✓ Required columns validated.")


# ============================================================
# 4. RAW DATA QUALITY VALIDATION
# ============================================================

if ml_df[required_columns].isnull().any().any():

    missing_summary = (
        ml_df[required_columns]
        .isnull()
        .sum()
    )

    missing_summary = missing_summary[
        missing_summary > 0
    ]

    raise ValueError(
        "Missing values found in required columns:\n"
        f"{missing_summary}"
    )

print("✓ No missing values in required columns.")


# ============================================================
# 5. CORRECT DATE PARSING
# ============================================================

ml_df["Order Date"] = pd.to_datetime(
    ml_df["Order Date"],
    format="%d-%m-%Y",
    errors="raise"
)

ml_df["Ship Date"] = pd.to_datetime(
    ml_df["Ship Date"],
    format="%d-%m-%Y",
    errors="raise"
)

print("✓ Order Date parsed successfully.")
print("✓ Ship Date parsed successfully.")


# ============================================================
# 6. DELIVERY / LEAD TIME CALCULATION
# ============================================================

ml_df["Delivery_Days"] = (
    ml_df["Ship Date"] -
    ml_df["Order Date"]
).dt.days


if ml_df["Delivery_Days"].isna().any():
    raise ValueError(
        "Missing Delivery_Days detected."
    )


if (ml_df["Delivery_Days"] < 0).any():
    raise ValueError(
        "Negative Delivery_Days detected."
    )

print("✓ Delivery_Days calculated successfully.")
print(
    f"  Mean lead time   : "
    f"{ml_df['Delivery_Days'].mean():.2f} days"
)
print(
    f"  Median lead time : "
    f"{ml_df['Delivery_Days'].median():.2f} days"
)


# ============================================================
# 7. VALIDATED PRODUCT → FACTORY MAPPING
# ============================================================

factory_mapping = {

    "Wonka Bar - Nutty Crunch Surprise":
        "Lot's O' Nuts",

    "Wonka Bar - Fudge Mallows":
        "Lot's O' Nuts",

    "Wonka Bar - Scrumdiddlyumptious":
        "Lot's O' Nuts",

    "Wonka Bar - Milk Chocolate":
        "Wicked Choccy’s",

    "Wonka Bar - Triple Dazzle Caramel":
        "Wicked Choccy’s",

    "Laffy Taffy":
        "Sugar Shack",

    "SweeTARTS":
        "Sugar Shack",

    "Nerds":
        "Sugar Shack",

    "Fun Dip":
        "Sugar Shack",

    "Fizzy Lifting Drinks":
        "Sugar Shack",

    "Everlasting Gobstopper":
        "Secret Factory",

    "Lickable Wallpaper":
        "Secret Factory",

    "Wonka Gum":
        "Secret Factory",

    "Hair Toffee":
        "The Other Factory",

    "Kazookles":
        "The Other Factory"
}


def canonical_product_name(value):

    if pd.isna(value):
        return ""

    text = str(value)

    text = unicodedata.normalize(
        "NFKC",
        text
    )

    text = text.replace(
        "\u00A0",
        " "
    )

    text = text.strip()

    text = re.sub(
        r"\s*-\s*",
        " - ",
        text
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text


canonical_mapping = {
    canonical_product_name(product): factory
    for product, factory
    in factory_mapping.items()
}


ml_df["Factory"] = (
    ml_df["Product Name"]
    .map(
        lambda value:
        canonical_mapping.get(
            canonical_product_name(value)
        )
    )
)


# ============================================================
# 8. FACTORY MAPPING VALIDATION
# ============================================================

missing_factory_rows = (
    ml_df["Factory"]
    .isna()
    .sum()
)

unique_products = (
    ml_df["Product Name"]
    .nunique()
)

unique_factories = (
    ml_df["Factory"]
    .nunique()
)

print("\n========== FACTORY VALIDATION ==========")

print(
    f"Unique products  : {unique_products}"
)

print(
    f"Unique factories : {unique_factories}"
)

print(
    f"Unmapped rows    : {missing_factory_rows}"
)

if missing_factory_rows != 0:
    raise ValueError(
        "Some products could not be mapped to a factory."
    )

if unique_products != 15:
    raise ValueError(
        f"Expected 15 products, found {unique_products}."
    )

if unique_factories != 5:
    raise ValueError(
        f"Expected 5 factories, found {unique_factories}."
    )

print("✓ Factory mapping validated.")


# ============================================================
# 9. CREATE SLOW-SHIPMENT TARGET
# ============================================================

q3_lead_time = (
    ml_df["Delivery_Days"]
    .quantile(0.75)
)

ml_df["Slow_Shipment"] = (
    ml_df["Delivery_Days"] >
    q3_lead_time
).astype(int)


print("\n========== TARGET DEFINITION ==========")

print(
    f"Q3 lead-time threshold : "
    f"{q3_lead_time:.2f} days"
)

target_counts = (
    ml_df["Slow_Shipment"]
    .value_counts()
    .sort_index()
)

print("\nTarget distribution:")

print(
    target_counts.to_string()
)


# ============================================================
# 10. CREATE ORDER-TIME FEATURES
# ============================================================

ml_df["Order_Year"] = (
    ml_df["Order Date"].dt.year
)

ml_df["Order_Month"] = (
    ml_df["Order Date"].dt.month
)

ml_df["Order_Quarter"] = (
    ml_df["Order Date"].dt.quarter
)

ml_df["Order_DayOfWeek"] = (
    ml_df["Order Date"].dt.dayofweek
)


# ============================================================
# 11. DEFINE ML FEATURES
# ============================================================

feature_columns = [

    # Product information
    "Product Name",
    "Division",

    # Customer geography
    "Country/Region",
    "State/Province",
    "Region",

    # Operational assignment
    "Factory",
    "Ship Mode",

    # Order-time numerical information
    "Units",
    "Sales",
    "Cost",
    "Gross Profit",

    # Calendar features
    "Order_Year",
    "Order_Month",
    "Order_Quarter",
    "Order_DayOfWeek"
]


target_column = "Slow_Shipment"


# ============================================================
# 12. CREATE MODELING DATASET
# ============================================================

model_df = ml_df[
    feature_columns +
    [target_column]
].copy()


# ============================================================
# 13. DATA LEAKAGE AUDIT
# ============================================================

forbidden_leakage_columns = [
    "Ship Date",
    "Delivery_Days",
    "Slow_Shipment"
]

feature_set = set(feature_columns)

leakage_detected = (
    feature_set
    .intersection(
        forbidden_leakage_columns
    )
)

print("\n========== DATA LEAKAGE AUDIT ==========")

print(
    "Forbidden outcome columns found in features:"
)

print(
    leakage_detected
)

if leakage_detected:
    raise ValueError(
        "DATA LEAKAGE DETECTED: "
        f"{sorted(leakage_detected)}"
    )

print("✓ No direct target leakage detected.")


# ============================================================
# 14. FEATURE COMPLETENESS CHECK
# ============================================================

missing_feature_values = (
    model_df[feature_columns]
    .isnull()
    .sum()
)

missing_feature_values = (
    missing_feature_values[
        missing_feature_values > 0
    ]
)

if len(missing_feature_values) > 0:

    raise ValueError(
        "Missing feature values detected:\n"
        f"{missing_feature_values}"
    )

print("✓ All model features are complete.")


# ============================================================
# 15. TARGET VALIDATION
# ============================================================

if not set(
    model_df[target_column].unique()
).issubset({0, 1}):

    raise ValueError(
        "Target column contains values other than 0 and 1."
    )

print("✓ Target is binary: 0 = normal, 1 = slow.")


# ============================================================
# 16. DATASET DIMENSION CHECK
# ============================================================

print("\n========== ML DATASET SUMMARY ==========")

print(
    f"Rows             : {len(model_df):,}"
)

print(
    f"Features         : {len(feature_columns)}"
)

print(
    f"Target           : {target_column}"
)

print(
    f"Products         : "
    f"{ml_df['Product Name'].nunique()}"
)

print(
    f"Factories        : "
    f"{ml_df['Factory'].nunique()}"
)

print(
    f"Regions          : "
    f"{ml_df['Region'].nunique()}"
)

print(
    f"Shipping modes   : "
    f"{ml_df['Ship Mode'].nunique()}"
)


# ============================================================
# 17. DISPLAY FINAL FEATURE LIST
# ============================================================

print("\n========== FINAL ML FEATURES ==========")

for number, column in enumerate(
    feature_columns,
    start=1
):

    print(
        f"{number:02d}. {column}"
    )


# ============================================================
# 18. FINAL VALIDATIONS
# ============================================================

assert len(ml_df) == 10194
assert len(model_df) == 10194
assert unique_products == 15
assert unique_factories == 5
assert missing_factory_rows == 0
assert ml_df["Delivery_Days"].min() >= 0
assert model_df[feature_columns].isnull().sum().sum() == 0
assert len(leakage_detected) == 0
assert set(
    model_df[target_column].unique()
).issubset({0, 1})


# ============================================================
# FINAL STATUS
# ============================================================

print("\n" + "=" * 80)
print("STEP 24 COMPLETED SUCCESSFULLY")
print("=" * 80)

print("✓ Raw dataset loaded independently.")
print("✓ 10,194 records validated.")
print("✓ Dates parsed using the validated DD-MM-YYYY format.")
print("✓ Delivery_Days calculated.")
print("✓ Factory mapping validated: 15 products → 5 factories.")
print("✓ Slow-shipment target created using dataset Q3.")
print("✓ Order-time features created.")
print("✓ ML feature set created.")
print("✓ Direct target leakage checked.")
print("✓ No leakage detected.")
print("✓ ML dataset is ready for model training.")
print("✓ Factory coordinates were NOT assumed.")
print("=" * 80)

================================================================================
STEP 24: ML-READY DATASET & DATA LEAKAGE AUDIT
================================================================================

✓ Dataset found: ..\data\Nassau Candy Distributor.csv
✓ Raw records loaded: 10,194

Required columns missing:
[]
✓ Required columns validated.
✓ No missing values in required columns.
✓ Order Date parsed successfully.
✓ Ship Date parsed successfully.
✓ Delivery_Days calculated successfully.
  Mean lead time   : 1320.84 days
  Median lead time : 1274.00 days

========== FACTORY VALIDATION ==========
Unique products  : 15
Unique factories : 5
Unmapped rows    : 0
✓ Factory mapping validated.

========== TARGET DEFINITION ==========
Q3 lead-time threshold : 1638.00 days

Target distribution:
Slow_Shipment
0    8047
1    2147

========== DATA LEAKAGE AUDIT ==========
Forbidden outcome columns found in features:
set()
✓ No direct target leakage detected.
✓ All model features are complete.
✓ Target is binary: 0 = normal, 1 = slow.

========== ML DATASET SUMMARY ==========
Rows             : 10,194
Features         : 15
Target           : Slow_Shipment
Products         : 15
Factories        : 5
Regions          : 4
Shipping modes   : 4

========== FINAL ML FEATURES ==========
01. Product Name
02. Division
03. Country/Region
04. State/Province
05. Region
06. Factory
07. Ship Mode
08. Units
09. Sales
10. Cost
11. Gross Profit
12. Order_Year
13. Order_Month
14. Order_Quarter
15. Order_DayOfWeek

================================================================================
STEP 24 COMPLETED SUCCESSFULLY
================================================================================
✓ Raw dataset loaded independently.
✓ 10,194 records validated.
✓ Dates parsed using the validated DD-MM-YYYY format.
✓ Delivery_Days calculated.
✓ Factory mapping validated: 15 products → 5 factories.
✓ Slow-shipment target created using dataset Q3.
✓ Order-time features created.
✓ ML feature set created.
✓ Direct target leakage checked.
✓ No leakage detected.
✓ ML dataset is ready for model training.
✓ Factory coordinates were NOT assumed.
================================================================================

In [5]:
# ============================================================
# STEP 25A — ORDER-LEVEL TRAIN/TEST SPLIT
# FINAL VERSION
# ============================================================

import sys
import subprocess
import importlib.util

# ------------------------------------------------------------
# 0. AUTOMATICALLY CHECK / INSTALL SCIKIT-LEARN
# ------------------------------------------------------------

if importlib.util.find_spec("sklearn") is None:

    print("scikit-learn is not installed.")
    print("Installing scikit-learn in the CURRENT Python environment...")
    
    subprocess.check_call([
        sys.executable,
        "-m",
        "pip",
        "install",
        "scikit-learn"
    ])

    print("✓ scikit-learn installation completed.")


# Import AFTER installation
from sklearn.model_selection import GroupShuffleSplit

import os
import re
import unicodedata
import pandas as pd
import numpy as np


print("=" * 70)
print("STEP 25A — ORDER-LEVEL TRAIN/TEST SPLIT")
print("=" * 70)


# ------------------------------------------------------------
# 1. FIND DATASET
# ------------------------------------------------------------

possible_paths = [
    "../data/Nassau Candy Distributor.csv",
    "/mnt/data/Nassau Candy Distributor.csv",
    "/mnt/data/files/Nassau Candy Distributor.csv"
]

DATA_PATH = None

for path in possible_paths:
    if os.path.exists(path):
        DATA_PATH = path
        break

if DATA_PATH is None:
    raise FileNotFoundError(
        "Nassau Candy Distributor.csv not found."
    )

print("✓ Dataset found:")
print(DATA_PATH)


# ------------------------------------------------------------
# 2. LOAD DATA
# ------------------------------------------------------------

df_ml = pd.read_csv(DATA_PATH)

print(f"✓ Dataset loaded")
print(f"✓ Records: {len(df_ml):,}")


# ------------------------------------------------------------
# 3. REQUIRED COLUMNS
# ------------------------------------------------------------

required_columns = [
    "Order ID",
    "Order Date",
    "Ship Date",
    "Ship Mode",
    "Customer ID",
    "Country/Region",
    "State/Province",
    "Region",
    "Product Name",
    "Division",
    "Units",
    "Sales",
    "Cost",
    "Gross Profit"
]

missing_columns = [
    column
    for column in required_columns
    if column not in df_ml.columns
]

if missing_columns:
    raise ValueError(
        f"Missing required columns: {missing_columns}"
    )

print("✓ Required columns verified")
print(f"✓ Missing columns: {missing_columns}")


# ------------------------------------------------------------
# 4. PRODUCT NORMALIZATION FUNCTION
# ------------------------------------------------------------

def canonical_product_name(value):

    if pd.isna(value):
        return ""

    text = unicodedata.normalize(
        "NFKC",
        str(value)
    )

    text = text.replace("\u00A0", " ")
    text = text.strip()

    text = re.sub(
        r"\s*-\s*",
        " - ",
        text
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text


# ------------------------------------------------------------
# 5. VALIDATED PRODUCT → FACTORY MAPPING
# ------------------------------------------------------------

product_factory_mapping = {

    "Wonka Bar - Nutty Crunch Surprise":
        "Lot’s O’ Nuts",

    "Wonka Bar - Fudge Mallows":
        "Lot’s O’ Nuts",

    "Wonka Bar - Scrumdiddlyumptious":
        "Lot’s O’ Nuts",

    "Wonka Bar - Milk Chocolate":
        "Wicked Choccy’s",

    "Wonka Bar - Triple Dazzle Caramel":
        "Wicked Choccy’s",

    "Laffy Taffy":
        "Sugar Shack",

    "SweeTARTS":
        "Sugar Shack",

    "Nerds":
        "Sugar Shack",

    "Fun Dip":
        "Sugar Shack",

    "Fizzy Lifting Drinks":
        "Sugar Shack",

    "Everlasting Gobstopper":
        "Secret Factory",

    "Lickable Wallpaper":
        "Secret Factory",

    "Wonka Gum":
        "Secret Factory",

    "Hair Toffee":
        "The Other Factory",

    "Kazookles":
        "The Other Factory"
}


normalized_factory_mapping = {
    canonical_product_name(product): factory
    for product, factory
    in product_factory_mapping.items()
}


# ------------------------------------------------------------
# 6. ASSIGN FACTORY
# ------------------------------------------------------------

df_ml["_Product_Key"] = (
    df_ml["Product Name"]
    .map(canonical_product_name)
)

df_ml["Factory"] = (
    df_ml["_Product_Key"]
    .map(normalized_factory_mapping)
)


# ------------------------------------------------------------
# 7. FACTORY VALIDATION
# ------------------------------------------------------------

unmapped_rows = df_ml["Factory"].isna().sum()

if unmapped_rows > 0:

    unmapped_products = (
        df_ml.loc[
            df_ml["Factory"].isna(),
            "Product Name"
        ]
        .drop_duplicates()
        .tolist()
    )

    raise ValueError(
        f"Factory mapping failed.\n"
        f"Unmapped rows: {unmapped_rows}\n"
        f"Products: {unmapped_products}"
    )

print("✓ Factory mapping validated")
print(
    f"✓ Products: "
    f"{df_ml['Product Name'].nunique()}"
)
print(
    f"✓ Factories: "
    f"{df_ml['Factory'].nunique()}"
)
print(
    f"✓ Unmapped rows: "
    f"{unmapped_rows}"
)


# ------------------------------------------------------------
# 8. DATE CONVERSION
# ------------------------------------------------------------

df_ml["Order Date"] = pd.to_datetime(
    df_ml["Order Date"],
    format="%d-%m-%Y",
    errors="raise"
)

df_ml["Ship Date"] = pd.to_datetime(
    df_ml["Ship Date"],
    format="%d-%m-%Y",
    errors="raise"
)

print("✓ Order Date parsed")
print("✓ Ship Date parsed")


# ------------------------------------------------------------
# 9. DELIVERY DAYS
# ------------------------------------------------------------

df_ml["Delivery_Days"] = (
    df_ml["Ship Date"] -
    df_ml["Order Date"]
).dt.days


if df_ml["Delivery_Days"].isna().any():
    raise ValueError(
        "Missing Delivery_Days detected."
    )


if (df_ml["Delivery_Days"] < 0).any():
    raise ValueError(
        "Negative Delivery_Days detected."
    )


print("✓ Delivery_Days calculated")

print(
    f"✓ Mean lead time: "
    f"{df_ml['Delivery_Days'].mean():.2f} days"
)

print(
    f"✓ Median lead time: "
    f"{df_ml['Delivery_Days'].median():.0f} days"
)


# ------------------------------------------------------------
# 10. ORDER-LEVEL TRAIN / TEST SPLIT
# ------------------------------------------------------------

splitter = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)


train_indices, test_indices = next(
    splitter.split(
        df_ml,
        groups=df_ml["Order ID"]
    )
)


train_df = df_ml.iloc[
    train_indices
].copy()

test_df = df_ml.iloc[
    test_indices
].copy()


print("✓ Train/Test split completed")


# ------------------------------------------------------------
# 11. ORDER LEAKAGE CHECK
# ------------------------------------------------------------

train_orders = set(
    train_df["Order ID"].unique()
)

test_orders = set(
    test_df["Order ID"].unique()
)

order_overlap = (
    train_orders
    .intersection(test_orders)
)


if len(order_overlap) != 0:

    raise ValueError(
        f"ORDER LEAKAGE DETECTED: "
        f"{len(order_overlap)} orders overlap."
    )


print("✓ Order ID overlap: 0")
print("✓ No order-level leakage")


# ------------------------------------------------------------
# 12. TRAIN-ONLY Q3 THRESHOLD
# ------------------------------------------------------------

train_q3_threshold = float(
    train_df["Delivery_Days"].quantile(0.75)
)


train_df["Slow_Shipment"] = (
    train_df["Delivery_Days"]
    > train_q3_threshold
).astype(int)


test_df["Slow_Shipment"] = (
    test_df["Delivery_Days"]
    > train_q3_threshold
).astype(int)


print(
    f"✓ Train-only Q3 threshold: "
    f"{train_q3_threshold:.0f} days"
)


# ------------------------------------------------------------
# 13. TIME FEATURES
# ------------------------------------------------------------

for data in [train_df, test_df]:

    data["Order_Year"] = (
        data["Order Date"].dt.year
    )

    data["Order_Month"] = (
        data["Order Date"].dt.month
    )

    data["Order_Quarter"] = (
        data["Order Date"].dt.quarter
    )

    data["Order_DayOfWeek"] = (
        data["Order Date"].dt.dayofweek
    )


# ------------------------------------------------------------
# 14. ML FEATURES
# ------------------------------------------------------------

feature_columns = [

    "Product Name",

    "Division",

    "Country/Region",

    "State/Province",

    "Region",

    "Factory",

    "Ship Mode",

    "Units",

    "Sales",

    "Cost",

    "Gross Profit",

    "Order_Year",

    "Order_Month",

    "Order_Quarter",

    "Order_DayOfWeek"
]


# ------------------------------------------------------------
# 15. CREATE X / y
# ------------------------------------------------------------

X_train = train_df[
    feature_columns
].copy()

X_test = test_df[
    feature_columns
].copy()

y_train = train_df[
    "Slow_Shipment"
].copy()

y_test = test_df[
    "Slow_Shipment"
].copy()


# ------------------------------------------------------------
# 16. LEAKAGE COLUMN CHECK
# ------------------------------------------------------------

forbidden_columns = [
    "Ship Date",
    "Delivery_Days",
    "Slow_Shipment"
]


leakage_columns = [
    column
    for column in forbidden_columns
    if column in X_train.columns
]


if leakage_columns:

    raise ValueError(
        f"LEAKAGE COLUMNS FOUND: "
        f"{leakage_columns}"
    )


print("✓ No target leakage")
print("✓ Delivery_Days not used as feature")
print("✓ Ship Date not used as feature")


# ------------------------------------------------------------
# 17. TARGET VALIDATION
# ------------------------------------------------------------

if y_train.nunique() != 2:
    raise ValueError(
        "Training target does not contain both classes."
    )

if y_test.nunique() != 2:
    raise ValueError(
        "Testing target does not contain both classes."
    )


# ------------------------------------------------------------
# 18. FINAL REPORT
# ------------------------------------------------------------

print()
print("=" * 70)
print("STEP 25A — FINAL VALIDATION REPORT")
print("=" * 70)

print(
    f"Total records          : "
    f"{len(df_ml):,}"
)

print(
    f"Unique orders          : "
    f"{df_ml['Order ID'].nunique():,}"
)

print(
    f"Training records       : "
    f"{len(train_df):,}"
)

print(
    f"Testing records        : "
    f"{len(test_df):,}"
)

print(
    f"Training orders        : "
    f"{train_df['Order ID'].nunique():,}"
)

print(
    f"Testing orders         : "
    f"{test_df['Order ID'].nunique():,}"
)

print(
    f"Order overlap          : "
    f"{len(order_overlap)}"
)

print(
    f"Train Q3 threshold     : "
    f"{train_q3_threshold:.0f} days"
)

print(
    f"Train slow shipments   : "
    f"{y_train.sum():,} "
    f"({y_train.mean() * 100:.2f}%)"
)

print(
    f"Test slow shipments    : "
    f"{y_test.sum():,} "
    f"({y_test.mean() * 100:.2f}%)"
)

print(
    f"Number of features     : "
    f"{len(feature_columns)}"
)

print(
    f"X_train shape          : "
    f"{X_train.shape}"
)

print(
    f"X_test shape           : "
    f"{X_test.shape}"
)

print()
print("✓ scikit-learn available")
print("✓ Factory mapping validated")
print("✓ Dates validated")
print("✓ Delivery_Days validated")
print("✓ Order-level split validated")
print("✓ Order leakage = 0")
print("✓ Target leakage = 0")
print("✓ Train-only threshold used")
print("✓ Both target classes available")
print("✓ ML feature matrix created")

print()
print("STATUS: STEP 25A COMPLETED SUCCESSFULLY")
print("=" * 70)

scikit-learn is not installed.
Installing scikit-learn in the CURRENT Python environment...
✓ scikit-learn installation completed.
======================================================================
STEP 25A — ORDER-LEVEL TRAIN/TEST SPLIT
======================================================================
✓ Dataset found:
../data/Nassau Candy Distributor.csv
✓ Dataset loaded
✓ Records: 10,194
✓ Required columns verified
✓ Missing columns: []
✓ Factory mapping validated
✓ Products: 15
✓ Factories: 5
✓ Unmapped rows: 0
✓ Order Date parsed
✓ Ship Date parsed
✓ Delivery_Days calculated
✓ Mean lead time: 1320.84 days
✓ Median lead time: 1274 days
✓ Train/Test split completed
✓ Order ID overlap: 0
✓ No order-level leakage
✓ Train-only Q3 threshold: 1638 days
✓ No target leakage
✓ Delivery_Days not used as feature
✓ Ship Date not used as feature

======================================================================
STEP 25A — FINAL VALIDATION REPORT
======================================================================
Total records          : 10,194
Unique orders          : 8,549
Training records       : 8,132
Testing records        : 2,062
Training orders        : 6,839
Testing orders         : 1,710
Order overlap          : 0
Train Q3 threshold     : 1638 days
Train slow shipments   : 1,719 (21.14%)
Test slow shipments    : 428 (20.76%)
Number of features     : 15
X_train shape          : (8132, 15)
X_test shape           : (2062, 15)

✓ scikit-learn available
✓ Factory mapping validated
✓ Dates validated
✓ Delivery_Days validated
✓ Order-level split validated
✓ Order leakage = 0
✓ Target leakage = 0
✓ Train-only threshold used
✓ Both target classes available
✓ ML feature matrix created

STATUS: STEP 25A COMPLETED SUCCESSFULLY
======================================================================

In [6]:
# ============================================================
# STEP 25B — ML MODEL TRAINING & EVALUATION
# ============================================================

import sys
import subprocess
import importlib.util
import os
import re
import unicodedata
import warnings

warnings.filterwarnings("ignore")

# ------------------------------------------------------------
# 1. CHECK / INSTALL REQUIRED LIBRARIES
# ------------------------------------------------------------

required_packages = {
    "pandas": "pandas",
    "numpy": "numpy",
    "sklearn": "scikit-learn"
}

for module_name, package_name in required_packages.items():
    if importlib.util.find_spec(module_name) is None:
        print(f"Installing missing package: {package_name}")
        subprocess.check_call([
            sys.executable,
            "-m",
            "pip",
            "install",
            package_name
        ])

import pandas as pd
import numpy as np

from sklearn.model_selection import GroupShuffleSplit
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)

import sklearn

print("=" * 70)
print("STEP 25B — ML MODEL TRAINING & EVALUATION")
print("=" * 70)
print(f"✓ Python environment: {sys.executable}")
print(f"✓ scikit-learn version: {sklearn.__version__}")


# ------------------------------------------------------------
# 2. LOCATE DATASET
# ------------------------------------------------------------

possible_paths = [
    "../data/Nassau Candy Distributor.csv",
    "/mnt/data/Nassau Candy Distributor.csv",
    "/mnt/data/files/Nassau Candy Distributor.csv"
]

data_path = None

for path in possible_paths:
    if os.path.exists(path):
        data_path = path
        break

if data_path is None:
    raise FileNotFoundError(
        "Nassau Candy Distributor.csv was not found."
    )

df_ml = pd.read_csv(data_path)

print(f"✓ Dataset loaded: {data_path}")
print(f"✓ Records: {len(df_ml):,}")


# ------------------------------------------------------------
# 3. REQUIRED COLUMN VALIDATION
# ------------------------------------------------------------

required_columns = [
    "Row ID",
    "Order ID",
    "Order Date",
    "Ship Date",
    "Ship Mode",
    "Customer ID",
    "Country/Region",
    "City",
    "State/Province",
    "Postal Code",
    "Division",
    "Region",
    "Product ID",
    "Product Name",
    "Sales",
    "Units",
    "Gross Profit",
    "Cost"
]

missing_columns = [
    col for col in required_columns
    if col not in df_ml.columns
]

if missing_columns:
    raise ValueError(
        f"Missing required columns: {missing_columns}"
    )

print(f"✓ Missing required columns: {missing_columns}")


# ------------------------------------------------------------
# 4. VALIDATED PRODUCT → FACTORY MAPPING
# ------------------------------------------------------------

def canonical_product_name(value):
    if pd.isna(value):
        return ""

    text = str(value)

    text = unicodedata.normalize("NFKC", text)
    text = text.replace("\u00A0", " ")
    text = text.strip()

    text = re.sub(r"\s*-\s*", " - ", text)
    text = re.sub(r"\s+", " ", text)

    return text


product_factory_map = {
    "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
    "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
    "Wonka Bar - Scrumdiddlyumptious": "Lot's O' Nuts",

    "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
    "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",

    "Laffy Taffy": "Sugar Shack",
    "SweeTARTS": "Sugar Shack",
    "Nerds": "Sugar Shack",
    "Fun Dip": "Sugar Shack",
    "Fizzy Lifting Drinks": "Sugar Shack",

    "Everlasting Gobstopper": "Secret Factory",
    "Lickable Wallpaper": "Secret Factory",
    "Wonka Gum": "Secret Factory",

    "Hair Toffee": "The Other Factory",
    "Kazookles": "The Other Factory"
}

df_ml["_Product_Key"] = (
    df_ml["Product Name"]
    .map(canonical_product_name)
)

normalized_map = {
    canonical_product_name(k): v
    for k, v in product_factory_map.items()
}

df_ml["Factory"] = df_ml["_Product_Key"].map(normalized_map)

unmapped_rows = int(df_ml["Factory"].isna().sum())

if unmapped_rows != 0:
    raise ValueError(
        f"Factory mapping failed. Unmapped rows: {unmapped_rows}"
    )

print("✓ Factory mapping validated")
print(f"✓ Products: {df_ml['Product Name'].nunique()}")
print(f"✓ Factories: {df_ml['Factory'].nunique()}")
print(f"✓ Unmapped rows: {unmapped_rows}")


# ------------------------------------------------------------
# 5. DATE PROCESSING
# ------------------------------------------------------------

df_ml["Order Date"] = pd.to_datetime(
    df_ml["Order Date"],
    format="%d-%m-%Y",
    errors="raise"
)

df_ml["Ship Date"] = pd.to_datetime(
    df_ml["Ship Date"],
    format="%d-%m-%Y",
    errors="raise"
)

df_ml["Delivery_Days"] = (
    df_ml["Ship Date"] - df_ml["Order Date"]
).dt.days

if df_ml["Delivery_Days"].isna().any():
    raise ValueError("Missing Delivery_Days detected.")

if (df_ml["Delivery_Days"] < 0).any():
    raise ValueError("Negative Delivery_Days detected.")

print("✓ Dates parsed")
print("✓ Delivery_Days calculated")


# ------------------------------------------------------------
# 6. ORDER-LEVEL TRAIN / TEST SPLIT
# ------------------------------------------------------------

splitter = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

train_idx, test_idx = next(
    splitter.split(
        df_ml,
        groups=df_ml["Order ID"]
    )
)

train_df = df_ml.iloc[train_idx].copy()
test_df = df_ml.iloc[test_idx].copy()

train_orders = set(train_df["Order ID"])
test_orders = set(test_df["Order ID"])

order_overlap = train_orders.intersection(test_orders)

if len(order_overlap) != 0:
    raise ValueError(
        f"Order leakage detected: {len(order_overlap)} overlapping orders."
    )

print("✓ Order-level train/test split completed")
print(f"✓ Train records: {len(train_df):,}")
print(f"✓ Test records: {len(test_df):,}")
print(f"✓ Train orders: {len(train_orders):,}")
print(f"✓ Test orders: {len(test_orders):,}")
print(f"✓ Order overlap: {len(order_overlap)}")


# ------------------------------------------------------------
# 7. TRAIN-ONLY TARGET THRESHOLD
# ------------------------------------------------------------

train_q3 = float(
    train_df["Delivery_Days"].quantile(0.75)
)

test_q3 = float(
    test_df["Delivery_Days"].quantile(0.75)
)

train_df["Slow_Shipment"] = (
    train_df["Delivery_Days"] > train_q3
).astype(int)

test_df["Slow_Shipment"] = (
    test_df["Delivery_Days"] > train_q3
).astype(int)

print(f"✓ Train-only Q3 threshold: {train_q3:.0f} days")
print(
    f"✓ Train slow shipments: "
    f"{train_df['Slow_Shipment'].sum():,}"
)
print(
    f"✓ Test slow shipments: "
    f"{test_df['Slow_Shipment'].sum():,}"
)


# ------------------------------------------------------------
# 8. TIME FEATURES
# ------------------------------------------------------------

for data in [train_df, test_df]:

    data["Order_Year"] = data["Order Date"].dt.year
    data["Order_Month"] = data["Order Date"].dt.month
    data["Order_Quarter"] = data["Order Date"].dt.quarter
    data["Order_DayOfWeek"] = data["Order Date"].dt.dayofweek


# ------------------------------------------------------------
# 9. DEFINE ML FEATURES
# ------------------------------------------------------------

categorical_features = [
    "Product Name",
    "Division",
    "Country/Region",
    "State/Province",
    "Region",
    "Factory",
    "Ship Mode"
]

numeric_features = [
    "Units",
    "Sales",
    "Cost",
    "Gross Profit",
    "Order_Year",
    "Order_Month",
    "Order_Quarter",
    "Order_DayOfWeek"
]

feature_columns = (
    categorical_features +
    numeric_features
)

target_column = "Slow_Shipment"

X_train = train_df[feature_columns].copy()
X_test = test_df[feature_columns].copy()

y_train = train_df[target_column].copy()
y_test = test_df[target_column].copy()


# ------------------------------------------------------------
# 10. LEAKAGE CHECK
# ------------------------------------------------------------

forbidden_columns = [
    "Ship Date",
    "Delivery_Days",
    "Slow_Shipment"
]

leakage_columns = [
    col for col in forbidden_columns
    if col in feature_columns
]

if leakage_columns:
    raise ValueError(
        f"Data leakage detected in features: {leakage_columns}"
    )

print(f"✓ ML features: {len(feature_columns)}")
print(f"✓ Leakage columns detected: {leakage_columns}")


# ------------------------------------------------------------
# 11. TARGET VALIDATION
# ------------------------------------------------------------

if y_train.nunique() != 2:
    raise ValueError(
        "Training target does not contain both classes."
    )

if y_test.nunique() != 2:
    raise ValueError(
        "Testing target does not contain both classes."
    )

print(
    f"✓ Train target classes: "
    f"{sorted(y_train.unique().tolist())}"
)

print(
    f"✓ Test target classes: "
    f"{sorted(y_test.unique().tolist())}"
)


# ------------------------------------------------------------
# 12. ONE-HOT ENCODER COMPATIBILITY
# ------------------------------------------------------------

import inspect

ohe_parameters = {
    "handle_unknown": "ignore"
}

if "sparse_output" in inspect.signature(
    OneHotEncoder
).parameters:

    ohe_parameters["sparse_output"] = False

else:

    ohe_parameters["sparse"] = False


# ------------------------------------------------------------
# 13. PREPROCESSING PIPELINES
# ------------------------------------------------------------

numeric_transformer_scaled = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        ),
        (
            "scaler",
            StandardScaler()
        )
    ]
)

numeric_transformer_tree = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        )
    ]
)

categorical_transformer = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="most_frequent")
        ),
        (
            "onehot",
            OneHotEncoder(**ohe_parameters)
        )
    ]
)


# ------------------------------------------------------------
# 14. LOGISTIC REGRESSION PREPROCESSOR
# ------------------------------------------------------------

preprocessor_logistic = ColumnTransformer(
    transformers=[
        (
            "num",
            numeric_transformer_scaled,
            numeric_features
        ),
        (
            "cat",
            categorical_transformer,
            categorical_features
        )
    ],
    remainder="drop"
)


# ------------------------------------------------------------
# 15. TREE MODEL PREPROCESSOR
# ------------------------------------------------------------

preprocessor_tree = ColumnTransformer(
    transformers=[
        (
            "num",
            numeric_transformer_tree,
            numeric_features
        ),
        (
            "cat",
            categorical_transformer,
            categorical_features
        )
    ],
    remainder="drop"
)


# ------------------------------------------------------------
# 16. DEFINE MODELS
# ------------------------------------------------------------

models = {

    "Logistic Regression": Pipeline(
        steps=[
            (
                "preprocessor",
                preprocessor_logistic
            ),
            (
                "model",
                LogisticRegression(
                    max_iter=2000,
                    class_weight="balanced",
                    random_state=42
                )
            )
        ]
    ),

    "Random Forest": Pipeline(
        steps=[
            (
                "preprocessor",
                preprocessor_tree
            ),
            (
                "model",
                RandomForestClassifier(
                    n_estimators=300,
                    max_depth=None,
                    min_samples_split=5,
                    min_samples_leaf=2,
                    class_weight="balanced",
                    random_state=42,
                    n_jobs=-1
                )
            )
        ]
    ),

    "Gradient Boosting": Pipeline(
        steps=[
            (
                "preprocessor",
                preprocessor_tree
            ),
            (
                "model",
                GradientBoostingClassifier(
                    n_estimators=200,
                    learning_rate=0.05,
                    max_depth=3,
                    random_state=42
                )
            )
        ]
    )
}


# ------------------------------------------------------------
# 17. TRAIN + EVALUATE MODELS
# ------------------------------------------------------------

results = []
confusion_matrices = {}

for model_name, model in models.items():

    print("\n" + "-" * 70)
    print(f"TRAINING: {model_name}")
    print("-" * 70)

    # Train ONLY on training data
    model.fit(X_train, y_train)

    # Predictions on unseen test data
    y_pred = model.predict(X_test)

    # Probability for ROC-AUC
    y_prob = model.predict_proba(X_test)[:, 1]

    accuracy = accuracy_score(
        y_test,
        y_pred
    )

    precision = precision_score(
        y_test,
        y_pred,
        zero_division=0
    )

    recall = recall_score(
        y_test,
        y_pred,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        y_pred,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        y_prob
    )

    cm = confusion_matrix(
        y_test,
        y_pred
    )

    confusion_matrices[model_name] = cm

    results.append({
        "Model": model_name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1_Score": f1,
        "ROC_AUC": roc_auc
    })

    print(f"Accuracy : {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall   : {recall:.4f}")
    print(f"F1 Score : {f1:.4f}")
    print(f"ROC-AUC  : {roc_auc:.4f}")

    print("\nConfusion Matrix:")
    print(cm)


# ------------------------------------------------------------
# 18. MODEL COMPARISON
# ------------------------------------------------------------

results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by="ROC_AUC",
    ascending=False
).reset_index(drop=True)

print("\n" + "=" * 70)
print("MODEL COMPARISON")
print("=" * 70)

print(
    results_df.to_string(
        index=False,
        formatters={
            "Accuracy": "{:.4f}".format,
            "Precision": "{:.4f}".format,
            "Recall": "{:.4f}".format,
            "F1_Score": "{:.4f}".format,
            "ROC_AUC": "{:.4f}".format
        }
    )
)


# ------------------------------------------------------------
# 19. BEST MODEL
# ------------------------------------------------------------

best_model_name = results_df.iloc[0]["Model"]
best_model = models[best_model_name]

print("\n" + "=" * 70)
print("BEST MODEL")
print("=" * 70)

print(f"✓ Best model based on ROC-AUC: {best_model_name}")
print(
    f"✓ ROC-AUC: "
    f"{results_df.iloc[0]['ROC_AUC']:.4f}"
)


# ------------------------------------------------------------
# 20. FINAL VALIDATION
# ------------------------------------------------------------

assert len(X_train) == len(y_train)
assert len(X_test) == len(y_test)

assert len(order_overlap) == 0

assert not leakage_columns

assert len(results_df) == 3

assert results_df["ROC_AUC"].between(
    0,
    1
).all()

print("\n" + "=" * 70)
print("STATUS: STEP 25B COMPLETED SUCCESSFULLY")
print("=" * 70)

======================================================================
STEP 25B — ML MODEL TRAINING & EVALUATION
======================================================================
✓ Python environment: c:\Users\Krishna Prajapati\AppData\Local\Programs\Python\Python313\python.exe
✓ scikit-learn version: 1.9.0
✓ Dataset loaded: ../data/Nassau Candy Distributor.csv
✓ Records: 10,194
✓ Missing required columns: []
✓ Factory mapping validated
✓ Products: 15
✓ Factories: 5
✓ Unmapped rows: 0
✓ Dates parsed
✓ Delivery_Days calculated
✓ Order-level train/test split completed
✓ Train records: 8,132
✓ Test records: 2,062
✓ Train orders: 6,839
✓ Test orders: 1,710
✓ Order overlap: 0
✓ Train-only Q3 threshold: 1638 days
✓ Train slow shipments: 1,719
✓ Test slow shipments: 428
✓ ML features: 15
✓ Leakage columns detected: []
✓ Train target classes: [0, 1]
✓ Test target classes: [0, 1]

----------------------------------------------------------------------
TRAINING: Logistic Regression
----------------------------------------------------------------------
Accuracy : 0.7978
Precision: 0.5070
Recall   : 0.9322
F1 Score : 0.6568
ROC-AUC  : 0.8863

Confusion Matrix:
[[1246  388]
 [  29  399]]

----------------------------------------------------------------------
TRAINING: Random Forest
----------------------------------------------------------------------
Accuracy : 0.8235
Precision: 0.5457
Recall   : 0.8925
F1 Score : 0.6773
ROC-AUC  : 0.9013

Confusion Matrix:
[[1316  318]
 [  46  382]]

----------------------------------------------------------------------
TRAINING: Gradient Boosting
----------------------------------------------------------------------
Accuracy : 0.8346
Precision: 0.5868
Recall   : 0.6869
F1 Score : 0.6329
ROC-AUC  : 0.9043

Confusion Matrix:
[[1427  207]
 [ 134  294]]

======================================================================
MODEL COMPARISON
======================================================================
              Model Accuracy Precision Recall F1_Score ROC_AUC
  Gradient Boosting   0.8346    0.5868 0.6869   0.6329  0.9043
      Random Forest   0.8235    0.5457 0.8925   0.6773  0.9013
Logistic Regression   0.7978    0.5070 0.9322   0.6568  0.8863

======================================================================
BEST MODEL
======================================================================
✓ Best model based on ROC-AUC: Gradient Boosting
✓ ROC-AUC: 0.9043

======================================================================
STATUS: STEP 25B COMPLETED SUCCESSFULLY
======================================================================

In [7]:
# ============================================================
# STEP 25C — MODEL PERFORMANCE VERIFICATION
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 25C — MODEL PERFORMANCE VERIFICATION")
print("=" * 70)

# ------------------------------------------------------------
# 1. VERIFY STEP 25B OBJECTS
# ------------------------------------------------------------

required_objects = [
    "results_df",
    "confusion_matrices",
    "models",
    "best_model_name",
    "best_model"
]

missing_objects = [
    obj for obj in required_objects
    if obj not in globals()
]

if missing_objects:
    raise RuntimeError(
        "STEP 25B objects are missing: "
        + str(missing_objects)
        + "\nPlease run STEP 25B successfully before STEP 25C."
    )

print("✓ STEP 25B model objects found")


# ------------------------------------------------------------
# 2. VERIFY MODEL COUNT
# ------------------------------------------------------------

expected_models = [
    "Logistic Regression",
    "Random Forest",
    "Gradient Boosting"
]

actual_models = list(results_df["Model"])

missing_models = [
    model for model in expected_models
    if model not in actual_models
]

if missing_models:
    raise ValueError(
        f"Missing expected models: {missing_models}"
    )

print(f"✓ Models evaluated: {len(actual_models)}")


# ------------------------------------------------------------
# 3. DISPLAY MODEL PERFORMANCE
# ------------------------------------------------------------

performance_columns = [
    "Model",
    "Accuracy",
    "Precision",
    "Recall",
    "F1_Score",
    "ROC_AUC"
]

performance_df = results_df[
    performance_columns
].copy()

print("\n" + "=" * 70)
print("MODEL PERFORMANCE")
print("=" * 70)

print(
    performance_df.to_string(
        index=False,
        formatters={
            "Accuracy": "{:.4f}".format,
            "Precision": "{:.4f}".format,
            "Recall": "{:.4f}".format,
            "F1_Score": "{:.4f}".format,
            "ROC_AUC": "{:.4f}".format
        }
    )
)


# ------------------------------------------------------------
# 4. CONFUSION MATRICES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CONFUSION MATRICES")
print("=" * 70)

for model_name in expected_models:

    if model_name not in confusion_matrices:
        raise ValueError(
            f"Confusion matrix missing for {model_name}"
        )

    cm = np.asarray(
        confusion_matrices[model_name]
    )

    if cm.shape != (2, 2):
        raise ValueError(
            f"Invalid confusion matrix shape for "
            f"{model_name}: {cm.shape}"
        )

    print(f"\n{model_name}")
    print("-" * 40)

    print(
        pd.DataFrame(
            cm,
            index=[
                "Actual 0 (Normal)",
                "Actual 1 (Slow)"
            ],
            columns=[
                "Predicted 0 (Normal)",
                "Predicted 1 (Slow)"
            ]
        ).to_string()
    )


# ------------------------------------------------------------
# 5. BEST MODEL VERIFICATION
# ------------------------------------------------------------

calculated_best_model = (
    performance_df
    .sort_values(
        by="ROC_AUC",
        ascending=False
    )
    .iloc[0]["Model"]
)

if best_model_name != calculated_best_model:
    raise ValueError(
        "Best model mismatch detected."
    )

best_row = performance_df[
    performance_df["Model"] == best_model_name
].iloc[0]

print("\n" + "=" * 70)
print("SELECTED BEST MODEL")
print("=" * 70)

print(f"✓ Best Model : {best_model_name}")
print(f"✓ Accuracy   : {best_row['Accuracy']:.4f}")
print(f"✓ Precision  : {best_row['Precision']:.4f}")
print(f"✓ Recall     : {best_row['Recall']:.4f}")
print(f"✓ F1 Score   : {best_row['F1_Score']:.4f}")
print(f"✓ ROC-AUC    : {best_row['ROC_AUC']:.4f}")


# ------------------------------------------------------------
# 6. FINAL VALIDATION
# ------------------------------------------------------------

assert len(performance_df) == 3

assert performance_df[
    ["Accuracy", "Precision", "Recall", "F1_Score", "ROC_AUC"]
].apply(
    lambda column: column.between(0, 1).all()
).all()

assert best_model_name in expected_models

print("\n" + "=" * 70)
print("STATUS: STEP 25C COMPLETED SUCCESSFULLY")
print("=" * 70)

======================================================================
STEP 25C — MODEL PERFORMANCE VERIFICATION
======================================================================
✓ STEP 25B model objects found
✓ Models evaluated: 3

======================================================================
MODEL PERFORMANCE
======================================================================
              Model Accuracy Precision Recall F1_Score ROC_AUC
  Gradient Boosting   0.8346    0.5868 0.6869   0.6329  0.9043
      Random Forest   0.8235    0.5457 0.8925   0.6773  0.9013
Logistic Regression   0.7978    0.5070 0.9322   0.6568  0.8863

======================================================================
CONFUSION MATRICES
======================================================================

Logistic Regression
----------------------------------------
                   Predicted 0 (Normal)  Predicted 1 (Slow)
Actual 0 (Normal)                  1246                 388
Actual 1 (Slow)                      29                 399

Random Forest
----------------------------------------
                   Predicted 0 (Normal)  Predicted 1 (Slow)
Actual 0 (Normal)                  1316                 318
Actual 1 (Slow)                      46                 382

Gradient Boosting
----------------------------------------
                   Predicted 0 (Normal)  Predicted 1 (Slow)
Actual 0 (Normal)                  1427                 207
Actual 1 (Slow)                     134                 294

======================================================================
SELECTED BEST MODEL
======================================================================
✓ Best Model : Gradient Boosting
✓ Accuracy   : 0.8346
✓ Precision  : 0.5868
✓ Recall     : 0.6869
✓ F1 Score   : 0.6329
✓ ROC-AUC    : 0.9043

======================================================================
STATUS: STEP 25C COMPLETED SUCCESSFULLY
======================================================================

In [8]:
# ============================================================
# STEP 25D — BUSINESS-ORIENTED MODEL SELECTION & MODEL SAVING
# ============================================================

import os
import sys
import json
import subprocess
from pathlib import Path

print("=" * 70)
print("STEP 25D — MODEL SELECTION & MODEL SAVING")
print("=" * 70)

# ------------------------------------------------------------
# 1. CHECK REQUIRED OBJECTS FROM STEP 25B
# ------------------------------------------------------------

required_objects = [
    "results_df",
    "models",
    "confusion_matrices"
]

missing_objects = [
    obj for obj in required_objects
    if obj not in globals()
]

if missing_objects:
    raise RuntimeError(
        f"Missing required Step 25B objects: {missing_objects}. "
        "Please run Step 25B again before Step 25D."
    )

print("✓ Step 25B objects found")

# ------------------------------------------------------------
# 2. VERIFY EXPECTED MODELS
# ------------------------------------------------------------

expected_models = {
    "Gradient Boosting",
    "Random Forest",
    "Logistic Regression"
}

available_models = set(models.keys())

missing_models = expected_models - available_models

if missing_models:
    raise RuntimeError(
        f"Missing trained models: {sorted(missing_models)}"
    )

print("✓ All 3 trained models are available")

# ------------------------------------------------------------
# 3. VERIFY REQUIRED METRICS
# ------------------------------------------------------------

required_metrics = {
    "Model",
    "Accuracy",
    "Precision",
    "Recall",
    "F1_Score",
    "ROC_AUC"
}

missing_metrics = required_metrics - set(results_df.columns)

if missing_metrics:
    raise RuntimeError(
        f"Missing required metric columns: {sorted(missing_metrics)}"
    )

# Create clean comparison table
model_comparison = results_df.copy()

# Ensure numeric metrics
metric_columns = [
    "Accuracy",
    "Precision",
    "Recall",
    "F1_Score",
    "ROC_AUC"
]

for col in metric_columns:
    model_comparison[col] = pd.to_numeric(
        model_comparison[col],
        errors="raise"
    )

print("✓ Model metrics verified")

# ------------------------------------------------------------
# 4. BUSINESS-ORIENTED MODEL SELECTION
# ------------------------------------------------------------
#
# Business objective:
# Detect as many SLOW shipments as possible while
# maintaining a reasonable balance between precision
# and recall.
#
# Selection hierarchy:
#   1. F1 Score  -> balance Precision and Recall
#   2. Recall    -> minimize missed slow shipments
#   3. ROC-AUC   -> overall ranking/discrimination
#
# ------------------------------------------------------------

selection_table = model_comparison.sort_values(
    by=["F1_Score", "Recall", "ROC_AUC"],
    ascending=[False, False, False]
).reset_index(drop=True)

selected_model_name = selection_table.loc[0, "Model"]
selected_model = models[selected_model_name]

print("\n" + "=" * 70)
print("MODEL SELECTION")
print("=" * 70)

print(selection_table[
    [
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1_Score",
        "ROC_AUC"
    ]
].to_string(index=False))

print("\n✓ Selected operational model:", selected_model_name)

# ------------------------------------------------------------
# 5. BUSINESS SELECTION VALIDATION
# ------------------------------------------------------------

selected_row = selection_table.iloc[0]

print("\nSelected Model Performance:")
print(f"  Accuracy : {selected_row['Accuracy']:.4f}")
print(f"  Precision: {selected_row['Precision']:.4f}")
print(f"  Recall   : {selected_row['Recall']:.4f}")
print(f"  F1 Score : {selected_row['F1_Score']:.4f}")
print(f"  ROC-AUC  : {selected_row['ROC_AUC']:.4f}")

# ------------------------------------------------------------
# 6. CREATE MODELS DIRECTORY
# ------------------------------------------------------------

cwd = Path.cwd()

if cwd.name.lower() == "notebooks":
    project_root = cwd.parent
else:
    project_root = cwd

models_dir = project_root / "models"
models_dir.mkdir(parents=True, exist_ok=True)

print("\n✓ Models directory:", models_dir)

# ------------------------------------------------------------
# 7. INSTALL / VERIFY JOBLIB
# ------------------------------------------------------------

try:
    import joblib
except ImportError:
    print("Installing joblib...")
    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", "joblib", "-q"]
    )
    import joblib

print("✓ joblib available")

# ------------------------------------------------------------
# 8. SAVE SELECTED MODEL
# ------------------------------------------------------------

model_path = models_dir / "nassau_slow_shipment_model.joblib"

joblib.dump(
    selected_model,
    model_path
)

if not model_path.exists():
    raise RuntimeError(
        "Model file was not created successfully."
    )

print("✓ Model saved successfully")
print("  File:", model_path)

# ------------------------------------------------------------
# 9. SAVE MODEL METADATA
# ------------------------------------------------------------

metadata = {
    "project": "Factory Reallocation & Shipping Optimization Recommendation System",
    "task": "Slow Shipment Classification",
    "selected_model": selected_model_name,
    "selection_strategy": {
        "primary_metric": "F1_Score",
        "secondary_metric": "Recall",
        "tertiary_metric": "ROC_AUC"
    },
    "metrics": {
        "Accuracy": float(selected_row["Accuracy"]),
        "Precision": float(selected_row["Precision"]),
        "Recall": float(selected_row["Recall"]),
        "F1_Score": float(selected_row["F1_Score"]),
        "ROC_AUC": float(selected_row["ROC_AUC"])
    },
    "models_evaluated": [
        "Gradient Boosting",
        "Random Forest",
        "Logistic Regression"
    ],
    "target": "Slow_Shipment",
    "model_file": model_path.name
}

metadata_path = models_dir / "nassau_slow_shipment_model_metadata.json"

with open(metadata_path, "w", encoding="utf-8") as f:
    json.dump(
        metadata,
        f,
        indent=4
    )

print("✓ Metadata saved successfully")
print("  File:", metadata_path)

# ------------------------------------------------------------
# 10. RELOAD MODEL — IMPORTANT VALIDATION
# ------------------------------------------------------------

loaded_model = joblib.load(model_path)

if loaded_model is None:
    raise RuntimeError(
        "Saved model could not be loaded."
    )

print("✓ Saved model loaded successfully")

# ------------------------------------------------------------
# 11. VERIFY MODEL TYPE
# ------------------------------------------------------------

if type(loaded_model) is not type(selected_model):
    raise RuntimeError(
        "Loaded model type does not match selected model type."
    )

print("✓ Loaded model type matches selected model")

# ------------------------------------------------------------
# 12. VERIFY PREDICTION CONSISTENCY
# ------------------------------------------------------------

if "X_test" not in globals():
    raise RuntimeError(
        "X_test is missing from Step 25B."
    )

original_predictions = selected_model.predict(X_test)
loaded_predictions = loaded_model.predict(X_test)

if not (original_predictions == loaded_predictions).all():
    raise RuntimeError(
        "Prediction mismatch between original and saved model."
    )

print("✓ Prediction consistency verified")

# ------------------------------------------------------------
# 13. FINAL STATUS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STATUS: STEP 25D COMPLETED SUCCESSFULLY")
print("=" * 70)

print(f"Operational Model : {selected_model_name}")
print(f"F1 Score          : {selected_row['F1_Score']:.4f}")
print(f"Recall            : {selected_row['Recall']:.4f}")
print(f"ROC-AUC           : {selected_row['ROC_AUC']:.4f}")
print(f"Model File        : {model_path.name}")
print(f"Metadata File     : {metadata_path.name}")
print("=" * 70)

======================================================================
STEP 25D — MODEL SELECTION & MODEL SAVING
======================================================================
✓ Step 25B objects found
✓ All 3 trained models are available
✓ Model metrics verified

======================================================================
MODEL SELECTION
======================================================================
              Model  Accuracy  Precision   Recall  F1_Score  ROC_AUC
      Random Forest  0.823472   0.545714 0.892523  0.677305 0.901339
Logistic Regression  0.797769   0.506989 0.932243  0.656790 0.886251
  Gradient Boosting  0.834627   0.586826 0.686916  0.632939 0.904320

✓ Selected operational model: Random Forest

Selected Model Performance:
  Accuracy : 0.8235
  Precision: 0.5457
  Recall   : 0.8925
  F1 Score : 0.6773
  ROC-AUC  : 0.9013

✓ Models directory: c:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization\models
✓ joblib available
✓ Model saved successfully
  File: c:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization\models\nassau_slow_shipment_model.joblib
✓ Metadata saved successfully
  File: c:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization\models\nassau_slow_shipment_model_metadata.json
✓ Saved model loaded successfully
✓ Loaded model type matches selected model
✓ Prediction consistency verified

======================================================================
STATUS: STEP 25D COMPLETED SUCCESSFULLY
======================================================================
Operational Model : Random Forest
F1 Score          : 0.6773
Recall            : 0.8925
ROC-AUC           : 0.9013
Model File        : nassau_slow_shipment_model.joblib
Metadata File     : nassau_slow_shipment_model_metadata.json
======================================================================

In [9]:
# ============================================================
# STEP 26A — FACTORY REALLOCATION SCENARIO ENGINE
# ============================================================

import os
import re
import sys
import subprocess
import unicodedata
from pathlib import Path

import numpy as np
import pandas as pd

print("=" * 75)
print("STEP 26A — FACTORY REALLOCATION SCENARIO ENGINE")
print("=" * 75)

# ------------------------------------------------------------
# 1. PROJECT PATHS
# ------------------------------------------------------------

cwd = Path.cwd()

if cwd.name.lower() == "notebooks":
    project_root = cwd.parent
else:
    project_root = cwd

data_path = project_root / "data" / "Nassau Candy Distributor.csv"
models_dir = project_root / "models"
model_path = models_dir / "nassau_slow_shipment_model.joblib"

if not data_path.exists():
    raise FileNotFoundError(
        f"Dataset not found:\n{data_path}"
    )

if not model_path.exists():
    raise FileNotFoundError(
        f"Saved model not found:\n{model_path}\n"
        "Please complete Step 25D first."
    )

print("✓ Project root:", project_root)
print("✓ Dataset found")
print("✓ Saved model found")

# ------------------------------------------------------------
# 2. LOAD SAVED MODEL
# ------------------------------------------------------------

try:
    import joblib
except ImportError:
    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", "joblib", "-q"]
    )
    import joblib

scenario_model = joblib.load(model_path)

if scenario_model is None:
    raise RuntimeError(
        "Saved model could not be loaded."
    )

print("✓ Random Forest model loaded")

# ------------------------------------------------------------
# 3. LOAD RAW DATA
# ------------------------------------------------------------

raw_df = pd.read_csv(data_path)

if raw_df.empty:
    raise RuntimeError("Dataset is empty.")

print("✓ Dataset loaded")
print("  Records:", len(raw_df))
print("  Columns:", len(raw_df.columns))

# ------------------------------------------------------------
# 4. REQUIRED RAW COLUMNS
# ------------------------------------------------------------

required_raw_columns = [
    "Order ID",
    "Order Date",
    "Ship Date",
    "Ship Mode",
    "Customer ID",
    "Country/Region",
    "State/Province",
    "Region",
    "Product Name",
    "Division",
    "Units",
    "Sales",
    "Cost",
    "Gross Profit"
]

missing_raw_columns = [
    col for col in required_raw_columns
    if col not in raw_df.columns
]

if missing_raw_columns:
    raise RuntimeError(
        f"Missing raw columns: {missing_raw_columns}"
    )

print("✓ Required raw columns verified")

# ------------------------------------------------------------
# 5. PRODUCT NAME CANONICALIZATION
# ------------------------------------------------------------

def canonical_product_name(value):
    if pd.isna(value):
        return ""

    text = str(value)

    text = unicodedata.normalize(
        "NFKC",
        text
    )

    text = text.replace(
        "\u00A0",
        " "
    )

    text = text.strip()

    text = re.sub(
        r"\s*-\s*",
        " - ",
        text
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text

# ------------------------------------------------------------
# 6. VALIDATED PRODUCT → FACTORY MAPPING
# ------------------------------------------------------------

product_to_factory = {

    # Lot's O' Nuts
    "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
    "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
    "Wonka Bar - Scrumdiddlyumptious": "Lot's O' Nuts",

    # Wicked Choccy's
    "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
    "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",

    # Sugar Shack
    "Laffy Taffy": "Sugar Shack",
    "SweeTARTS": "Sugar Shack",
    "Nerds": "Sugar Shack",
    "Fun Dip": "Sugar Shack",
    "Fizzy Lifting Drinks": "Sugar Shack",

    # Secret Factory
    "Everlasting Gobstopper": "Secret Factory",
    "Lickable Wallpaper": "Secret Factory",
    "Wonka Gum": "Secret Factory",

    # The Other Factory
    "Hair Toffee": "The Other Factory",
    "Kazookles": "The Other Factory"
}

# Normalize mapping keys
normalized_product_to_factory = {
    canonical_product_name(product): factory
    for product, factory in product_to_factory.items()
}

raw_df["_Product_Key"] = raw_df["Product Name"].apply(
    canonical_product_name
)

raw_df["Factory"] = raw_df["_Product_Key"].map(
    normalized_product_to_factory
)

# ------------------------------------------------------------
# 7. FACTORY MAPPING VALIDATION
# ------------------------------------------------------------

unmapped_rows = int(
    raw_df["Factory"].isna().sum()
)

if unmapped_rows != 0:
    unmapped_products = sorted(
        raw_df.loc[
            raw_df["Factory"].isna(),
            "Product Name"
        ].astype(str).unique()
    )

    raise RuntimeError(
        "Factory mapping failed.\n"
        f"Unmapped rows: {unmapped_rows}\n"
        f"Unmapped products: {unmapped_products}"
    )

factories = sorted(
    raw_df["Factory"].dropna().unique().tolist()
)

if len(factories) != 5:
    raise RuntimeError(
        f"Expected 5 factories, found {len(factories)}: {factories}"
    )

product_count = raw_df["Product Name"].nunique()

if product_count != 15:
    raise RuntimeError(
        f"Expected 15 products, found {product_count}"
    )

print("✓ Factory mapping validated")
print("  Products :", product_count)
print("  Factories:", len(factories))
print("  Unmapped :", unmapped_rows)

# ------------------------------------------------------------
# 8. DATE FEATURES
# ------------------------------------------------------------

raw_df["Order Date"] = pd.to_datetime(
    raw_df["Order Date"],
    format="%d-%m-%Y",
    errors="raise"
)

raw_df["Ship Date"] = pd.to_datetime(
    raw_df["Ship Date"],
    format="%d-%m-%Y",
    errors="raise"
)

delivery_days = (
    raw_df["Ship Date"] -
    raw_df["Order Date"]
).dt.days

if delivery_days.isna().any():
    raise RuntimeError(
        "Delivery_Days contains missing values."
    )

if (delivery_days < 0).any():
    raise RuntimeError(
        "Negative Delivery_Days detected."
    )

raw_df["Delivery_Days"] = delivery_days

raw_df["Order_Year"] = raw_df["Order Date"].dt.year
raw_df["Order_Month"] = raw_df["Order Date"].dt.month
raw_df["Order_Quarter"] = raw_df["Order Date"].dt.quarter
raw_df["Order_DayOfWeek"] = raw_df["Order Date"].dt.dayofweek

print("✓ Date features recreated")

# ------------------------------------------------------------
# 9. MODEL FEATURE DEFINITION
# ------------------------------------------------------------

feature_columns = [
    "Product Name",
    "Division",
    "Country/Region",
    "State/Province",
    "Region",
    "Factory",
    "Ship Mode",
    "Units",
    "Sales",
    "Cost",
    "Gross Profit",
    "Order_Year",
    "Order_Month",
    "Order_Quarter",
    "Order_DayOfWeek"
]

missing_features = [
    col for col in feature_columns
    if col not in raw_df.columns
]

if missing_features:
    raise RuntimeError(
        f"Missing model features: {missing_features}"
    )

# ------------------------------------------------------------
# 10. BUILD BASE FEATURE DATASET
# ------------------------------------------------------------

base_features = raw_df[
    feature_columns
].copy()

if base_features.isna().any().any():
    missing_feature_counts = (
        base_features.isna().sum()
    )

    raise RuntimeError(
        "Missing values detected in model features:\n"
        f"{missing_feature_counts[missing_feature_counts > 0]}"
    )

print("✓ Model feature dataset created")
print("  Features:", len(feature_columns))

# ------------------------------------------------------------
# 11. CURRENT FACTORY BASELINE
# ------------------------------------------------------------

current_factory_by_product = (
    raw_df[
        ["Product Name", "Factory"]
    ]
    .drop_duplicates()
)

factory_counts_per_product = (
    current_factory_by_product
    .groupby("Product Name")["Factory"]
    .nunique()
)

if (factory_counts_per_product != 1).any():
    problematic_products = (
        factory_counts_per_product[
            factory_counts_per_product != 1
        ]
    )

    raise RuntimeError(
        "Some products have multiple current factories:\n"
        f"{problematic_products}"
    )

print("✓ Current factory baseline validated")

# ------------------------------------------------------------
# 12. GENERATE COUNTERFACTUAL SCENARIOS
# ------------------------------------------------------------
#
# For every product:
#   Current Factory
#   Alternative Factory 1
#   Alternative Factory 2
#   ...
#
# All other operational features remain unchanged.
#
# This is scenario analysis, not causal inference.
# ------------------------------------------------------------

scenario_results = []

unique_products = sorted(
    raw_df["Product Name"].dropna().unique()
)

for product in unique_products:

    product_mask = (
        raw_df["Product Name"] == product
    )

    product_data = base_features.loc[
        product_mask
    ].copy()

    current_factory = (
        raw_df.loc[
            product_mask,
            "Factory"
        ]
        .iloc[0]
    )

    for scenario_factory in factories:

        scenario_data = product_data.copy()

        scenario_data["Factory"] = scenario_factory

        # Predict probability of Slow Shipment = class 1
        probabilities = scenario_model.predict_proba(
            scenario_data
        )[:, 1]

        predictions = scenario_model.predict(
            scenario_data
        )

        scenario_results.append({
            "Product Name": product,
            "Current Factory": current_factory,
            "Scenario Factory": scenario_factory,
            "Records Scored": len(scenario_data),
            "Predicted Slow Probability": float(
                np.mean(probabilities)
            ),
            "Predicted Slow Rate": float(
                np.mean(predictions)
            )
        })

scenario_df = pd.DataFrame(
    scenario_results
)

# ------------------------------------------------------------
# 13. VALIDATE SCENARIO DATASET
# ------------------------------------------------------------

expected_rows = (
    len(unique_products) *
    len(factories)
)

if len(scenario_df) != expected_rows:
    raise RuntimeError(
        f"Expected {expected_rows} scenario rows, "
        f"found {len(scenario_df)}."
    )

if scenario_df["Predicted Slow Probability"].isna().any():
    raise RuntimeError(
        "Scenario predictions contain missing values."
    )

if not (
    scenario_df["Predicted Slow Probability"]
    .between(0, 1)
    .all()
):
    raise RuntimeError(
        "Predicted probabilities outside [0, 1]."
    )

print("✓ Scenario predictions generated")
print("  Products :", len(unique_products))
print("  Factories:", len(factories))
print("  Scenarios:", len(scenario_df))

# ------------------------------------------------------------
# 14. CURRENT FACTORY BASELINE PROBABILITY
# ------------------------------------------------------------

current_baseline = (
    scenario_df[
        scenario_df["Scenario Factory"]
        ==
        scenario_df["Current Factory"]
    ]
    [
        [
            "Product Name",
            "Current Factory",
            "Predicted Slow Probability"
        ]
    ]
    .rename(
        columns={
            "Predicted Slow Probability":
            "Current Slow Probability"
        }
    )
)

# ------------------------------------------------------------
# 15. CALCULATE REALLOCATION IMPROVEMENT
# ------------------------------------------------------------

scenario_df = scenario_df.merge(
    current_baseline,
    on=[
        "Product Name",
        "Current Factory"
    ],
    how="left",
    validate="many_to_one"
)

scenario_df["Probability Reduction"] = (
    scenario_df["Current Slow Probability"]
    -
    scenario_df["Predicted Slow Probability"]
)

scenario_df["Improvement_Percentage_Points"] = (
    scenario_df["Probability Reduction"] * 100
)

scenario_df["Is_Current_Factory"] = (
    scenario_df["Scenario Factory"]
    ==
    scenario_df["Current Factory"]
)

# ------------------------------------------------------------
# 16. ALTERNATIVE FACTORY RECOMMENDATION
# ------------------------------------------------------------

alternative_scenarios = (
    scenario_df[
        ~scenario_df["Is_Current_Factory"]
    ]
    .copy()
)

best_alternatives = (
    alternative_scenarios
    .sort_values(
        [
            "Product Name",
            "Probability Reduction",
            "Predicted Slow Probability"
        ],
        ascending=[
            True,
            False,
            True
        ]
    )
    .groupby(
        "Product Name",
        as_index=False
    )
    .head(1)
    .reset_index(drop=True)
)

# ------------------------------------------------------------
# 17. ADD RECOMMENDATION STATUS
# ------------------------------------------------------------
#
# We use a conservative screening threshold:
# at least 5 percentage-point reduction in predicted
# slow-shipment probability.
#
# This is NOT a causal threshold. It is only a
# scenario-screening rule.
# ------------------------------------------------------------

recommendation_threshold = 0.05

best_alternatives["Recommendation"] = np.where(
    best_alternatives["Probability Reduction"]
    >= recommendation_threshold,
    "CONSIDER REALLOCATION",
    "NO STRONG ML SIGNAL"
)

# ------------------------------------------------------------
# 18. FINAL RECOMMENDATION TABLE
# ------------------------------------------------------------

recommendation_columns = [
    "Product Name",
    "Current Factory",
    "Scenario Factory",
    "Current Slow Probability",
    "Predicted Slow Probability",
    "Probability Reduction",
    "Improvement_Percentage_Points",
    "Recommendation"
]

recommendation_df = (
    best_alternatives[
        recommendation_columns
    ]
    .sort_values(
        "Probability Reduction",
        ascending=False
    )
    .reset_index(drop=True)
)

# ------------------------------------------------------------
# 19. SAVE RESULTS
# ------------------------------------------------------------

results_dir = project_root / "results"
results_dir.mkdir(
    parents=True,
    exist_ok=True
)

scenario_path = (
    results_dir /
    "factory_reallocation_scenarios.csv"
)

recommendation_path = (
    results_dir /
    "factory_reallocation_recommendations.csv"
)

scenario_df.to_csv(
    scenario_path,
    index=False
)

recommendation_df.to_csv(
    recommendation_path,
    index=False
)

# ------------------------------------------------------------
# 20. DISPLAY RESULTS
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("TOP FACTORY REALLOCATION SCENARIOS")
print("=" * 75)

display(
    recommendation_df[
        [
            "Product Name",
            "Current Factory",
            "Scenario Factory",
            "Current Slow Probability",
            "Predicted Slow Probability",
            "Improvement_Percentage_Points",
            "Recommendation"
        ]
    ].head(15)
)

# ------------------------------------------------------------
# 21. FINAL VALIDATION
# ------------------------------------------------------------

if recommendation_df["Product Name"].nunique() != 15:
    raise RuntimeError(
        "Expected one best alternative for each of 15 products."
    )

if recommendation_df["Scenario Factory"].isna().any():
    raise RuntimeError(
        "Missing recommended scenario factory."
    )

if (
    recommendation_df["Scenario Factory"]
    ==
    recommendation_df["Current Factory"]
).any():
    raise RuntimeError(
        "Current factory incorrectly selected as alternative."
    )

print("\n" + "=" * 75)
print("STATUS: STEP 26A COMPLETED SUCCESSFULLY")
print("=" * 75)

print("Total products evaluated :", len(unique_products))
print("Factories evaluated      :", len(factories))
print("Scenario combinations    :", len(scenario_df))
print("Recommendations generated:", len(recommendation_df))
print("Scenario file            :", scenario_path.name)
print("Recommendation file      :", recommendation_path.name)

print("\nIMPORTANT:")
print("These are ML-based counterfactual scenario recommendations.")
print("They are NOT causal estimates and do NOT use invented factory coordinates.")

print("=" * 75)

===========================================================================
STEP 26A — FACTORY REALLOCATION SCENARIO ENGINE
===========================================================================
✓ Project root: c:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization
✓ Dataset found
✓ Saved model found
✓ Random Forest model loaded
✓ Dataset loaded
  Records: 10194
  Columns: 18
✓ Required raw columns verified
✓ Factory mapping validated
  Products : 15
  Factories: 5
  Unmapped : 0
✓ Date features recreated
✓ Model feature dataset created
  Features: 15
✓ Current factory baseline validated
✓ Scenario predictions generated
  Products : 15
  Factories: 5
  Scenarios: 75

===========================================================================
TOP FACTORY REALLOCATION SCENARIOS
===========================================================================

,Product Name,Current Factory,Scenario Factory,Current Slow Probability,Predicted Slow Probability,Improvement_Percentage_Points,Recommendation
0,Everlasting Gobstopper,Secret Factory,The Other Factory,0.524733,0.498854,2.587866,NO STRONG ML SIGNAL
1,Fizzy Lifting Drinks,Sugar Shack,The Other Factory,0.292623,0.278194,1.442872,NO STRONG ML SIGNAL
2,Laffy Taffy,Sugar Shack,The Other Factory,0.366585,0.352903,1.368241,NO STRONG ML SIGNAL
3,Lickable Wallpaper,Secret Factory,The Other Factory,0.345119,0.332885,1.223438,NO STRONG ML SIGNAL
4,Wonka Gum,Secret Factory,The Other Factory,0.314837,0.302741,1.209590,NO STRONG ML SIGNAL
5,SweeTARTS,Sugar Shack,The Other Factory,0.459319,0.447265,1.205417,NO STRONG ML SIGNAL
6,Wonka Bar - Milk Chocolate,Wicked Choccy's,The Other Factory,0.329027,0.319269,0.975803,NO STRONG ML SIGNAL
7,Nerds,Sugar Shack,The Other Factory,0.486656,0.477404,0.925209,NO STRONG ML SIGNAL
8,Wonka Bar - Triple Dazzle Caramel,Wicked Choccy's,The Other Factory,0.316443,0.309277,0.716562,NO STRONG ML SIGNAL
9,Wonka Bar - Fudge Mallows,Lot's O' Nuts,The Other Factory,0.316155,0.309246,0.690892,NO STRONG ML SIGNAL
10,Wonka Bar - Nutty Crunch Surprise,Lot's O' Nuts,The Other Factory,0.325851,0.319331,0.651918,NO STRONG ML SIGNAL
11,Wonka Bar -Scrumdiddlyumptious,Lot's O' Nuts,The Other Factory,0.309408,0.303281,0.612666,NO STRONG ML SIGNAL
12,Hair Toffee,The Other Factory,Wicked Choccy's,0.369730,0.369431,0.029973,NO STRONG ML SIGNAL
13,Fun Dip,Sugar Shack,Lot's O' Nuts,0.444194,0.445932,-0.173814,NO STRONG ML SIGNAL
14,Kazookles,The Other Factory,Lot's O' Nuts,0.260536,0.268511,-0.797484,NO STRONG ML SIGNAL

===========================================================================
STATUS: STEP 26A COMPLETED SUCCESSFULLY
===========================================================================
Total products evaluated : 15
Factories evaluated      : 5
Scenario combinations    : 75
Recommendations generated: 15
Scenario file            : factory_reallocation_scenarios.csv
Recommendation file      : factory_reallocation_recommendations.csv

IMPORTANT:
These are ML-based counterfactual scenario recommendations.
They are NOT causal estimates and do NOT use invented factory coordinates.
===========================================================================

In [17]:
# ============================================================
# STEP 26B — FINAL FACTORY REALLOCATION RECOMMENDATIONS
# FINAL CLEAN VERSION
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 26B — FINAL FACTORY REALLOCATION RECOMMENDATIONS")
print("=" * 70)

# ------------------------------------------------------------
# 1. FIND PROJECT DIRECTORY
# ------------------------------------------------------------

cwd = Path.cwd()

possible_dirs = [
    cwd,
    cwd.parent,
    cwd.parent.parent
]

project_dir = None

for p in possible_dirs:
    if (p / "results").exists():
        project_dir = p
        break

if project_dir is None:
    raise FileNotFoundError(
        "Project results folder not found."
    )

results_dir = project_dir / "results"

recommendation_file = (
    results_dir / "factory_reallocation_recommendations.csv"
)

if not recommendation_file.exists():
    raise FileNotFoundError(
        f"Step 26A recommendation file not found:\n"
        f"{recommendation_file}"
    )

print("Project directory:", project_dir)
print("Loading Step 26A output...")

# ------------------------------------------------------------
# 2. LOAD STEP 26A OUTPUT
# ------------------------------------------------------------

rec = pd.read_csv(recommendation_file)

print("Records:", len(rec))
print("\nColumns found:")

for col in rec.columns:
    print(" -", col)

# ------------------------------------------------------------
# 3. CHECK ONLY THE ORIGINAL REQUIRED COLUMNS
# ------------------------------------------------------------

required = [
    "Product Name",
    "Current Factory",
    "Scenario Factory",
    "Current Slow Probability",
    "Predicted Slow Probability"
]

missing = [
    col for col in required
    if col not in rec.columns
]

if missing:
    raise ValueError(
        "Required Step 26A columns are missing:\n"
        + "\n".join(missing)
    )

print("\nSTEP 26A INPUT VALIDATION: PASSED")

# ------------------------------------------------------------
# 4. CONVERT PROBABILITY COLUMNS
# ------------------------------------------------------------

rec["Current Slow Probability"] = pd.to_numeric(
    rec["Current Slow Probability"],
    errors="coerce"
)

rec["Predicted Slow Probability"] = pd.to_numeric(
    rec["Predicted Slow Probability"],
    errors="coerce"
)

if rec[
    [
        "Current Slow Probability",
        "Predicted Slow Probability"
    ]
].isna().any().any():

    raise ValueError(
        "Invalid or missing probability values detected."
    )

# ------------------------------------------------------------
# 5. PROBABILITY RANGE CHECK
# ------------------------------------------------------------

if not rec["Current Slow Probability"].between(0, 1).all():
    raise ValueError(
        "Current Slow Probability contains values outside 0-1."
    )

if not rec["Predicted Slow Probability"].between(0, 1).all():
    raise ValueError(
        "Predicted Slow Probability contains values outside 0-1."
    )

print("Probability range validation: PASSED")

# ------------------------------------------------------------
# 6. IGNORE OLD PROBABILITY REDUCTION COLUMN
# ------------------------------------------------------------

# IMPORTANT:
# The old Step 26A derived "Probability Reduction" column
# is NOT used for validation or final calculation.
#
# We calculate it directly from the two source probabilities.

rec["Probability_Reduction_Percentage_Points"] = (
    rec["Current Slow Probability"]
    - rec["Predicted Slow Probability"]
) * 100

print(
    "Probability reduction recalculated "
    "from source probabilities."
)

# ------------------------------------------------------------
# 7. FACTORY VALIDATION
# ------------------------------------------------------------

if (
    rec["Current Factory"]
    == rec["Scenario Factory"]
).any():

    raise ValueError(
        "Current Factory and Scenario Factory cannot be identical."
    )

print("Factory scenario validation: PASSED")

# ------------------------------------------------------------
# 8. PRODUCT VALIDATION
# ------------------------------------------------------------

unique_products = rec["Product Name"].nunique()

print("Unique products:", unique_products)

if unique_products != 15:
    raise ValueError(
        f"Expected 15 products, found {unique_products}."
    )

print("Product validation: PASSED")

# ------------------------------------------------------------
# 9. LOAD RAW DATASET
# ------------------------------------------------------------

data_file = project_dir / "data" / "Nassau Candy Distributor.csv"

if not data_file.exists():

    alternate = project_dir.parent / "data" / "Nassau Candy Distributor.csv"

    if alternate.exists():
        data_file = alternate
    else:
        raise FileNotFoundError(
            "Nassau Candy Distributor.csv not found."
        )

df_raw = pd.read_csv(data_file)

print("\nRaw dataset records:", len(df_raw))

# ------------------------------------------------------------
# 10. PRODUCT BUSINESS METRICS
# ------------------------------------------------------------

business = (
    df_raw
    .groupby("Product Name")
    .agg(
        Records=("Product Name", "size"),
        Orders=("Order ID", "nunique"),
        Sales=("Sales", "sum"),
        Units=("Units", "sum"),
        Gross_Profit=("Gross Profit", "sum")
    )
    .reset_index()
)

# ------------------------------------------------------------
# 11. MERGE BUSINESS METRICS
# ------------------------------------------------------------

final_rec = rec.merge(
    business,
    on="Product Name",
    how="left",
    validate="one_to_one"
)

if final_rec[
    [
        "Records",
        "Orders",
        "Sales",
        "Units",
        "Gross_Profit"
    ]
].isna().any().any():

    raise ValueError(
        "Business metrics could not be matched "
        "for every product."
    )

print("Business metrics merge: PASSED")

# ------------------------------------------------------------
# 12. ML SIGNAL
# ------------------------------------------------------------

THRESHOLD = 5.0

final_rec["ML_Signal"] = np.where(
    final_rec[
        "Probability_Reduction_Percentage_Points"
    ] >= THRESHOLD,

    "CONSIDER REALLOCATION",

    "NO STRONG ML SIGNAL"
)

# ------------------------------------------------------------
# 13. ESTIMATED AVOIDED SLOW RECORDS
# ------------------------------------------------------------

final_rec["Estimated_Avoided_Slow_Records"] = (
    final_rec["Records"]
    *
    final_rec[
        "Probability_Reduction_Percentage_Points"
    ]
    / 100
)

# ------------------------------------------------------------
# 14. FINAL BUSINESS ACTION
# ------------------------------------------------------------

final_rec["Final_Action"] = np.where(

    final_rec["ML_Signal"]
    == "CONSIDER REALLOCATION",

    "CONSIDER PILOT REALLOCATION",

    "KEEP CURRENT FACTORY"
)

# ------------------------------------------------------------
# 15. SORT BEST IMPROVEMENT FIRST
# ------------------------------------------------------------

final_rec = final_rec.sort_values(
    "Probability_Reduction_Percentage_Points",
    ascending=False
).reset_index(drop=True)

# ------------------------------------------------------------
# 16. SAVE FINAL FILE
# ------------------------------------------------------------

final_file = (
    results_dir
    / "final_factory_reallocation_recommendations.csv"
)

final_rec.to_csv(
    final_file,
    index=False
)

# ------------------------------------------------------------
# 17. FINAL RESULT
# ------------------------------------------------------------

print("\n")
print("=" * 70)
print("FINAL RECOMMENDATIONS")
print("=" * 70)

show_cols = [
    "Product Name",
    "Current Factory",
    "Scenario Factory",
    "Current Slow Probability",
    "Predicted Slow Probability",
    "Probability_Reduction_Percentage_Points",
    "ML_Signal",
    "Final_Action"
]

print(
    final_rec[show_cols].to_string(index=False)
)

# ------------------------------------------------------------
# 18. OVERALL IMPACT
# ------------------------------------------------------------

total_records = final_rec["Records"].sum()

weighted_current = (
    (
        final_rec["Current Slow Probability"]
        * final_rec["Records"]
    ).sum()
    / total_records
)

weighted_predicted = (
    (
        final_rec["Predicted Slow Probability"]
        * final_rec["Records"]
    ).sum()
    / total_records
)

weighted_reduction = (
    weighted_current
    - weighted_predicted
) * 100

# ------------------------------------------------------------
# 19. SUMMARY
# ------------------------------------------------------------

reallocation_count = (
    final_rec["ML_Signal"]
    == "CONSIDER REALLOCATION"
).sum()

print("\n")
print("=" * 70)
print("PROJECT SUMMARY")
print("=" * 70)

print(
    f"Products evaluated              : "
    f"{len(final_rec)}"
)

print(
    f"Products with strong ML signal  : "
    f"{reallocation_count}"
)

print(
    f"Weighted current slow probability : "
    f"{weighted_current:.4f}"
)

print(
    f"Weighted predicted slow probability: "
    f"{weighted_predicted:.4f}"
)

print(
    f"Weighted improvement             : "
    f"{weighted_reduction:.4f} percentage points"
)

print("\nFinal file:")
print(final_file)

print("\n" + "=" * 70)
print("STATUS: STEP 26B COMPLETED SUCCESSFULLY")
print("=" * 70)

print(
    "\nNOTE:"
    "\nThese recommendations are ML-based counterfactual"
    "\nscreening results, not causal estimates."
    "\nNo transportation-cost savings are claimed because"
    "\nverified factory coordinates/cost data are unavailable."
)

======================================================================
STEP 26B — FINAL FACTORY REALLOCATION RECOMMENDATIONS
======================================================================
Project directory: c:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization
Loading Step 26A output...
Records: 15

Columns found:
 - Product Name
 - Current Factory
 - Scenario Factory
 - Current Slow Probability
 - Predicted Slow Probability
 - Probability Reduction
 - Improvement_Percentage_Points
 - Recommendation

STEP 26A INPUT VALIDATION: PASSED
Probability range validation: PASSED
Probability reduction recalculated from source probabilities.
Factory scenario validation: PASSED
Unique products: 15
Product validation: PASSED

Raw dataset records: 10194
Business metrics merge: PASSED


======================================================================
FINAL RECOMMENDATIONS
======================================================================
                     Product Name   Current Factory  Scenario Factory  Current Slow Probability  Predicted Slow Probability  Probability_Reduction_Percentage_Points           ML_Signal         Final_Action
           Everlasting Gobstopper    Secret Factory The Other Factory                  0.524733                    0.498854                                 2.587866 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
             Fizzy Lifting Drinks       Sugar Shack The Other Factory                  0.292623                    0.278194                                 1.442872 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                      Laffy Taffy       Sugar Shack The Other Factory                  0.366585                    0.352903                                 1.368241 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
               Lickable Wallpaper    Secret Factory The Other Factory                  0.345119                    0.332885                                 1.223438 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                        Wonka Gum    Secret Factory The Other Factory                  0.314837                    0.302741                                 1.209590 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                        SweeTARTS       Sugar Shack The Other Factory                  0.459319                    0.447265                                 1.205417 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
       Wonka Bar - Milk Chocolate   Wicked Choccy's The Other Factory                  0.329027                    0.319269                                 0.975803 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                            Nerds       Sugar Shack The Other Factory                  0.486656                    0.477404                                 0.925209 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
Wonka Bar - Triple Dazzle Caramel   Wicked Choccy's The Other Factory                  0.316443                    0.309277                                 0.716562 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
        Wonka Bar - Fudge Mallows     Lot's O' Nuts The Other Factory                  0.316155                    0.309246                                 0.690892 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
Wonka Bar - Nutty Crunch Surprise     Lot's O' Nuts The Other Factory                  0.325851                    0.319331                                 0.651918 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
   Wonka Bar -Scrumdiddlyumptious     Lot's O' Nuts The Other Factory                  0.309408                    0.303281                                 0.612666 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                      Hair Toffee The Other Factory   Wicked Choccy's                  0.369730                    0.369431                                 0.029973 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                          Fun Dip       Sugar Shack     Lot's O' Nuts                  0.444194                    0.445932                                -0.173814 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                        Kazookles The Other Factory     Lot's O' Nuts                  0.260536                    0.268511                                -0.797484 NO STRONG ML SIGNAL KEEP CURRENT FACTORY


======================================================================
PROJECT SUMMARY
======================================================================
Products evaluated              : 15
Products with strong ML signal  : 0
Weighted current slow probability : 0.3194
Weighted predicted slow probability: 0.3120
Weighted improvement             : 0.7317 percentage points

Final file:
c:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization\results\final_factory_reallocation_recommendations.csv

======================================================================
STATUS: STEP 26B COMPLETED SUCCESSFULLY
======================================================================

NOTE:
These recommendations are ML-based counterfactual
screening results, not causal estimates.
No transportation-cost savings are claimed because
verified factory coordinates/cost data are unavailable.

In [18]:
# ============================================================
# STEP 26C — FINAL OUTPUT AUDIT
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 26C — FINAL OUTPUT AUDIT")
print("=" * 70)

# ------------------------------------------------------------
# 1. LOCATE PROJECT
# ------------------------------------------------------------

cwd = Path.cwd()

project_candidates = [
    cwd,
    cwd.parent,
    cwd.parent.parent
]

project_dir = None

for path in project_candidates:
    if (path / "results").is_dir():
        project_dir = path
        break

if project_dir is None:
    raise FileNotFoundError(
        "Project directory with 'results' folder was not found."
    )

results_dir = project_dir / "results"

# ------------------------------------------------------------
# 2. FINAL FILE
# ------------------------------------------------------------

final_file = (
    results_dir
    / "final_factory_reallocation_recommendations.csv"
)

if not final_file.is_file():
    raise FileNotFoundError(
        "Final recommendation file was not created:\n"
        + str(final_file)
    )

print("Final file found:")
print(final_file)

# ------------------------------------------------------------
# 3. LOAD FINAL FILE
# ------------------------------------------------------------

final_df = pd.read_csv(final_file)

print("\nFinal records:", len(final_df))
print("Final columns:", len(final_df.columns))

# ------------------------------------------------------------
# 4. REQUIRED FINAL COLUMNS
# ------------------------------------------------------------

required_columns = [
    "Product Name",
    "Current Factory",
    "Scenario Factory",
    "Current Slow Probability",
    "Predicted Slow Probability",
    "Probability_Reduction_Percentage_Points",
    "ML_Signal",
    "Final_Action",
    "Records",
    "Orders",
    "Sales",
    "Units",
    "Gross_Profit",
    "Estimated_Avoided_Slow_Records"
]

missing_columns = [
    col for col in required_columns
    if col not in final_df.columns
]

if missing_columns:
    raise ValueError(
        "Final file is missing required columns:\n"
        + "\n".join(missing_columns)
    )

print("Required columns: PASSED")

# ------------------------------------------------------------
# 5. RECORD / PRODUCT CHECK
# ------------------------------------------------------------

if len(final_df) != 15:
    raise ValueError(
        f"Expected 15 final recommendations, "
        f"found {len(final_df)}."
    )

if final_df["Product Name"].nunique() != 15:
    raise ValueError(
        "Final file does not contain exactly "
        "15 unique products."
    )

print("15-product recommendation check: PASSED")

# ------------------------------------------------------------
# 6. DUPLICATE CHECK
# ------------------------------------------------------------

if final_df["Product Name"].duplicated().any():
    raise ValueError(
        "Duplicate product recommendations detected."
    )

print("Duplicate check: PASSED")

# ------------------------------------------------------------
# 7. PROBABILITY CHECK
# ------------------------------------------------------------

probability_columns = [
    "Current Slow Probability",
    "Predicted Slow Probability"
]

for column in probability_columns:

    final_df[column] = pd.to_numeric(
        final_df[column],
        errors="coerce"
    )

    if final_df[column].isna().any():
        raise ValueError(
            f"Invalid probability values in {column}."
        )

    if not final_df[column].between(0, 1).all():
        raise ValueError(
            f"Probability outside 0-1 range in {column}."
        )

print("Probability range check: PASSED")

# ------------------------------------------------------------
# 8. REDUCTION CHECK
# ------------------------------------------------------------

final_df[
    "Probability_Reduction_Percentage_Points"
] = pd.to_numeric(
    final_df[
        "Probability_Reduction_Percentage_Points"
    ],
    errors="coerce"
)

calculated_reduction = (
    final_df["Current Slow Probability"]
    - final_df["Predicted Slow Probability"]
) * 100

difference = np.abs(
    final_df[
        "Probability_Reduction_Percentage_Points"
    ]
    - calculated_reduction
)

if difference.max() > 0.0001:
    raise ValueError(
        "Final probability reduction values "
        "do not match source probabilities."
    )

print("Probability reduction check: PASSED")

# ------------------------------------------------------------
# 9. FACTORY CHECK
# ------------------------------------------------------------

if (
    final_df["Current Factory"]
    == final_df["Scenario Factory"]
).any():

    raise ValueError(
        "Current Factory equals Scenario Factory "
        "for at least one recommendation."
    )

print("Factory scenario check: PASSED")

# ------------------------------------------------------------
# 10. BUSINESS METRICS CHECK
# ------------------------------------------------------------

business_columns = [
    "Records",
    "Orders",
    "Sales",
    "Units",
    "Gross_Profit"
]

for column in business_columns:

    final_df[column] = pd.to_numeric(
        final_df[column],
        errors="coerce"
    )

    if final_df[column].isna().any():
        raise ValueError(
            f"Invalid business metric in {column}."
        )

print("Business metrics check: PASSED")

# ------------------------------------------------------------
# 11. ACTION CHECK
# ------------------------------------------------------------

allowed_actions = {
    "CONSIDER PILOT REALLOCATION",
    "KEEP CURRENT FACTORY"
}

invalid_actions = set(
    final_df["Final_Action"].dropna().unique()
) - allowed_actions

if invalid_actions:
    raise ValueError(
        "Unexpected Final_Action values:\n"
        + str(invalid_actions)
    )

print("Final action check: PASSED")

# ------------------------------------------------------------
# 12. ML SIGNAL CHECK
# ------------------------------------------------------------

allowed_signals = {
    "CONSIDER REALLOCATION",
    "NO STRONG ML SIGNAL"
}

invalid_signals = set(
    final_df["ML_Signal"].dropna().unique()
) - allowed_signals

if invalid_signals:
    raise ValueError(
        "Unexpected ML_Signal values:\n"
        + str(invalid_signals)
    )

print("ML signal check: PASSED")

# ------------------------------------------------------------
# 13. DISPLAY FINAL RECOMMENDATIONS
# ------------------------------------------------------------

display_columns = [
    "Product Name",
    "Current Factory",
    "Scenario Factory",
    "Current Slow Probability",
    "Predicted Slow Probability",
    "Probability_Reduction_Percentage_Points",
    "ML_Signal",
    "Final_Action"
]

print("\nFINAL RECOMMENDATION TABLE")
print("=" * 70)

print(
    final_df[display_columns]
    .to_string(index=False)
)

# ------------------------------------------------------------
# 14. SUMMARY
# ------------------------------------------------------------

strong_signal_count = (
    final_df["ML_Signal"]
    == "CONSIDER REALLOCATION"
).sum()

keep_current_count = (
    final_df["Final_Action"]
    == "KEEP CURRENT FACTORY"
).sum()

pilot_count = (
    final_df["Final_Action"]
    == "CONSIDER PILOT REALLOCATION"
).sum()

print("\n" + "=" * 70)
print("FINAL AUDIT SUMMARY")
print("=" * 70)

print("Products evaluated       :", len(final_df))
print("Consider pilot           :", pilot_count)
print("Keep current factory     :", keep_current_count)
print("Strong ML signals        :", strong_signal_count)

print("\nFinal file verified:")
print(final_file)

print("\n" + "=" * 70)
print("STATUS: STEP 26C COMPLETED SUCCESSFULLY")
print("=" * 70)

======================================================================
STEP 26C — FINAL OUTPUT AUDIT
======================================================================
Final file found:
c:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization\results\final_factory_reallocation_recommendations.csv

Final records: 15
Final columns: 17
Required columns: PASSED
15-product recommendation check: PASSED
Duplicate check: PASSED
Probability range check: PASSED
Probability reduction check: PASSED
Factory scenario check: PASSED
Business metrics check: PASSED
Final action check: PASSED
ML signal check: PASSED

FINAL RECOMMENDATION TABLE
======================================================================
                     Product Name   Current Factory  Scenario Factory  Current Slow Probability  Predicted Slow Probability  Probability_Reduction_Percentage_Points           ML_Signal         Final_Action
           Everlasting Gobstopper    Secret Factory The Other Factory                  0.524733                    0.498854                                 2.587866 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
             Fizzy Lifting Drinks       Sugar Shack The Other Factory                  0.292623                    0.278194                                 1.442872 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                      Laffy Taffy       Sugar Shack The Other Factory                  0.366585                    0.352903                                 1.368241 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
               Lickable Wallpaper    Secret Factory The Other Factory                  0.345119                    0.332885                                 1.223438 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                        Wonka Gum    Secret Factory The Other Factory                  0.314837                    0.302741                                 1.209590 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                        SweeTARTS       Sugar Shack The Other Factory                  0.459319                    0.447265                                 1.205417 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
       Wonka Bar - Milk Chocolate   Wicked Choccy's The Other Factory                  0.329027                    0.319269                                 0.975803 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                            Nerds       Sugar Shack The Other Factory                  0.486656                    0.477404                                 0.925209 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
Wonka Bar - Triple Dazzle Caramel   Wicked Choccy's The Other Factory                  0.316443                    0.309277                                 0.716562 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
        Wonka Bar - Fudge Mallows     Lot's O' Nuts The Other Factory                  0.316155                    0.309246                                 0.690892 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
Wonka Bar - Nutty Crunch Surprise     Lot's O' Nuts The Other Factory                  0.325851                    0.319331                                 0.651918 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
   Wonka Bar -Scrumdiddlyumptious     Lot's O' Nuts The Other Factory                  0.309408                    0.303281                                 0.612666 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                      Hair Toffee The Other Factory   Wicked Choccy's                  0.369730                    0.369431                                 0.029973 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                          Fun Dip       Sugar Shack     Lot's O' Nuts                  0.444194                    0.445932                                -0.173814 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                        Kazookles The Other Factory     Lot's O' Nuts                  0.260536                    0.268511                                -0.797484 NO STRONG ML SIGNAL KEEP CURRENT FACTORY

======================================================================
FINAL AUDIT SUMMARY
======================================================================
Products evaluated       : 15
Consider pilot           : 0
Keep current factory     : 15
Strong ML signals        : 0

Final file verified:
c:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization\results\final_factory_reallocation_recommendations.csv

======================================================================
STATUS: STEP 26C COMPLETED SUCCESSFULLY
======================================================================

In [19]:
# ============================================================
# STEP 27 — RANDOM FOREST MODEL EXPLAINABILITY
# Feature Importance Analysis
# ============================================================

from pathlib import Path
import sys
import subprocess
import importlib.util

# ------------------------------------------------------------
# 1. Required package check
# ------------------------------------------------------------
if importlib.util.find_spec("joblib") is None:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "joblib"])

import joblib
import pandas as pd
import numpy as np

# ------------------------------------------------------------
# 2. Locate project directory and saved model
# ------------------------------------------------------------
current_path = Path.cwd()

possible_model_paths = [
    current_path / "models" / "nassau_slow_shipment_model.joblib",
    current_path.parent / "models" / "nassau_slow_shipment_model.joblib",
]

model_path = next(
    (p for p in possible_model_paths if p.exists()),
    None
)

if model_path is None:
    raise FileNotFoundError(
        "Saved model not found. Expected:\n"
        "models/nassau_slow_shipment_model.joblib"
    )

# ------------------------------------------------------------
# 3. Load saved model
# ------------------------------------------------------------
loaded_model = joblib.load(model_path)

print("=" * 70)
print("STEP 27 — RANDOM FOREST FEATURE IMPORTANCE")
print("=" * 70)

print(f"Model file: {model_path}")
print(f"Loaded model type: {type(loaded_model).__name__}")

# ------------------------------------------------------------
# 4. Validate that the saved object is a Pipeline
# ------------------------------------------------------------
if not hasattr(loaded_model, "named_steps"):
    raise TypeError(
        "Saved model is not a scikit-learn Pipeline. "
        "Feature extraction cannot continue safely."
    )

print(f"Pipeline steps: {list(loaded_model.named_steps.keys())}")

# ------------------------------------------------------------
# 5. Find the fitted estimator
# ------------------------------------------------------------
estimator = None

for step_name, step_object in reversed(loaded_model.named_steps.items()):
    if hasattr(step_object, "feature_importances_"):
        estimator = step_object
        estimator_name = step_name
        break

if estimator is None:
    raise TypeError(
        "No estimator with feature_importances_ was found "
        "inside the saved pipeline."
    )

print(f"Estimator step: {estimator_name}")
print(f"Estimator type: {type(estimator).__name__}")

# ------------------------------------------------------------
# 6. Confirm Random Forest
# ------------------------------------------------------------
if not hasattr(estimator, "feature_importances_"):
    raise AttributeError(
        "The selected estimator does not provide feature_importances_."
    )

raw_importances = np.asarray(estimator.feature_importances_, dtype=float)

if len(raw_importances) == 0:
    raise ValueError("Feature importance array is empty.")

if not np.isfinite(raw_importances).all():
    raise ValueError("Feature importance contains invalid numeric values.")

# ------------------------------------------------------------
# 7. Locate preprocessing transformer
# ------------------------------------------------------------
preprocessor = None

for step_name, step_object in loaded_model.named_steps.items():
    if hasattr(step_object, "get_feature_names_out"):
        if step_name != estimator_name:
            preprocessor = step_object
            preprocessor_name = step_name
            break

if preprocessor is None:
    raise TypeError(
        "Preprocessing transformer with get_feature_names_out() "
        "was not found in the saved pipeline."
    )

print(f"Preprocessor step: {preprocessor_name}")

# ------------------------------------------------------------
# 8. Extract transformed feature names
# ------------------------------------------------------------
feature_names = np.asarray(
    preprocessor.get_feature_names_out(),
    dtype=str
)

if len(feature_names) != len(raw_importances):
    raise ValueError(
        f"Feature-name count ({len(feature_names)}) does not match "
        f"importance count ({len(raw_importances)})."
    )

# ------------------------------------------------------------
# 9. Create transformed-feature importance table
# ------------------------------------------------------------
importance_df = pd.DataFrame({
    "Transformed_Feature": feature_names,
    "Importance": raw_importances
})

importance_df["Importance_Percentage"] = (
    importance_df["Importance"] /
    importance_df["Importance"].sum()
) * 100

importance_df = importance_df.sort_values(
    "Importance",
    ascending=False
).reset_index(drop=True)

# ------------------------------------------------------------
# 10. Aggregate One-Hot Encoded features back to original features
# ------------------------------------------------------------
original_features = [
    "Product Name",
    "Division",
    "Country/Region",
    "State/Province",
    "Region",
    "Factory",
    "Ship Mode",
    "Units",
    "Sales",
    "Cost",
    "Gross Profit",
    "Order_Year",
    "Order_Month",
    "Order_Quarter",
    "Order_DayOfWeek",
]

def map_to_original_feature(transformed_name):
    """
    Convert ColumnTransformer output names such as:
    cat__Product Name_X
    num__Sales
    back to the original feature name.
    """
    
    cleaned = str(transformed_name)

    if cleaned.startswith("cat__"):
        cleaned = cleaned[len("cat__"):]

        for feature in sorted(
            original_features,
            key=len,
            reverse=True
        ):
            if cleaned == feature or cleaned.startswith(feature + "_"):
                return feature

    if cleaned.startswith("num__"):
        cleaned = cleaned[len("num__"):]

        if cleaned in original_features:
            return cleaned

    # Fallback: try direct matching
    for feature in sorted(
        original_features,
        key=len,
        reverse=True
    ):
        if cleaned == feature or cleaned.startswith(feature + "_"):
            return feature

    return cleaned


importance_df["Original_Feature"] = (
    importance_df["Transformed_Feature"]
    .apply(map_to_original_feature)
)

# ------------------------------------------------------------
# 11. Aggregate importance by original feature
# ------------------------------------------------------------
feature_importance_summary = (
    importance_df
    .groupby("Original_Feature", as_index=False)["Importance"]
    .sum()
    .sort_values("Importance", ascending=False)
    .reset_index(drop=True)
)

feature_importance_summary["Importance_Percentage"] = (
    feature_importance_summary["Importance"] /
    feature_importance_summary["Importance"].sum()
) * 100

# ------------------------------------------------------------
# 12. Validation
# ------------------------------------------------------------
if len(feature_importance_summary) != len(original_features):
    missing_features = sorted(
        set(original_features)
        - set(feature_importance_summary["Original_Feature"])
    )

    if missing_features:
        print(
            "Note: Some original features have no transformed "
            f"importance entry: {missing_features}"
        )

if not np.isclose(
    feature_importance_summary["Importance"].sum(),
    1.0,
    atol=1e-6
):
    raise ValueError(
        "Aggregated feature importance does not sum to 1."
    )

if (
    feature_importance_summary["Importance_Percentage"].isna().any()
    or
    np.isinf(
        feature_importance_summary["Importance_Percentage"]
    ).any()
):
    raise ValueError(
        "Invalid values found in feature importance percentages."
    )

# ------------------------------------------------------------
# 13. Save results
# ------------------------------------------------------------
project_dir = model_path.parent.parent
results_dir = project_dir / "results"
results_dir.mkdir(parents=True, exist_ok=True)

transformed_output = (
    results_dir / "random_forest_transformed_feature_importance.csv"
)

summary_output = (
    results_dir / "random_forest_feature_importance.csv"
)

importance_df.to_csv(
    transformed_output,
    index=False
)

feature_importance_summary.to_csv(
    summary_output,
    index=False
)

# ------------------------------------------------------------
# 14. Display top 15 original features
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("TOP MODEL FEATURES")
print("=" * 70)

display_columns = [
    "Original_Feature",
    "Importance",
    "Importance_Percentage"
]

print(
    feature_importance_summary[
        display_columns
    ]
    .head(15)
    .to_string(index=False)
)

# ------------------------------------------------------------
# 15. Final validation summary
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("STEP 27 VALIDATION")
print("=" * 70)

print(f"Transformed features analyzed: {len(feature_names)}")
print(
    f"Original model features analyzed: "
    f"{len(feature_importance_summary)}"
)
print(
    "Importance total: "
    f"{feature_importance_summary['Importance'].sum():.6f}"
)

print(f"\nSaved transformed feature importance:")
print(transformed_output)

print(f"\nSaved original feature importance:")
print(summary_output)

print("\n" + "=" * 70)
print("STATUS: STEP 27 COMPLETED SUCCESSFULLY")
print("=" * 70)

======================================================================
STEP 27 — RANDOM FOREST FEATURE IMPORTANCE
======================================================================
Model file: c:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization\models\nassau_slow_shipment_model.joblib
Loaded model type: Pipeline
Pipeline steps: ['preprocessor', 'model']
Estimator step: model
Estimator type: RandomForestClassifier
Preprocessor step: preprocessor

======================================================================
TOP MODEL FEATURES
======================================================================
Original_Feature  Importance  Importance_Percentage
      Order_Year    0.409008              40.900839
       Ship Mode    0.260200              26.019957
  State/Province    0.072826               7.282631
 Order_DayOfWeek    0.067687               6.768710
     Order_Month    0.035582               3.558186
            Cost    0.024427               2.442748
    Gross Profit    0.023838               2.383831
           Sales    0.022171               2.217122
    Product Name    0.021835               2.183471
          Region    0.018508               1.850751
   Order_Quarter    0.016329               1.632940
           Units    0.015493               1.549266
         Factory    0.008788               0.878777
        Division    0.001786               0.178605
  Country/Region    0.001522               0.152164

======================================================================
STEP 27 VALIDATION
======================================================================
Transformed features analyzed: 99
Original model features analyzed: 15
Importance total: 1.000000

Saved transformed feature importance:
c:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization\results\random_forest_transformed_feature_importance.csv

Saved original feature importance:
c:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization\results\random_forest_feature_importance.csv

======================================================================
STATUS: STEP 27 COMPLETED SUCCESSFULLY
======================================================================

In [20]:
# ============================================================
# STEP 28 — TEST-SET PERMUTATION IMPORTANCE
# Independent Model Explainability Validation
# ============================================================

from pathlib import Path
import sys
import subprocess
import importlib.util

# ------------------------------------------------------------
# 1. Check required packages
# ------------------------------------------------------------
required_packages = {
    "pandas": "pandas",
    "numpy": "numpy",
    "joblib": "joblib",
    "sklearn": "scikit-learn"
}

for module_name, package_name in required_packages.items():
    if importlib.util.find_spec(module_name) is None:
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", package_name]
        )

import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import GroupShuffleSplit
from sklearn.inspection import permutation_importance
from sklearn.metrics import roc_auc_score


# ============================================================
# 2. Locate project directory
# ============================================================

current_path = Path.cwd()

possible_project_dirs = [
    current_path,
    current_path.parent,
]

project_dir = None

for candidate in possible_project_dirs:
    if (
        (candidate / "data" / "Nassau Candy Distributor.csv").exists()
        and
        (candidate / "models" / "nassau_slow_shipment_model.joblib").exists()
    ):
        project_dir = candidate
        break

if project_dir is None:
    raise FileNotFoundError(
        "Project files could not be located.\n"
        "Expected data/Nassau Candy Distributor.csv and "
        "models/nassau_slow_shipment_model.joblib"
    )


# ============================================================
# 3. Define file paths
# ============================================================

data_path = project_dir / "data" / "Nassau Candy Distributor.csv"
model_path = project_dir / "models" / "nassau_slow_shipment_model.joblib"
results_dir = project_dir / "results"

results_dir.mkdir(parents=True, exist_ok=True)


# ============================================================
# 4. Load raw dataset
# ============================================================

df = pd.read_csv(data_path)

print("=" * 70)
print("STEP 28 — TEST-SET PERMUTATION IMPORTANCE")
print("=" * 70)

print(f"Dataset: {data_path}")
print(f"Records loaded: {len(df):,}")


# ============================================================
# 5. Validate raw dataset
# ============================================================

required_raw_columns = [
    "Row ID",
    "Order ID",
    "Order Date",
    "Ship Date",
    "Ship Mode",
    "Customer ID",
    "Country/Region",
    "City",
    "State/Province",
    "Postal Code",
    "Division",
    "Region",
    "Product ID",
    "Product Name",
    "Sales",
    "Units",
    "Gross Profit",
    "Cost"
]

missing_raw_columns = [
    col for col in required_raw_columns
    if col not in df.columns
]

if missing_raw_columns:
    raise ValueError(
        f"Missing raw dataset columns: {missing_raw_columns}"
    )

if len(df) != 10194:
    raise ValueError(
        f"Unexpected dataset size: {len(df)}. "
        "Expected 10,194 records."
    )


# ============================================================
# 6. Validated Product → Factory mapping
# ============================================================

factory_mapping = {
    "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
    "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
    "Wonka Bar - Scrumdiddlyumptious": "Lot's O' Nuts",

    "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
    "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",

    "Laffy Taffy": "Sugar Shack",
    "SweeTARTS": "Sugar Shack",
    "Nerds": "Sugar Shack",
    "Fun Dip": "Sugar Shack",
    "Fizzy Lifting Drinks": "Sugar Shack",

    "Everlasting Gobstopper": "Secret Factory",
    "Lickable Wallpaper": "Secret Factory",
    "Wonka Gum": "Secret Factory",

    "Hair Toffee": "The Other Factory",
    "Kazookles": "The Other Factory"
}


# ============================================================
# 7. Normalize product names safely
# ============================================================

import re
import unicodedata


def canonical_product_name(value):
    if pd.isna(value):
        return ""

    text = str(value)

    text = unicodedata.normalize("NFKC", text)
    text = text.replace("\u00A0", " ")
    text = text.strip()

    # Normalize spaces around hyphen
    text = re.sub(r"\s*-\s*", " - ", text)

    # Normalize repeated whitespace
    text = re.sub(r"\s+", " ", text)

    return text


df["_Product_Key"] = df["Product Name"].apply(
    canonical_product_name
)

mapping_normalized = {
    canonical_product_name(product): factory
    for product, factory in factory_mapping.items()
}

df["Factory"] = df["_Product_Key"].map(
    mapping_normalized
)

unmapped_rows = int(df["Factory"].isna().sum())

if unmapped_rows != 0:
    raise ValueError(
        f"Factory mapping failed for {unmapped_rows} rows."
    )


# ============================================================
# 8. Parse dates from ORIGINAL raw strings
# ============================================================

df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y",
    errors="raise"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    format="%d-%m-%Y",
    errors="raise"
)

df["Delivery_Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days


# ============================================================
# 9. Validate delivery calculations
# ============================================================

if df["Order Date"].isna().any():
    raise ValueError("Order Date contains missing values.")

if df["Ship Date"].isna().any():
    raise ValueError("Ship Date contains missing values.")

if df["Delivery_Days"].isna().any():
    raise ValueError("Delivery_Days contains missing values.")

if (df["Delivery_Days"] < 0).any():
    raise ValueError(
        "Negative Delivery_Days detected."
    )


# ============================================================
# 10. Create date features
# ============================================================

df["Order_Year"] = df["Order Date"].dt.year
df["Order_Month"] = df["Order Date"].dt.month
df["Order_Quarter"] = df["Order Date"].dt.quarter
df["Order_DayOfWeek"] = df["Order Date"].dt.dayofweek


# ============================================================
# 11. Reproduce the SAME order-level split used previously
# ============================================================

splitter = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

train_idx, test_idx = next(
    splitter.split(
        df,
        groups=df["Order ID"]
    )
)

train_df = df.iloc[train_idx].copy()
test_df = df.iloc[test_idx].copy()


# ============================================================
# 12. Validate order-level separation
# ============================================================

train_orders = set(train_df["Order ID"])
test_orders = set(test_df["Order ID"])

order_overlap = train_orders.intersection(test_orders)

if len(order_overlap) != 0:
    raise ValueError(
        f"Order leakage detected: {len(order_overlap)} overlapping orders."
    )

print("\nORDER-LEVEL SPLIT VALIDATION")
print("-" * 70)
print(f"Train records: {len(train_df):,}")
print(f"Test records : {len(test_df):,}")
print(f"Train orders : {len(train_orders):,}")
print(f"Test orders  : {len(test_orders):,}")
print(f"Order overlap: {len(order_overlap)}")


# ============================================================
# 13. Create TRAIN-ONLY target threshold
# ============================================================

train_q3 = train_df["Delivery_Days"].quantile(0.75)

if not np.isfinite(train_q3):
    raise ValueError(
        "Invalid train-only Q3 threshold."
    )

train_df["Slow_Shipment"] = (
    train_df["Delivery_Days"] > train_q3
).astype(int)

test_df["Slow_Shipment"] = (
    test_df["Delivery_Days"] > train_q3
).astype(int)


# ============================================================
# 14. Validate expected split statistics
# ============================================================

if len(train_df) != 8132:
    raise ValueError(
        f"Unexpected train record count: {len(train_df)}. "
        "Expected 8,132."
    )

if len(test_df) != 2062:
    raise ValueError(
        f"Unexpected test record count: {len(test_df)}. "
        "Expected 2,062."
    )

if len(train_orders) != 6839:
    raise ValueError(
        f"Unexpected train order count: {len(train_orders)}. "
        "Expected 6,839."
    )

if len(test_orders) != 1710:
    raise ValueError(
        f"Unexpected test order count: {len(test_orders)}. "
        "Expected 1,710."
    )

if int(round(train_q3)) != 1638:
    raise ValueError(
        f"Unexpected train-only Q3 threshold: {train_q3}. "
        "Expected 1,638."
    )


# ============================================================
# 15. Define EXACT model input features
# ============================================================

feature_columns = [
    "Product Name",
    "Division",
    "Country/Region",
    "State/Province",
    "Region",
    "Factory",
    "Ship Mode",
    "Units",
    "Sales",
    "Cost",
    "Gross Profit",
    "Order_Year",
    "Order_Month",
    "Order_Quarter",
    "Order_DayOfWeek"
]


# ============================================================
# 16. Validate feature columns
# ============================================================

missing_features = [
    col for col in feature_columns
    if col not in test_df.columns
]

if missing_features:
    raise ValueError(
        f"Missing model features: {missing_features}"
    )

X_test = test_df[feature_columns].copy()
y_test = test_df["Slow_Shipment"].copy()


# ============================================================
# 17. Load saved Random Forest pipeline
# ============================================================

loaded_model = joblib.load(model_path)

if not hasattr(loaded_model, "predict_proba"):
    raise TypeError(
        "Saved model does not support predict_proba()."
    )

if not hasattr(loaded_model, "predict"):
    raise TypeError(
        "Saved model does not support predict()."
    )

print("\nMODEL VALIDATION")
print("-" * 70)
print(f"Model file: {model_path}")
print(f"Model type: {type(loaded_model).__name__}")


# ============================================================
# 18. Verify test-set predictive performance
# ============================================================

test_probabilities = loaded_model.predict_proba(X_test)[:, 1]

if not np.isfinite(test_probabilities).all():
    raise ValueError(
        "Model produced invalid probability values."
    )

baseline_auc = roc_auc_score(
    y_test,
    test_probabilities
)

print(f"Test ROC-AUC: {baseline_auc:.4f}")

# Existing validated model performance should be approximately 0.9013.
if not np.isclose(
    baseline_auc,
    0.9013,
    atol=0.01
):
    raise ValueError(
        f"Unexpected test ROC-AUC: {baseline_auc:.4f}. "
        "This does not match the previously validated model."
    )


# ============================================================
# 19. Calculate TEST-SET permutation importance
# ============================================================

print("\nCalculating permutation importance...")
print("Metric: ROC-AUC")
print("Repeats: 10")
print("Random state: 42")

permutation_result = permutation_importance(
    loaded_model,
    X_test,
    y_test,
    scoring="roc_auc",
    n_repeats=10,
    random_state=42,
    n_jobs=-1
)


# ============================================================
# 20. Validate permutation output
# ============================================================

if len(permutation_result.importances_mean) != len(feature_columns):
    raise ValueError(
        "Permutation importance count does not match "
        "the number of model input features."
    )

if not np.isfinite(
    permutation_result.importances_mean
).all():
    raise ValueError(
        "Permutation importance contains invalid values."
    )

if not np.isfinite(
    permutation_result.importances_std
).all():
    raise ValueError(
        "Permutation importance standard deviation "
        "contains invalid values."
    )


# ============================================================
# 21. Create importance table
# ============================================================

permutation_df = pd.DataFrame({
    "Feature": feature_columns,
    "Importance_Mean": permutation_result.importances_mean,
    "Importance_STD": permutation_result.importances_std
})

permutation_df["Importance_Percentage"] = (
    permutation_df["Importance_Mean"].clip(lower=0)
)

positive_total = permutation_df[
    "Importance_Percentage"
].sum()

if positive_total > 0:
    permutation_df["Importance_Percentage"] = (
        permutation_df["Importance_Percentage"]
        / positive_total
    ) * 100
else:
    permutation_df["Importance_Percentage"] = 0.0

permutation_df = permutation_df.sort_values(
    "Importance_Mean",
    ascending=False
).reset_index(drop=True)


# ============================================================
# 22. Add interpretation label
# ============================================================

def importance_level(value):
    if value > 0.02:
        return "HIGH"
    elif value > 0.005:
        return "MODERATE"
    elif value > 0:
        return "LOW"
    else:
        return "NO POSITIVE TEST-SET IMPACT"


permutation_df["Importance_Level"] = (
    permutation_df["Importance_Mean"]
    .apply(importance_level)
)


# ============================================================
# 23. Save results
# ============================================================

output_path = (
    results_dir
    / "random_forest_test_permutation_importance.csv"
)

permutation_df.to_csv(
    output_path,
    index=False
)


# ============================================================
# 24. Display final results
# ============================================================

print("\n" + "=" * 70)
print("TEST-SET PERMUTATION IMPORTANCE RESULTS")
print("=" * 70)

print(
    permutation_df[
        [
            "Feature",
            "Importance_Mean",
            "Importance_STD",
            "Importance_Percentage",
            "Importance_Level"
        ]
    ]
    .to_string(index=False)
)


# ============================================================
# 25. Final validation
# ============================================================

print("\n" + "=" * 70)
print("STEP 28 VALIDATION")
print("=" * 70)

print("Raw dataset validation: PASSED")
print("Factory mapping validation: PASSED")
print("Date parsing validation: PASSED")
print("Delivery calculation validation: PASSED")
print("Order-level split validation: PASSED")
print("Train-only target threshold validation: PASSED")
print("Feature validation: PASSED")
print("Saved model validation: PASSED")
print(f"Test ROC-AUC validation: PASSED ({baseline_auc:.4f})")
print("Permutation importance calculation: PASSED")
print("Permutation output validation: PASSED")

print(f"\nSaved file:")
print(output_path)

print("\n" + "=" * 70)
print("STATUS: STEP 28 COMPLETED SUCCESSFULLY")
print("=" * 70)

======================================================================
STEP 28 — TEST-SET PERMUTATION IMPORTANCE
======================================================================
Dataset: c:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization\data\Nassau Candy Distributor.csv
Records loaded: 10,194

ORDER-LEVEL SPLIT VALIDATION
----------------------------------------------------------------------
Train records: 8,132
Test records : 2,062
Train orders : 6,839
Test orders  : 1,710
Order overlap: 0

MODEL VALIDATION
----------------------------------------------------------------------
Model file: c:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization\models\nassau_slow_shipment_model.joblib
Model type: Pipeline
Test ROC-AUC: 0.9013

Calculating permutation importance...
Metric: ROC-AUC
Repeats: 10
Random state: 42

======================================================================
TEST-SET PERMUTATION IMPORTANCE RESULTS
======================================================================
        Feature  Importance_Mean  Importance_STD  Importance_Percentage            Importance_Level
     Order_Year         0.230840        0.009572              50.499147                        HIGH
      Ship Mode         0.193775        0.010201              42.390693                        HIGH
Order_DayOfWeek         0.016590        0.003520               3.629333                    MODERATE
 State/Province         0.006535        0.001527               1.429530                    MODERATE
    Order_Month         0.006174        0.001104               1.350593                    MODERATE
  Order_Quarter         0.002730        0.001106               0.597306                         LOW
         Region         0.000473        0.001361               0.103398                         LOW
 Country/Region        -0.000490        0.000144               0.000000 NO POSITIVE TEST-SET IMPACT
       Division        -0.000523        0.000094               0.000000 NO POSITIVE TEST-SET IMPACT
          Units        -0.000753        0.000431               0.000000 NO POSITIVE TEST-SET IMPACT
   Gross Profit        -0.000877        0.000454               0.000000 NO POSITIVE TEST-SET IMPACT
           Cost        -0.001922        0.000613               0.000000 NO POSITIVE TEST-SET IMPACT
          Sales        -0.002051        0.000627               0.000000 NO POSITIVE TEST-SET IMPACT
        Factory        -0.004565        0.000941               0.000000 NO POSITIVE TEST-SET IMPACT
   Product Name        -0.005480        0.001121               0.000000 NO POSITIVE TEST-SET IMPACT

======================================================================
STEP 28 VALIDATION
======================================================================
Raw dataset validation: PASSED
Factory mapping validation: PASSED
Date parsing validation: PASSED
Delivery calculation validation: PASSED
Order-level split validation: PASSED
Train-only target threshold validation: PASSED
Feature validation: PASSED
Saved model validation: PASSED
Test ROC-AUC validation: PASSED (0.9013)
Permutation importance calculation: PASSED
Permutation output validation: PASSED

Saved file:
c:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization\results\random_forest_test_permutation_importance.csv

======================================================================
STATUS: STEP 28 COMPLETED SUCCESSFULLY
======================================================================

In [21]:
# ============================================================
# STEP 29 — FINAL BUSINESS IMPACT ANALYSIS
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np


# ============================================================
# 1. Locate project directory
# ============================================================

current_path = Path.cwd()

possible_project_dirs = [
    current_path,
    current_path.parent,
]

project_dir = None

for candidate in possible_project_dirs:
    if (
        (candidate / "results" / "final_factory_reallocation_recommendations.csv").exists()
        and
        (candidate / "data" / "Nassau Candy Distributor.csv").exists()
    ):
        project_dir = candidate
        break

if project_dir is None:
    raise FileNotFoundError(
        "Project directory could not be located.\n"
        "Expected:\n"
        "results/final_factory_reallocation_recommendations.csv\n"
        "data/Nassau Candy Distributor.csv"
    )


# ============================================================
# 2. File paths
# ============================================================

recommendation_path = (
    project_dir
    / "results"
    / "final_factory_reallocation_recommendations.csv"
)

raw_data_path = (
    project_dir
    / "data"
    / "Nassau Candy Distributor.csv"
)

results_dir = project_dir / "results"
results_dir.mkdir(parents=True, exist_ok=True)


print("=" * 70)
print("STEP 29 — FINAL BUSINESS IMPACT ANALYSIS")
print("=" * 70)


# ============================================================
# 3. Load validated recommendation output
# ============================================================

recommendations = pd.read_csv(
    recommendation_path
)

print(f"Recommendation file: {recommendation_path}")
print(f"Recommendation records: {len(recommendations)}")


# ============================================================
# 4. Validate recommendation columns
# ============================================================

required_recommendation_columns = [
    "Product Name",
    "Current Factory",
    "Scenario Factory",
    "Current Slow Probability",
    "Predicted Slow Probability",
    "Probability_Reduction_Percentage_Points",
    "ML_Signal",
    "Final_Action",
    "Records",
    "Orders",
    "Sales",
    "Units",
    "Gross_Profit",
    "Estimated_Avoided_Slow_Records"
]

missing_columns = [
    col
    for col in required_recommendation_columns
    if col not in recommendations.columns
]

if missing_columns:
    raise ValueError(
        f"Missing recommendation columns: {missing_columns}"
    )


# ============================================================
# 5. Validate 15-product structure
# ============================================================

if len(recommendations) != 15:
    raise ValueError(
        f"Expected 15 recommendation records, "
        f"found {len(recommendations)}."
    )

if recommendations["Product Name"].nunique() != 15:
    raise ValueError(
        "Expected 15 unique products in final recommendations."
    )

if recommendations["Product Name"].duplicated().any():
    raise ValueError(
        "Duplicate product recommendation detected."
    )


# ============================================================
# 6. Validate probability values
# ============================================================

probability_columns = [
    "Current Slow Probability",
    "Predicted Slow Probability"
]

for column in probability_columns:

    values = pd.to_numeric(
        recommendations[column],
        errors="coerce"
    )

    if values.isna().any():
        raise ValueError(
            f"Invalid probability values found in {column}."
        )

    if ((values < 0) | (values > 1)).any():
        raise ValueError(
            f"Probability outside 0-1 range found in {column}."
        )


# ============================================================
# 7. Recalculate probability improvement independently
# ============================================================

recalculated_improvement = (
    recommendations["Current Slow Probability"]
    - recommendations["Predicted Slow Probability"]
) * 100

saved_improvement = pd.to_numeric(
    recommendations[
        "Probability_Reduction_Percentage_Points"
    ],
    errors="coerce"
)

if saved_improvement.isna().any():
    raise ValueError(
        "Invalid Probability_Reduction_Percentage_Points values."
    )

if not np.allclose(
    recalculated_improvement,
    saved_improvement,
    atol=1e-6
):
    raise ValueError(
        "Probability improvement values are inconsistent "
        "with source probabilities."
    )


# ============================================================
# 8. Validate factory scenarios
# ============================================================

if (
    recommendations["Current Factory"]
    == recommendations["Scenario Factory"]
).any():
    raise ValueError(
        "Current Factory and Scenario Factory cannot be identical."
    )


# ============================================================
# 9. Validate business metrics
# ============================================================

business_columns = [
    "Records",
    "Orders",
    "Sales",
    "Units",
    "Gross_Profit",
    "Estimated_Avoided_Slow_Records"
]

for column in business_columns:

    recommendations[column] = pd.to_numeric(
        recommendations[column],
        errors="coerce"
    )

    if recommendations[column].isna().any():
        raise ValueError(
            f"Invalid numeric values found in {column}."
        )


# ============================================================
# 10. Validate categorical recommendation fields
# ============================================================

allowed_ml_signals = {
    "CONSIDER REALLOCATION",
    "NO STRONG ML SIGNAL"
}

allowed_final_actions = {
    "CONSIDER PILOT REALLOCATION",
    "KEEP CURRENT FACTORY"
}

invalid_ml_signals = set(
    recommendations["ML_Signal"]
) - allowed_ml_signals

if invalid_ml_signals:
    raise ValueError(
        f"Unexpected ML signal values: {invalid_ml_signals}"
    )

invalid_final_actions = set(
    recommendations["Final_Action"]
) - allowed_final_actions

if invalid_final_actions:
    raise ValueError(
        f"Unexpected final action values: {invalid_final_actions}"
    )


# ============================================================
# 11. Business-level summary
# ============================================================

total_products = recommendations["Product Name"].nunique()

pilot_products = int(
    (
        recommendations["Final_Action"]
        == "CONSIDER PILOT REALLOCATION"
    ).sum()
)

keep_products = int(
    (
        recommendations["Final_Action"]
        == "KEEP CURRENT FACTORY"
    ).sum()
)

ml_signal_products = int(
    (
        recommendations["ML_Signal"]
        == "CONSIDER REALLOCATION"
    ).sum()
)

no_signal_products = int(
    (
        recommendations["ML_Signal"]
        == "NO STRONG ML SIGNAL"
    ).sum()
)

total_records = int(
    recommendations["Records"].sum()
)

total_orders = int(
    recommendations["Orders"].sum()
)

total_sales = float(
    recommendations["Sales"].sum()
)

total_units = int(
    recommendations["Units"].sum()
)

total_gross_profit = float(
    recommendations["Gross_Profit"].sum()
)

estimated_avoided_slow_records = float(
    recommendations[
        "Estimated_Avoided_Slow_Records"
    ].sum()
)

average_probability_improvement = float(
    recommendations[
        "Probability_Reduction_Percentage_Points"
    ].mean()
)

maximum_probability_improvement = float(
    recommendations[
        "Probability_Reduction_Percentage_Points"
    ].max()
)

minimum_probability_improvement = float(
    recommendations[
        "Probability_Reduction_Percentage_Points"
    ].min()
)


# ============================================================
# 12. Best and weakest ML scenarios
# ============================================================

best_row = recommendations.loc[
    recommendations[
        "Probability_Reduction_Percentage_Points"
    ].idxmax()
]

worst_row = recommendations.loc[
    recommendations[
        "Probability_Reduction_Percentage_Points"
    ].idxmin()
]


# ============================================================
# 13. Create management summary table
# ============================================================

business_summary = pd.DataFrame({
    "Metric": [
        "Products Evaluated",
        "Products with ML Reallocation Signal",
        "Products Recommended for Pilot",
        "Products Recommended to Keep Current Factory",
        "Total Records Covered",
        "Total Orders Covered",
        "Total Sales Covered",
        "Total Units Covered",
        "Total Gross Profit Covered",
        "Estimated Avoided Slow Records",
        "Average Probability Improvement (pp)",
        "Maximum Probability Improvement (pp)",
        "Minimum Probability Improvement (pp)"
    ],
    "Value": [
        total_products,
        ml_signal_products,
        pilot_products,
        keep_products,
        total_records,
        total_orders,
        round(total_sales, 2),
        total_units,
        round(total_gross_profit, 2),
        round(estimated_avoided_slow_records, 2),
        round(average_probability_improvement, 4),
        round(maximum_probability_improvement, 4),
        round(minimum_probability_improvement, 4)
    ]
})


# ============================================================
# 14. Create priority table
# ============================================================

priority_columns = [
    "Product Name",
    "Current Factory",
    "Scenario Factory",
    "Current Slow Probability",
    "Predicted Slow Probability",
    "Probability_Reduction_Percentage_Points",
    "ML_Signal",
    "Final_Action",
    "Records",
    "Orders",
    "Sales",
    "Units",
    "Gross_Profit",
    "Estimated_Avoided_Slow_Records"
]

priority_table = (
    recommendations[
        priority_columns
    ]
    .sort_values(
        "Probability_Reduction_Percentage_Points",
        ascending=False
    )
    .reset_index(drop=True)
)


# ============================================================
# 15. Save business outputs
# ============================================================

summary_path = (
    results_dir
    / "final_business_impact_summary.csv"
)

priority_path = (
    results_dir
    / "final_business_priority_table.csv"
)

business_summary.to_csv(
    summary_path,
    index=False
)

priority_table.to_csv(
    priority_path,
    index=False
)


# ============================================================
# 16. Display results
# ============================================================

print("\n" + "=" * 70)
print("BUSINESS SUMMARY")
print("=" * 70)

print(
    business_summary.to_string(index=False)
)


print("\n" + "=" * 70)
print("TOP RECOMMENDATION SCENARIO")
print("=" * 70)

print(
    f"Product          : {best_row['Product Name']}"
)
print(
    f"Current Factory  : {best_row['Current Factory']}"
)
print(
    f"Scenario Factory : {best_row['Scenario Factory']}"
)
print(
    f"Probability Drop : "
    f"{best_row['Probability_Reduction_Percentage_Points']:.4f} pp"
)
print(
    f"Final Action     : {best_row['Final_Action']}"
)


print("\n" + "=" * 70)
print("LOWEST-SCORING SCENARIO")
print("=" * 70)

print(
    f"Product          : {worst_row['Product Name']}"
)
print(
    f"Current Factory  : {worst_row['Current Factory']}"
)
print(
    f"Scenario Factory : {worst_row['Scenario Factory']}"
)
print(
    f"Probability Change: "
    f"{worst_row['Probability_Reduction_Percentage_Points']:.4f} pp"
)
print(
    f"Final Action     : {worst_row['Final_Action']}"
)


print("\n" + "=" * 70)
print("TOP 15 PRODUCT RECOMMENDATIONS")
print("=" * 70)

print(
    priority_table[
        [
            "Product Name",
            "Current Factory",
            "Scenario Factory",
            "Probability_Reduction_Percentage_Points",
            "ML_Signal",
            "Final_Action"
        ]
    ]
    .to_string(index=False)
)


# ============================================================
# 17. Final validation
# ============================================================

print("\n" + "=" * 70)
print("STEP 29 VALIDATION")
print("=" * 70)

print("Recommendation file validation: PASSED")
print("15-product validation: PASSED")
print("Probability validation: PASSED")
print("Probability improvement validation: PASSED")
print("Factory scenario validation: PASSED")
print("Business metric validation: PASSED")
print("ML signal validation: PASSED")
print("Final action validation: PASSED")
print("Business summary generation: PASSED")
print("Priority table generation: PASSED")

print("\nSaved files:")
print(summary_path)
print(priority_path)

print("\n" + "=" * 70)
print("STATUS: STEP 29 COMPLETED SUCCESSFULLY")
print("=" * 70)

======================================================================
STEP 29 — FINAL BUSINESS IMPACT ANALYSIS
======================================================================
Recommendation file: c:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization\results\final_factory_reallocation_recommendations.csv
Recommendation records: 15

======================================================================
BUSINESS SUMMARY
======================================================================
                                      Metric       Value
                          Products Evaluated     15.0000
        Products with ML Reallocation Signal      0.0000
              Products Recommended for Pilot      0.0000
Products Recommended to Keep Current Factory     15.0000
                       Total Records Covered  10194.0000
                        Total Orders Covered   8549.0000
                         Total Sales Covered 141783.6300
                         Total Units Covered  38654.0000
                  Total Gross Profit Covered  93442.8000
              Estimated Avoided Slow Records     74.5900
        Average Probability Improvement (pp)      0.8446
        Maximum Probability Improvement (pp)      2.5879
        Minimum Probability Improvement (pp)     -0.7975

======================================================================
TOP RECOMMENDATION SCENARIO
======================================================================
Product          : Everlasting Gobstopper
Current Factory  : Secret Factory
Scenario Factory : The Other Factory
Probability Drop : 2.5879 pp
Final Action     : KEEP CURRENT FACTORY

======================================================================
LOWEST-SCORING SCENARIO
======================================================================
Product          : Kazookles
Current Factory  : The Other Factory
Scenario Factory : Lot's O' Nuts
Probability Change: -0.7975 pp
Final Action     : KEEP CURRENT FACTORY

======================================================================
TOP 15 PRODUCT RECOMMENDATIONS
======================================================================
                     Product Name   Current Factory  Scenario Factory  Probability_Reduction_Percentage_Points           ML_Signal         Final_Action
           Everlasting Gobstopper    Secret Factory The Other Factory                                 2.587866 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
             Fizzy Lifting Drinks       Sugar Shack The Other Factory                                 1.442872 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                      Laffy Taffy       Sugar Shack The Other Factory                                 1.368241 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
               Lickable Wallpaper    Secret Factory The Other Factory                                 1.223438 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                        Wonka Gum    Secret Factory The Other Factory                                 1.209590 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                        SweeTARTS       Sugar Shack The Other Factory                                 1.205417 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
       Wonka Bar - Milk Chocolate   Wicked Choccy's The Other Factory                                 0.975803 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                            Nerds       Sugar Shack The Other Factory                                 0.925209 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
Wonka Bar - Triple Dazzle Caramel   Wicked Choccy's The Other Factory                                 0.716562 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
        Wonka Bar - Fudge Mallows     Lot's O' Nuts The Other Factory                                 0.690892 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
Wonka Bar - Nutty Crunch Surprise     Lot's O' Nuts The Other Factory                                 0.651918 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
   Wonka Bar -Scrumdiddlyumptious     Lot's O' Nuts The Other Factory                                 0.612666 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                      Hair Toffee The Other Factory   Wicked Choccy's                                 0.029973 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                          Fun Dip       Sugar Shack     Lot's O' Nuts                                -0.173814 NO STRONG ML SIGNAL KEEP CURRENT FACTORY
                        Kazookles The Other Factory     Lot's O' Nuts                                -0.797484 NO STRONG ML SIGNAL KEEP CURRENT FACTORY

======================================================================
STEP 29 VALIDATION
======================================================================
Recommendation file validation: PASSED
15-product validation: PASSED
Probability validation: PASSED
Probability improvement validation: PASSED
Factory scenario validation: PASSED
Business metric validation: PASSED
ML signal validation: PASSED
Final action validation: PASSED
Business summary generation: PASSED
Priority table generation: PASSED

Saved files:
c:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization\results\final_business_impact_summary.csv
c:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization\results\final_business_priority_table.csv

======================================================================
STATUS: STEP 29 COMPLETED SUCCESSFULLY
======================================================================

In [2]:
# ============================================================
# STEP 30 — FINAL PROJECT INTEGRITY & SUBMISSION AUDIT
# CORRECTED VERSION
# ============================================================

from pathlib import Path
import json
import pandas as pd
import numpy as np
import sys

print("=" * 70)
print("STEP 30 — FINAL PROJECT INTEGRITY & SUBMISSION AUDIT")
print("=" * 70)

# ------------------------------------------------------------
# 1. FIND PROJECT DIRECTORY
# ------------------------------------------------------------

cwd = Path.cwd().resolve()

possible_dirs = [
    cwd,
    cwd.parent,
    cwd.parent.parent
]

project_dir = None

for candidate in possible_dirs:
    if (
        (candidate / "data").is_dir()
        and (candidate / "models").is_dir()
        and (candidate / "results").is_dir()
    ):
        project_dir = candidate
        break

if project_dir is None:
    raise FileNotFoundError(
        "Project directory could not be located. "
        "Expected data/, models/ and results/ folders."
    )

print(f"\nProject directory: {project_dir}")

# ------------------------------------------------------------
# 2. REQUIRED FOLDERS
# ------------------------------------------------------------

required_folders = [
    "data",
    "models",
    "results",
    "notebooks"
]

print("\n" + "=" * 70)
print("FOLDER VALIDATION")
print("=" * 70)

for folder in required_folders:
    folder_path = project_dir / folder

    if not folder_path.is_dir():
        raise FileNotFoundError(
            f"Required folder missing: {folder_path}"
        )

    print(f"{folder:<15}: PASSED")

# ------------------------------------------------------------
# 3. REQUIRED CORE FILES
# ------------------------------------------------------------

required_files = {
    "Raw dataset":
        project_dir / "data" / "Nassau Candy Distributor.csv",

    "Saved ML model":
        project_dir / "models" / "nassau_slow_shipment_model.joblib",

    "Model metadata":
        project_dir / "models" / "nassau_slow_shipment_model_metadata.json",

    "Factory scenarios":
        project_dir / "results" / "factory_reallocation_scenarios.csv",

    "Factory recommendations":
        project_dir / "results" / "factory_reallocation_recommendations.csv",

    "Final recommendations":
        project_dir / "results" / "final_factory_reallocation_recommendations.csv",

    "Feature importance":
        project_dir / "results" / "random_forest_feature_importance.csv",

    "Permutation importance":
        project_dir / "results" / "random_forest_test_permutation_importance.csv",

    "Business impact summary":
        project_dir / "results" / "final_business_impact_summary.csv",

    "Business priority table":
        project_dir / "results" / "final_business_priority_table.csv",
}

print("\n" + "=" * 70)
print("CORE FILE VALIDATION")
print("=" * 70)

for label, path in required_files.items():

    if not path.is_file():
        raise FileNotFoundError(
            f"Required file missing: {path}"
        )

    size = path.stat().st_size

    if size <= 0:
        raise ValueError(
            f"Required file is empty: {path}"
        )

    print(f"{label:<28}: PASSED ({size:,} bytes)")

# ------------------------------------------------------------
# 4. RAW DATASET VALIDATION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("RAW DATASET VALIDATION")
print("=" * 70)

raw_path = required_files["Raw dataset"]

raw_df = pd.read_csv(raw_path)

expected_raw_columns = [
    "Row ID",
    "Order ID",
    "Order Date",
    "Ship Date",
    "Ship Mode",
    "Customer ID",
    "Country/Region",
    "City",
    "State/Province",
    "Postal Code",
    "Division",
    "Region",
    "Product ID",
    "Product Name",
    "Sales",
    "Units",
    "Gross Profit",
    "Cost"
]

missing_raw_columns = [
    col for col in expected_raw_columns
    if col not in raw_df.columns
]

if missing_raw_columns:
    raise ValueError(
        f"Raw dataset missing columns: {missing_raw_columns}"
    )

if len(raw_df) != 10194:
    raise ValueError(
        f"Unexpected raw dataset row count: {len(raw_df)}. "
        f"Expected 10194."
    )

if raw_df.shape[1] != 18:
    raise ValueError(
        f"Unexpected raw dataset column count: "
        f"{raw_df.shape[1]}. Expected 18."
    )

if raw_df.isna().sum().sum() != 0:
    raise ValueError(
        "Raw dataset contains missing values."
    )

if raw_df.duplicated().sum() != 0:
    raise ValueError(
        "Raw dataset contains duplicate rows."
    )

print(f"Rows       : {len(raw_df):,}")
print(f"Columns    : {raw_df.shape[1]}")
print("Missing    : 0")
print("Duplicates : 0")
print("STATUS     : PASSED")

# ------------------------------------------------------------
# 5. MODEL METADATA VALIDATION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("MODEL METADATA VALIDATION")
print("=" * 70)

metadata_path = required_files["Model metadata"]

with open(metadata_path, "r", encoding="utf-8") as f:
    metadata = json.load(f)

if not isinstance(metadata, dict):
    raise ValueError(
        "Model metadata must be a JSON dictionary/object."
    )

print("Metadata format : PASSED")
print(f"Metadata keys   : {len(metadata)}")

# ------------------------------------------------------------
# 6. ACTUAL PROJECT ML FEATURES
# ------------------------------------------------------------
# IMPORTANT:
# The trained model uses EXACTLY 15 input features.
# The target is NOT included here.

expected_ml_features = [
    "Product Name",
    "Division",
    "Country/Region",
    "State/Province",
    "Region",
    "Factory",
    "Ship Mode",
    "Units",
    "Sales",
    "Cost",
    "Gross Profit",
    "Order_Year",
    "Order_Month",
    "Order_Quarter",
    "Order_DayOfWeek"
]

EXPECTED_FEATURE_COUNT = len(expected_ml_features)

print("\n" + "=" * 70)
print("ML FEATURE DEFINITION")
print("=" * 70)

print(f"Expected ML input features: {EXPECTED_FEATURE_COUNT}")

for i, feature in enumerate(expected_ml_features, start=1):
    print(f"{i:02d}. {feature}")

if EXPECTED_FEATURE_COUNT != 15:
    raise ValueError(
        "Internal project feature definition error. "
        "Expected exactly 15 ML input features."
    )

print("\nML feature definition: PASSED")

# ------------------------------------------------------------
# 7. FINAL RECOMMENDATIONS VALIDATION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL RECOMMENDATION VALIDATION")
print("=" * 70)

final_path = required_files["Final recommendations"]

final_df = pd.read_csv(final_path)

required_final_columns = [
    "Product Name",
    "Current Factory",
    "Scenario Factory",
    "Current Slow Probability",
    "Predicted Slow Probability",
    "Probability_Reduction_Percentage_Points",
    "Estimated_Avoided_Slow_Records",
    "ML_Signal",
    "Final_Action"
]

missing_final_columns = [
    col for col in required_final_columns
    if col not in final_df.columns
]

if missing_final_columns:
    raise ValueError(
        f"Final recommendation file missing columns: "
        f"{missing_final_columns}"
    )

if len(final_df) != 15:
    raise ValueError(
        f"Final recommendation rows = {len(final_df)}. "
        f"Expected exactly 15."
    )

if final_df["Product Name"].nunique() != 15:
    raise ValueError(
        "Final recommendations do not contain exactly "
        "15 unique products."
    )

if final_df.duplicated(subset=["Product Name"]).any():
    raise ValueError(
        "Duplicate product recommendations detected."
    )

if (
    final_df["Current Factory"]
    == final_df["Scenario Factory"]
).any():
    raise ValueError(
        "At least one recommendation uses the same "
        "current and scenario factory."
    )

# Probability validation
probability_columns = [
    "Current Slow Probability",
    "Predicted Slow Probability"
]

for col in probability_columns:

    values = pd.to_numeric(
        final_df[col],
        errors="coerce"
    )

    if values.isna().any():
        raise ValueError(
            f"Non-numeric probability values found in {col}."
        )

    if ((values < 0) | (values > 1)).any():
        raise ValueError(
            f"Probability outside 0-1 range found in {col}."
        )

# Recalculate probability reduction from source probabilities
expected_reduction = (
    final_df["Current Slow Probability"]
    - final_df["Predicted Slow Probability"]
) * 100

actual_reduction = pd.to_numeric(
    final_df["Probability_Reduction_Percentage_Points"],
    errors="coerce"
)

if actual_reduction.isna().any():
    raise ValueError(
        "Invalid values found in "
        "Probability_Reduction_Percentage_Points."
    )

max_difference = (
    expected_reduction - actual_reduction
).abs().max()

if max_difference > 1e-6:
    raise ValueError(
        "Probability reduction validation failed. "
        f"Maximum difference = {max_difference}"
    )

print(f"Final recommendations : {len(final_df)}")
print("15-product check       : PASSED")
print("Duplicate check        : PASSED")
print("Probability range      : PASSED")
print("Probability reduction  : PASSED")
print("Factory scenario       : PASSED")

# ------------------------------------------------------------
# 8. BUSINESS METRIC VALIDATION
# ------------------------------------------------------------

business_numeric_columns = [
    "Sales",
    "Units",
    "Gross Profit",
    "Estimated_Avoided_Slow_Records"
]

# Only validate columns that are actually present.
for col in business_numeric_columns:

    if col in final_df.columns:

        numeric_values = pd.to_numeric(
            final_df[col],
            errors="coerce"
        )

        if numeric_values.isna().any():
            raise ValueError(
                f"Invalid numeric values found in {col}."
            )

print("Business metrics       : PASSED")

# ------------------------------------------------------------
# 9. ML SIGNAL / ACTION VALIDATION
# ------------------------------------------------------------

allowed_signals = {
    "CONSIDER REALLOCATION",
    "NO STRONG ML SIGNAL"
}

allowed_actions = {
    "PILOT REALLOCATION",
    "KEEP CURRENT FACTORY"
}

actual_signals = set(
    final_df["ML_Signal"].dropna().astype(str)
)

actual_actions = set(
    final_df["Final_Action"].dropna().astype(str)
)

invalid_signals = actual_signals - allowed_signals
invalid_actions = actual_actions - allowed_actions

if invalid_signals:
    raise ValueError(
        f"Unexpected ML signals: {invalid_signals}"
    )

if invalid_actions:
    raise ValueError(
        f"Unexpected final actions: {invalid_actions}"
    )

print("ML signal validation    : PASSED")
print("Final action validation : PASSED")

# ------------------------------------------------------------
# 10. FEATURE IMPORTANCE VALIDATION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("MODEL EXPLAINABILITY OUTPUT VALIDATION")
print("=" * 70)

feature_importance_path = required_files["Feature importance"]
permutation_path = required_files["Permutation importance"]

feature_importance_df = pd.read_csv(
    feature_importance_path
)

permutation_importance_df = pd.read_csv(
    permutation_path
)

if feature_importance_df.empty:
    raise ValueError(
        "Feature importance output is empty."
    )

if permutation_importance_df.empty:
    raise ValueError(
        "Permutation importance output is empty."
    )

print(
    f"Feature importance rows     : "
    f"{len(feature_importance_df)}"
)

print(
    f"Permutation importance rows : "
    f"{len(permutation_importance_df)}"
)

# ------------------------------------------------------------
# 11. CORRECT PERMUTATION FEATURE VALIDATION
# ------------------------------------------------------------
# NO HARD-CODED 16.
# The expected count is derived from the actual project
# feature definition above.

# Find the feature-name column safely.
feature_column_candidates = [
    col for col in permutation_importance_df.columns
    if col.strip().lower() in {
        "feature",
        "features",
        "feature name",
        "feature_name"
    }
]

if not feature_column_candidates:
    raise ValueError(
        "Could not identify the feature-name column "
        "in permutation importance output."
    )

permutation_feature_column = feature_column_candidates[0]

permutation_features = (
    permutation_importance_df[
        permutation_feature_column
    ]
    .dropna()
    .astype(str)
    .str.strip()
)

# No duplicate feature names
if permutation_features.duplicated().any():
    duplicates = (
        permutation_features[
            permutation_features.duplicated()
        ]
        .unique()
        .tolist()
    )

    raise ValueError(
        f"Duplicate permutation-importance features: {duplicates}"
    )

actual_permutation_feature_count = (
    permutation_features.nunique()
)

# THIS IS THE IMPORTANT FIX:
if actual_permutation_feature_count != EXPECTED_FEATURE_COUNT:
    raise ValueError(
        "Permutation importance feature count mismatch. "
        f"Expected {EXPECTED_FEATURE_COUNT} actual ML input "
        f"features, but found "
        f"{actual_permutation_feature_count}."
    )

# Check exact feature names
expected_feature_set = set(expected_ml_features)
actual_feature_set = set(permutation_features)

missing_features = sorted(
    expected_feature_set - actual_feature_set
)

unexpected_features = sorted(
    actual_feature_set - expected_feature_set
)

if missing_features:
    raise ValueError(
        f"Permutation importance is missing features: "
        f"{missing_features}"
    )

if unexpected_features:
    raise ValueError(
        f"Permutation importance contains unexpected "
        f"features: {unexpected_features}"
    )

print(
    f"Expected ML features       : "
    f"{EXPECTED_FEATURE_COUNT}"
)

print(
    f"Permutation features found : "
    f"{actual_permutation_feature_count}"
)

print("Feature-name check         : PASSED")
print("Permutation importance     : PASSED")

# ------------------------------------------------------------
# 12. NOTEBOOK VALIDATION
# ------------------------------------------------------------

notebook_files = list(
    (project_dir / "notebooks").glob("*.ipynb")
)

if len(notebook_files) == 0:
    raise FileNotFoundError(
        "No Jupyter notebook found in notebooks folder."
    )

print("\n" + "=" * 70)
print("NOTEBOOK VALIDATION")
print("=" * 70)

print(
    f"Jupyter notebooks found : {len(notebook_files)}"
)

for notebook in notebook_files:
    print(f"PASSED : {notebook.name}")

# ------------------------------------------------------------
# 13. FINAL PROJECT FILE INVENTORY
# ------------------------------------------------------------

inventory_rows = []

for label, path in required_files.items():

    inventory_rows.append({
        "Category": label,
        "File": str(path.relative_to(project_dir)),
        "Exists": path.exists(),
        "Size_Bytes": path.stat().st_size
    })

inventory_df = pd.DataFrame(inventory_rows)

inventory_path = (
    project_dir
    / "results"
    / "final_project_file_inventory.csv"
)

inventory_df.to_csv(
    inventory_path,
    index=False
)

if not inventory_path.is_file():
    raise IOError(
        "Final project file inventory was not created."
    )

print("\n" + "=" * 70)
print("FINAL PROJECT FILE INVENTORY")
print("=" * 70)

print(
    inventory_df.to_string(index=False)
)

# ------------------------------------------------------------
# 14. FINAL STATUS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL INTEGRITY RESULT")
print("=" * 70)

print("Raw dataset validation       : PASSED")
print("Core files validation        : PASSED")
print("Model metadata validation    : PASSED")
print("Final recommendations        : PASSED")
print("Business metrics             : PASSED")
print("ML signals/actions           : PASSED")
print("Feature importance           : PASSED")
print("Permutation importance       : PASSED")
print("Notebook validation          : PASSED")
print("File inventory               : PASSED")

print("\n" + "=" * 70)
print("STATUS: STEP 30 COMPLETED SUCCESSFULLY")
print("=" * 70)

print(
    "\nIMPORTANT METHODOLOGY NOTE:"
)

print(
    "Factory reallocation recommendations are "
    "ML-based counterfactual screening results, "
    "not causal estimates."
)

print(
    "No transportation-cost savings are claimed "
    "because verified factory coordinates/cost data "
    "are unavailable."
)

print(
    "\nProject integrity audit completed successfully."
)

======================================================================
STEP 30 — FINAL PROJECT INTEGRITY & SUBMISSION AUDIT
======================================================================

Project directory: C:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization

======================================================================
FOLDER VALIDATION
======================================================================
data           : PASSED
models         : PASSED
results        : PASSED
notebooks      : PASSED

======================================================================
CORE FILE VALIDATION
======================================================================
Raw dataset                 : PASSED (1,979,595 bytes)
Saved ML model              : PASSED (27,926,571 bytes)
Model metadata              : PASSED (764 bytes)
Factory scenarios           : PASSED (11,218 bytes)
Factory recommendations     : PASSED (2,423 bytes)
Final recommendations       : PASSED (4,078 bytes)
Feature importance          : PASSED (816 bytes)
Permutation importance      : PASSED (984 bytes)
Business impact summary     : PASSED (484 bytes)
Business priority table     : PASSED (2,680 bytes)

======================================================================
RAW DATASET VALIDATION
======================================================================
Rows       : 10,194
Columns    : 18
Missing    : 0
Duplicates : 0
STATUS     : PASSED

======================================================================
MODEL METADATA VALIDATION
======================================================================
Metadata format : PASSED
Metadata keys   : 8

======================================================================
ML FEATURE DEFINITION
======================================================================
Expected ML input features: 15
01. Product Name
02. Division
03. Country/Region
04. State/Province
05. Region
06. Factory
07. Ship Mode
08. Units
09. Sales
10. Cost
11. Gross Profit
12. Order_Year
13. Order_Month
14. Order_Quarter
15. Order_DayOfWeek

ML feature definition: PASSED

======================================================================
FINAL RECOMMENDATION VALIDATION
======================================================================
Final recommendations : 15
15-product check       : PASSED
Duplicate check        : PASSED
Probability range      : PASSED
Probability reduction  : PASSED
Factory scenario       : PASSED
Business metrics       : PASSED
ML signal validation    : PASSED
Final action validation : PASSED

======================================================================
MODEL EXPLAINABILITY OUTPUT VALIDATION
======================================================================
Feature importance rows     : 15
Permutation importance rows : 15
Expected ML features       : 15
Permutation features found : 15
Feature-name check         : PASSED
Permutation importance     : PASSED

======================================================================
NOTEBOOK VALIDATION
======================================================================
Jupyter notebooks found : 1
PASSED : 01_data_understanding.ipynb

======================================================================
FINAL PROJECT FILE INVENTORY
======================================================================
               Category                                                   File  Exists  Size_Bytes
            Raw dataset                      data\Nassau Candy Distributor.csv    True     1979595
         Saved ML model               models\nassau_slow_shipment_model.joblib    True    27926571
         Model metadata        models\nassau_slow_shipment_model_metadata.json    True         764
      Factory scenarios             results\factory_reallocation_scenarios.csv    True       11218
Factory recommendations       results\factory_reallocation_recommendations.csv    True        2423
  Final recommendations results\final_factory_reallocation_recommendations.csv    True        4078
     Feature importance           results\random_forest_feature_importance.csv    True         816
 Permutation importance  results\random_forest_test_permutation_importance.csv    True         984
Business impact summary              results\final_business_impact_summary.csv    True         484
Business priority table              results\final_business_priority_table.csv    True        2680

======================================================================
FINAL INTEGRITY RESULT
======================================================================
Raw dataset validation       : PASSED
Core files validation        : PASSED
Model metadata validation    : PASSED
Final recommendations        : PASSED
Business metrics             : PASSED
ML signals/actions           : PASSED
Feature importance           : PASSED
Permutation importance       : PASSED
Notebook validation          : PASSED
File inventory               : PASSED

======================================================================
STATUS: STEP 30 COMPLETED SUCCESSFULLY
======================================================================

IMPORTANT METHODOLOGY NOTE:
Factory reallocation recommendations are ML-based counterfactual screening results, not causal estimates.
No transportation-cost savings are claimed because verified factory coordinates/cost data are unavailable.

Project integrity audit completed successfully.

In [4]:
# ============================================================
# STEP 31A — GITHUB-READY PROJECT FILES
# SAFE VERSION
# ============================================================

from pathlib import Path

print("=" * 70)
print("STEP 31A — GITHUB-READY PROJECT FILES")
print("=" * 70)

# ------------------------------------------------------------
# 1. FIND PROJECT DIRECTORY
# ------------------------------------------------------------

current = Path.cwd().resolve()

project_dir = None

for candidate in [current, current.parent, current.parent.parent]:
    if (
        (candidate / "data").is_dir()
        and (candidate / "models").is_dir()
        and (candidate / "results").is_dir()
        and (candidate / "notebooks").is_dir()
    ):
        project_dir = candidate
        break

if project_dir is None:
    raise FileNotFoundError(
        "Could not find Nassau_Candy_Optimization project folder."
    )

print(f"\nProject directory: {project_dir}")

# ------------------------------------------------------------
# 2. VERIFY IMPORTANT EXISTING FILES
# ------------------------------------------------------------

important_files = [
    project_dir / "data" / "Nassau Candy Distributor.csv",
    project_dir / "models" / "nassau_slow_shipment_model.joblib",
    project_dir / "models" / "nassau_slow_shipment_model_metadata.json",
    project_dir / "results" / "final_factory_reallocation_recommendations.csv",
    project_dir / "results" / "final_business_impact_summary.csv",
    project_dir / "results" / "final_business_priority_table.csv",
]

for file_path in important_files:
    if not file_path.is_file():
        raise FileNotFoundError(
            f"Important project file missing: {file_path}"
        )

print("Existing project files: PASSED")

# ------------------------------------------------------------
# 3. README CONTENT
# ------------------------------------------------------------

readme_lines = [
    "# Factory Reallocation & Shipping Optimization Recommendation System",
    "",
    "## Nassau Candy Distributor — E-Commerce Analytics",
    "",
    "A machine learning based decision-support system for identifying slow-shipment risk and evaluating factory reallocation scenarios.",
    "",
    "## Project Overview",
    "",
    "This project analyzes historical order and shipping data and develops a machine learning workflow to predict slow shipments and evaluate alternative factory assignments.",
    "",
    "The project covers:",
    "- Data understanding and validation",
    "- Delivery lead-time analysis",
    "- Product-to-factory mapping",
    "- Customer geography analysis",
    "- Factory-region analysis",
    "- Shipping-mode analysis",
    "- Data leakage auditing",
    "- Machine learning classification",
    "- Model evaluation and selection",
    "- Factory reallocation scenario analysis",
    "- Model explainability",
    "- Business impact analysis",
    "- Final project integrity validation",
    "",
    "## Dataset",
    "",
    "- 10,194 records",
    "- 18 original columns",
    "- 15 products",
    "- 5,044 customers",
    "- 8,549 unique orders",
    "- 3 divisions",
    "- 4 regions",
    "- 4 shipping modes",
    "",
    "## Machine Learning Target",
    "",
    "The target variable is `Slow_Shipment`.",
    "",
    "A shipment is classified as slow when its delivery lead time is greater than the training-set Q3 threshold.",
    "",
    "## ML Features",
    "",
    "The model uses 15 input features:",
    "",
    "1. Product Name",
    "2. Division",
    "3. Country/Region",
    "4. State/Province",
    "5. Region",
    "6. Factory",
    "7. Ship Mode",
    "8. Units",
    "9. Sales",
    "10. Cost",
    "11. Gross Profit",
    "12. Order_Year",
    "13. Order_Month",
    "14. Order_Quarter",
    "15. Order_DayOfWeek",
    "",
    "Direct leakage variables such as Ship Date, Delivery_Days and Slow_Shipment are excluded from model inputs.",
    "",
    "## Train/Test Methodology",
    "",
    "Because multiple records can belong to the same order, an order-level group-aware train/test split was used.",
    "",
    "- Training records: 8,132",
    "- Testing records: 2,062",
    "- Training orders: 6,839",
    "- Testing orders: 1,710",
    "- Order overlap: 0",
    "",
    "## Models Evaluated",
    "",
    "Three classification models were evaluated:",
    "",
    "- Logistic Regression",
    "- Random Forest",
    "- Gradient Boosting",
    "",
    "## Model Performance",
    "",
    "### Logistic Regression",
    "",
    "- Accuracy: 0.7978",
    "- Precision: 0.5070",
    "- Recall: 0.9322",
    "- F1 Score: 0.6568",
    "- ROC-AUC: 0.8863",
    "",
    "### Random Forest",
    "",
    "- Accuracy: 0.8235",
    "- Precision: 0.5457",
    "- Recall: 0.8925",
    "- F1 Score: 0.6773",
    "- ROC-AUC: 0.9013",
    "",
    "### Gradient Boosting",
    "",
    "- Accuracy: 0.8346",
    "- Precision: 0.5868",
    "- Recall: 0.6869",
    "- F1 Score: 0.6329",
    "- ROC-AUC: 0.9043",
    "",
    "## Selected Model",
    "",
    "The final operational model is a Random Forest Classifier.",
    "",
    "Selection prioritized:",
    "1. F1 Score",
    "2. Recall",
    "3. ROC-AUC",
    "",
    "The trained model pipeline is stored in:",
    "",
    "`models/nassau_slow_shipment_model.joblib`",
    "",
    "## Factory Reallocation Analysis",
    "",
    "The system evaluates alternative factory assignments for each product and compares predicted slow-shipment probabilities.",
    "",
    "The analysis includes:",
    "- Current factory",
    "- Scenario factory",
    "- Current slow probability",
    "- Predicted slow probability",
    "- Probability improvement",
    "- ML signal",
    "- Final operational action",
    "",
    "These recommendations are ML-based counterfactual screening results and are not causal estimates.",
    "",
    "## Factory Coordinates",
    "",
    "Verified factory coordinates were not available in the supplied project data.",
    "",
    "Therefore, the project does not invent factory coordinates or claim transportation-cost savings.",
    "",
    "## Model Explainability",
    "",
    "The project includes:",
    "- Random Forest feature importance",
    "- Test-set permutation importance using ROC-AUC",
    "",
    "Permutation importance evaluates the change in model performance when an input feature is shuffled on the held-out test set.",
    "",
    "## Project Structure",
    "",
    "```text",
    "Nassau_Candy_Optimization/",
    "|-- data/",
    "|-- models/",
    "|-- notebooks/",
    "|-- results/",
    "|-- .gitignore",
    "|-- README.md",
    "|-- requirements.txt",
    "```",
    "",
    "## Main Outputs",
    "",
    "- Factory reallocation scenarios",
    "- Factory reallocation recommendations",
    "- Final factory reallocation recommendations",
    "- Random Forest feature importance",
    "- Test-set permutation importance",
    "- Final business impact summary",
    "- Final business priority table",
    "- Final project file inventory",
    "",
    "## Technologies",
    "",
    "- Python",
    "- Pandas",
    "- NumPy",
    "- Scikit-learn",
    "- Joblib",
    "- Jupyter Notebook",
    "- VS Code",
    "- Git",
    "- GitHub",
    "",
    "## Reproducibility",
    "",
    "Install dependencies with:",
    "",
    "`pip install -r requirements.txt`",
    "",
    "Then open:",
    "",
    "`notebooks/01_data_understanding.ipynb`",
    "",
    "## Business Value",
    "",
    "The system helps identify slow-shipment risk and supports investigation of products where alternative factory assignments produce lower predicted slow-shipment probabilities.",
    "",
    "Operational recommendations should be validated against factory capacity, production feasibility, transportation costs, inventory constraints and controlled pilot testing before implementation.",
    "",
    "## Important Limitation",
    "",
    "Factory reallocation results are model-based scenarios, not guaranteed operational outcomes or causal effects.",
    "",
    "Transportation-cost savings are not estimated because verified factory coordinates and transportation-cost data were unavailable.",
    "",
    "## Author",
    "",
    "**Krishna Prajapati**",
    "",
    "Machine Learning | AI & ML | Data Analytics",
]

# ------------------------------------------------------------
# 4. REQUIREMENTS CONTENT
# ------------------------------------------------------------

requirements_lines = [
    "pandas",
    "numpy",
    "scikit-learn==1.9.0",
    "joblib",
    "jupyter",
    "ipykernel",
]

# ------------------------------------------------------------
# 5. GITIGNORE CONTENT
# ------------------------------------------------------------

gitignore_lines = [
    "# Python cache",
    "__pycache__/",
    "*.py[cod]",
    "",
    "# Virtual environments",
    ".venv/",
    "venv/",
    "env/",
    "ENV/",
    "",
    "# Jupyter",
    ".ipynb_checkpoints/",
    "",
    "# VS Code",
    ".vscode/",
    "",
    "# Testing and cache",
    ".pytest_cache/",
    ".mypy_cache/",
    "",
    "# Temporary files",
    "*.tmp",
    "*.temp",
    "*.log",
    "",
    "# Operating system files",
    ".DS_Store",
    "Thumbs.db",
    "",
    "# Environment files",
    ".env",
    ".env.*",
    "",
    "# Private keys and credentials",
    "*.key",
    "*.pem",
]

# ------------------------------------------------------------
# 6. CREATE FILES ONLY IF THEY DO NOT EXIST
# ------------------------------------------------------------

files_to_create = {
    "README.md": "\n".join(readme_lines) + "\n",
    "requirements.txt": "\n".join(requirements_lines) + "\n",
    ".gitignore": "\n".join(gitignore_lines) + "\n",
}

created = []
preserved = []

for filename, content in files_to_create.items():

    file_path = project_dir / filename

    if file_path.exists():
        preserved.append(filename)
    else:
        file_path.write_text(
            content,
            encoding="utf-8"
        )
        created.append(filename)

# ------------------------------------------------------------
# 7. VALIDATE FILES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("GITHUB FILE VALIDATION")
print("=" * 70)

for filename in files_to_create:

    file_path = project_dir / filename

    if not file_path.is_file():
        raise FileNotFoundError(
            f"File creation failed: {filename}"
        )

    if file_path.stat().st_size == 0:
        raise ValueError(
            f"File is empty: {filename}"
        )

    print(
        f"{filename:<20}: PASSED "
        f"({file_path.stat().st_size:,} bytes)"
    )

# ------------------------------------------------------------
# 8. SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 31A SUMMARY")
print("=" * 70)

if created:
    print("\nCreated:")
    for filename in created:
        print(f"  + {filename}")

if preserved:
    print("\nAlready existed — preserved:")
    for filename in preserved:
        print(f"  = {filename}")

print("\nREADME.md           : PASSED")
print("requirements.txt    : PASSED")
print(".gitignore          : PASSED")

print("\n" + "=" * 70)
print("STATUS: STEP 31A COMPLETED SUCCESSFULLY")
print("=" * 70)

======================================================================
STEP 31A — GITHUB-READY PROJECT FILES
======================================================================

Project directory: C:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization
Existing project files: PASSED

======================================================================
GITHUB FILE VALIDATION
======================================================================
README.md           : PASSED (5,094 bytes)
requirements.txt    : PASSED (64 bytes)
.gitignore          : PASSED (382 bytes)

======================================================================
STEP 31A SUMMARY
======================================================================

Created:
  + README.md
  + requirements.txt
  + .gitignore

README.md           : PASSED
requirements.txt    : PASSED
.gitignore          : PASSED

======================================================================
STATUS: STEP 31A COMPLETED SUCCESSFULLY
======================================================================

In [6]:
# ============================================================
# STEP 31B — FINAL GITHUB PRE-PUSH SAFETY AUDIT
# ============================================================

from pathlib import Path
import re
import subprocess
import sys

# ------------------------------------------------------------
# 1. LOCATE PROJECT DIRECTORY
# ------------------------------------------------------------

cwd = Path.cwd().resolve()

possible_dirs = [
    cwd,
    *cwd.parents
]

project_dir = None

for p in possible_dirs:
    if (
        (p / "data" / "Nassau Candy Distributor.csv").exists()
        and (p / "models").exists()
        and (p / "results").exists()
        and (p / "notebooks").exists()
    ):
        project_dir = p
        break

if project_dir is None:
    raise FileNotFoundError(
        "Project directory could not be located automatically."
    )

print("=" * 70)
print("STEP 31B — FINAL GITHUB PRE-PUSH SAFETY AUDIT")
print("=" * 70)
print("Project directory:")
print(project_dir)

# ------------------------------------------------------------
# 2. REQUIRED FILES
# ------------------------------------------------------------

required_files = [
    "README.md",
    "requirements.txt",
    ".gitignore",

    "data/Nassau Candy Distributor.csv",

    "models/nassau_slow_shipment_model.joblib",
    "models/nassau_slow_shipment_model_metadata.json",

    "notebooks/01_data_understanding.ipynb",

    "results/factory_reallocation_scenarios.csv",
    "results/factory_reallocation_recommendations.csv",
    "results/final_factory_reallocation_recommendations.csv",
    "results/random_forest_feature_importance.csv",
    "results/random_forest_transformed_feature_importance.csv",
    "results/random_forest_test_permutation_importance.csv",
    "results/final_business_impact_summary.csv",
    "results/final_business_priority_table.csv",
]

print("\n" + "=" * 70)
print("REQUIRED FILE CHECK")
print("=" * 70)

missing_files = []

for relative_path in required_files:
    path = project_dir / relative_path

    if path.exists() and path.is_file():
        print(f"[PASSED] {relative_path}")
    else:
        print(f"[MISSING] {relative_path}")
        missing_files.append(relative_path)

if missing_files:
    raise FileNotFoundError(
        "Required project files are missing:\n"
        + "\n".join(missing_files)
    )

print("Required file check: PASSED")

# ------------------------------------------------------------
# 3. FILE SIZE AUDIT
# GitHub hard limit = 100 MiB
# Warning threshold = 50 MiB
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FILE SIZE AUDIT")
print("=" * 70)

GITHUB_HARD_LIMIT = 100 * 1024 * 1024
WARNING_LIMIT = 50 * 1024 * 1024

large_files = []
warning_files = []

for relative_path in required_files:
    path = project_dir / relative_path
    size_bytes = path.stat().st_size
    size_mb = size_bytes / (1024 * 1024)

    if size_bytes > GITHUB_HARD_LIMIT:
        status = "BLOCKED"
        large_files.append(relative_path)

    elif size_bytes > WARNING_LIMIT:
        status = "WARNING"
        warning_files.append(relative_path)

    else:
        status = "OK"

    print(f"{relative_path:<65} {size_mb:>8.2f} MB  {status}")

if large_files:
    raise ValueError(
        "One or more required files exceed GitHub's 100 MiB limit:\n"
        + "\n".join(large_files)
    )

if warning_files:
    print("\nWarning: files above 50 MiB:")
    for item in warning_files:
        print(" -", item)

print("\nFile size audit: PASSED")

# ------------------------------------------------------------
# 4. .GITIGNORE AUDIT
# ------------------------------------------------------------

print("\n" + "=" * 70)
print(".GITIGNORE AUDIT")
print("=" * 70)

gitignore_path = project_dir / ".gitignore"

gitignore_text = gitignore_path.read_text(
    encoding="utf-8",
    errors="replace"
)

required_ignore_patterns = [
    ".venv/",
    "__pycache__/",
    ".ipynb_checkpoints/",
    ".env",
    ".env.*",
]

missing_ignore_patterns = []

for pattern in required_ignore_patterns:
    if pattern not in gitignore_text:
        missing_ignore_patterns.append(pattern)

    else:
        print(f"[PASSED] {pattern}")

if missing_ignore_patterns:
    raise ValueError(
        "Required .gitignore patterns are missing:\n"
        + "\n".join(missing_ignore_patterns)
    )

print(".gitignore audit: PASSED")

# ------------------------------------------------------------
# 5. DEFINE FILES THAT ARE SAFE TO SCAN
#
# IMPORTANT:
# Do NOT recursively scan .venv or installed packages.
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CREDENTIAL SAFETY SCAN")
print("=" * 70)

scan_extensions = {
    ".py",
    ".ipynb",
    ".json",
    ".txt",
    ".md",
    ".yml",
    ".yaml",
    ".toml",
    ".ini",
    ".cfg",
    ".conf",
}

excluded_directories = {
    ".venv",
    "venv",
    "env",
    "ENV",
    ".git",
    "__pycache__",
    ".ipynb_checkpoints",
    ".pytest_cache",
    ".mypy_cache",
    "node_modules",
    "dist",
    "build",
}

files_to_scan = []

for path in project_dir.rglob("*"):

    if not path.is_file():
        continue

    # Ignore excluded directories
    if any(part in excluded_directories for part in path.parts):
        continue

    # Ignore very large/binary files
    if path.suffix.lower() not in scan_extensions:
        continue

    files_to_scan.append(path)

print("Files selected for safety scan:", len(files_to_scan))

# ------------------------------------------------------------
# 6. HIGH-CONFIDENCE SECRET PATTERNS
#
# Generic words such as "api_key" alone are NOT considered
# a credential.
# ------------------------------------------------------------

secret_patterns = [

    # OpenAI-style secret key
    (
        "OpenAI-style API key",
        re.compile(r"\bsk-[A-Za-z0-9_-]{20,}\b")
    ),

    # GitHub personal access token
    (
        "GitHub token",
        re.compile(r"\bgh[pousr]_[A-Za-z0-9_]{20,}\b")
    ),

    # AWS access key
    (
        "AWS access key",
        re.compile(r"\bAKIA[0-9A-Z]{16}\b")
    ),

    # Private key block
    (
        "Private key block",
        re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----")
    ),

    # Bearer token with a substantial token value
    (
        "Bearer token",
        re.compile(
            r"(?i)\bbearer\s+[A-Za-z0-9._-]{30,}\b"
        )
    ),

    # URL containing username/password credentials
    (
        "Credential-containing URL",
        re.compile(
            r"https?://[^/\s:@]+:[^/\s@]+@"
        )
    ),

    # High-confidence assignment pattern.
    # Placeholder values are explicitly excluded.
    (
        "Hard-coded secret assignment",
        re.compile(
            r"""(?ix)
            \b(api[_-]?key|secret[_-]?key|access[_-]?token|
               auth[_-]?token|password)
            \b
            \s*[:=]\s*
            ["']
            (?!your[_-]?api[_-]?key
               |your[_-]?password
               |your[_-]?token
               |change[_-]?me
               |replace[_-]?me
               |example
               |placeholder
               |none
               |null
               |xxx+
               |\*+)
            [^"']{12,}
            ["']
            """
        )
    ),
]

secret_hits = []

# ------------------------------------------------------------
# 7. SCAN ONLY PROJECT-RELEVANT TEXT FILES
# ------------------------------------------------------------

for path in files_to_scan:

    try:
        text = path.read_text(
            encoding="utf-8",
            errors="replace"
        )
    except Exception:
        continue

    lines = text.splitlines()

    for line_number, line in enumerate(lines, start=1):

        for description, pattern in secret_patterns:

            if pattern.search(line):

                relative_path = path.relative_to(project_dir)

                secret_hits.append(
                    (
                        str(relative_path),
                        line_number,
                        description,
                        line.strip()
                    )
                )

# ------------------------------------------------------------
# 8. REPORT RESULT
# ------------------------------------------------------------

if secret_hits:

    print("\nPotential high-confidence credential content found:")

    for file_name, line_number, description, line in secret_hits:
        print("\nFile:", file_name)
        print("Line:", line_number)
        print("Type:", description)

        # Do NOT print the full possible secret.
        # Mask suspicious-looking long values.
        masked_line = re.sub(
            r'([A-Za-z0-9_\-]{8})[A-Za-z0-9_\-]{8,}',
            r'\1********',
            line
        )

        print("Content:", masked_line)

    raise ValueError(
        "\nCredential safety scan FAILED. "
        "Review the listed project files before pushing."
    )

else:
    print("High-confidence credential scan: PASSED")
    print("No high-confidence API key/token/private-key pattern detected.")

# ------------------------------------------------------------
# 9. CHECK GIT INSTALLATION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("GIT ENVIRONMENT CHECK")
print("=" * 70)

try:
    git_version = subprocess.check_output(
        ["git", "--version"],
        text=True,
        stderr=subprocess.STDOUT
    ).strip()

    print("Git:", git_version)
    git_installed = True

except Exception:
    print("Git: NOT FOUND")
    git_installed = False

# ------------------------------------------------------------
# 10. CHECK WHETHER REPOSITORY ALREADY EXISTS
# ------------------------------------------------------------

git_dir = project_dir / ".git"

if git_dir.exists() and git_dir.is_dir():

    print("Git repository: EXISTS")

    try:
        remote_output = subprocess.check_output(
            ["git", "remote", "-v"],
            cwd=project_dir,
            text=True,
            stderr=subprocess.STDOUT
        ).strip()

        if remote_output:
            print("Git remote:")
            print(remote_output)
        else:
            print("Git remote: NOT CONFIGURED")

    except Exception as e:
        print("Git remote check could not be completed:", e)

else:
    print("Git repository: NOT INITIALIZED")
    print("This is OK for the current pre-push audit.")

# ------------------------------------------------------------
# 11. REQUIRED FILE TOTAL SIZE
# ------------------------------------------------------------

total_bytes = 0

for relative_path in required_files:
    total_bytes += (project_dir / relative_path).stat().st_size

total_mb = total_bytes / (1024 * 1024)

print("\n" + "=" * 70)
print("PROJECT SIZE SUMMARY")
print("=" * 70)

print(f"Required project files: {len(required_files)}")
print(f"Combined size: {total_mb:.2f} MB")

# ------------------------------------------------------------
# 12. FINAL STATUS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL PRE-PUSH DECISION")
print("=" * 70)

print("Required files: PASSED")
print("File size limits: PASSED")
print(".gitignore: PASSED")
print("Credential safety scan: PASSED")

if git_installed:
    print("Git installation: PASSED")
else:
    print("Git installation: NOT AVAILABLE")

print("\nIMPORTANT:")
print("No git add was performed.")
print("No commit was created.")
print("No push was performed.")

print("\nSTATUS: STEP 31B COMPLETED SUCCESSFULLY")

======================================================================
STEP 31B — FINAL GITHUB PRE-PUSH SAFETY AUDIT
======================================================================
Project directory:
C:\Users\Krishna Prajapati\OneDrive\Desktop\Nassau_Candy_Optimization

======================================================================
REQUIRED FILE CHECK
======================================================================
[PASSED] README.md
[PASSED] requirements.txt
[PASSED] .gitignore
[PASSED] data/Nassau Candy Distributor.csv
[PASSED] models/nassau_slow_shipment_model.joblib
[PASSED] models/nassau_slow_shipment_model_metadata.json
[PASSED] notebooks/01_data_understanding.ipynb
[PASSED] results/factory_reallocation_scenarios.csv
[PASSED] results/factory_reallocation_recommendations.csv
[PASSED] results/final_factory_reallocation_recommendations.csv
[PASSED] results/random_forest_feature_importance.csv
[PASSED] results/random_forest_transformed_feature_importance.csv
[PASSED] results/random_forest_test_permutation_importance.csv
[PASSED] results/final_business_impact_summary.csv
[PASSED] results/final_business_priority_table.csv
Required file check: PASSED

======================================================================
FILE SIZE AUDIT
======================================================================
README.md                                                             0.00 MB  OK
requirements.txt                                                      0.00 MB  OK
.gitignore                                                            0.00 MB  OK
data/Nassau Candy Distributor.csv                                     1.89 MB  OK
models/nassau_slow_shipment_model.joblib                             26.63 MB  OK
models/nassau_slow_shipment_model_metadata.json                       0.00 MB  OK
notebooks/01_data_understanding.ipynb                                 0.59 MB  OK
results/factory_reallocation_scenarios.csv                            0.01 MB  OK
results/factory_reallocation_recommendations.csv                      0.00 MB  OK
results/final_factory_reallocation_recommendations.csv                0.00 MB  OK
results/random_forest_feature_importance.csv                          0.00 MB  OK
results/random_forest_transformed_feature_importance.csv              0.01 MB  OK
results/random_forest_test_permutation_importance.csv                 0.00 MB  OK
results/final_business_impact_summary.csv                             0.00 MB  OK
results/final_business_priority_table.csv                             0.00 MB  OK

File size audit: PASSED

======================================================================
.GITIGNORE AUDIT
======================================================================
[PASSED] .venv/
[PASSED] __pycache__/
[PASSED] .ipynb_checkpoints/
[PASSED] .env
[PASSED] .env.*
.gitignore audit: PASSED

======================================================================
CREDENTIAL SAFETY SCAN
======================================================================
Files selected for safety scan: 4
High-confidence credential scan: PASSED
No high-confidence API key/token/private-key pattern detected.

======================================================================
GIT ENVIRONMENT CHECK
======================================================================
Git: NOT FOUND
Git repository: NOT INITIALIZED
This is OK for the current pre-push audit.

======================================================================
PROJECT SIZE SUMMARY
======================================================================
Required project files: 15
Combined size: 29.15 MB

======================================================================
FINAL PRE-PUSH DECISION
======================================================================
Required files: PASSED
File size limits: PASSED
.gitignore: PASSED
Credential safety scan: PASSED
Git installation: NOT AVAILABLE

IMPORTANT:
No git add was performed.
No commit was created.
No push was performed.

STATUS: STEP 31B COMPLETED SUCCESSFULLY